// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>

namespace Protocol
{
	public enum InventorySourceType
	{
		/// <summary>Container Inventory</summary>
		ContainerInventory = 0,
		/// <summary>Global Inventory</summary>
		GlobalInventory = 1,
		/// <summary>World Interaction</summary>
		WorldInteraction = 2,
		/// <summary>Creative Inventory</summary>
		CreativeInventory = 3,
		/// <summary>Non Implemented Feature TODO</summary>
		NonImplementedFeatureTODO = 99999,
	}
}
