// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class InventorySource
	{
		public Protocol.InventorySourceType SourceType { get; set; } 
		public Optional<sbyte> ContainerID { get; set; } = new Optional<sbyte>();
		public Optional<Protocol.InventorySource.InventorySourceFlags> BitFlags { get; set; } = new Optional<Protocol.InventorySource.InventorySourceFlags>(); 

		public void Read(MemoryStreamReader reader)
		{
			SourceType = (Protocol.InventorySourceType)VarInt.ReadUInt32(reader); 
			reader.ReadByte(); // 常量标志位true
			if (reader.ReadByte() != 0)
			{
				ContainerID = new Optional<sbyte>((sbyte)reader.ReadByte());
			}
			reader.ReadByte(); // 常量标志位true
			if (reader.ReadByte() != 0)
			{
				BitFlags = new Optional<Protocol.InventorySource.InventorySourceFlags>((Protocol.InventorySource.InventorySourceFlags)VarInt.ReadUInt32(reader)); 
			}
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteVarUInt32((uint)SourceType); 
			writer.WriteByte(1); // 常量标志位
			if (ContainerID != null && ContainerID.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteByte((byte)ContainerID.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
			writer.WriteByte(1); // 常量标志位
			if (BitFlags != null && BitFlags.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteVarUInt32((uint)BitFlags.Value); 
			}
			else
			{
				writer.WriteByte(0);
			}
		}
	}
}
