// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class ItemReleaseInventoryTransaction
	{
		public InventoryTransaction Actions { get; set; }
		public Protocol.ItemReleaseInventoryTransaction.ActionType ActionType { get; set; } 
		public int Slot { get; set; } 
		public NetworkItemStackDescriptor.NetworkItemStackDescriptor Item { get; set; }
		public Vec3 FromPosition { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			Actions = new InventoryTransaction();
			Actions.Read(reader);
			ActionType = (Protocol.ItemReleaseInventoryTransaction.ActionType)VarInt.ReadInt32(reader); 
			Slot = VarInt.ReadInt32(reader); 
			Item = new NetworkItemStackDescriptor.NetworkItemStackDescriptor();
			Item.Read(reader);
			FromPosition = new Vec3();
			FromPosition.Read(reader);
		}

		public void Write(MemoryStreamWriter writer)
		{
			Actions.Write(writer);
			writer.WriteVarInt32((int)ActionType); 
			writer.WriteVarInt32(Slot); 
			Item.Write(writer);
			FromPosition.Write(writer);
		}
	}
}
