// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>

namespace Protocol.ItemUseInventoryTransaction
{
	public enum ActionType
	{
		Place = 0,
		Use = 1,
		Destroy = 2,
		/// <summary>Use As Attack</summary>
		UseAsAttack = 3,
	}
}
