// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>

namespace Protocol.ItemUseInventoryTransaction
{
	public enum TriggerType
	{
		Unknown = 0,
		/// <summary>Player Input</summary>
		PlayerInput = 1,
		/// <summary>Simulation Tick</summary>
		SimulationTick = 2,
	}
}
