// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class ItemUseInventoryTransaction
	{
		public InventoryTransaction Actions { get; set; }
		public Protocol.ItemUseInventoryTransaction.ActionType ActionType { get; set; } 
		public Protocol.ItemUseInventoryTransaction.TriggerType TriggerType { get; set; }
		public BlockPos Position { get; set; }
		public byte Face { get; set; }
		public int Slot { get; set; } 
		public NetworkItemStackDescriptor.NetworkItemStackDescriptor Item { get; set; }
		public Vec3 FromPosition { get; set; }
		public Vec3 ClickPosition { get; set; }
		public uint TargetBlockId { get; set; } 
		public Protocol.ItemUseInventoryTransaction.PredictedResult ClientInteractPrediction { get; set; }
		public Protocol.ItemUseInventoryTransaction.ClientCooldownState ClientCooldownState { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			Actions = new InventoryTransaction();
			Actions.Read(reader);
			ActionType = (Protocol.ItemUseInventoryTransaction.ActionType)VarInt.ReadInt32(reader); 
			TriggerType = (Protocol.ItemUseInventoryTransaction.TriggerType)reader.ReadByte();
			Position = new BlockPos();
			Position.Read(reader);
			Face = (byte)reader.ReadByte();
			Slot = VarInt.ReadInt32(reader); 
			Item = new NetworkItemStackDescriptor.NetworkItemStackDescriptor();
			Item.Read(reader);
			FromPosition = new Vec3();
			FromPosition.Read(reader);
			ClickPosition = new Vec3();
			ClickPosition.Read(reader);
			TargetBlockId = VarInt.ReadUInt32(reader); 
			ClientInteractPrediction = (Protocol.ItemUseInventoryTransaction.PredictedResult)reader.ReadByte();
			ClientCooldownState = (Protocol.ItemUseInventoryTransaction.ClientCooldownState)reader.ReadByte();
		}

		public void Write(MemoryStreamWriter writer)
		{
			Actions.Write(writer);
			writer.WriteVarInt32((int)ActionType); 
			writer.WriteByte((byte)TriggerType);
			Position.Write(writer);
			writer.WriteByte(Face);
			writer.WriteVarInt32(Slot); 
			Item.Write(writer);
			FromPosition.Write(writer);
			ClickPosition.Write(writer);
			writer.WriteVarUInt32(TargetBlockId); 
			writer.WriteByte((byte)ClientInteractPrediction);
			writer.WriteByte((byte)ClientCooldownState);
		}
	}
}
