// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class PackedItemUseLegacyInventoryTransaction
	{
		public TypedClientNetId_struct_ItemStackLegacyRequestIdTag_int32_t_0 LegacyRequestID { get; set; }
		public Optional<List<LegacySetSlot>> LegacySetItemSlots { get; set; } = new Optional<List<LegacySetSlot>>();
		public ItemUseInventoryTransaction ItemUseTransaction { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			LegacyRequestID = new TypedClientNetId_struct_ItemStackLegacyRequestIdTag_int32_t_0();
			LegacyRequestID.Read(reader);
			if (reader.ReadByte() != 0)
			{
				LegacySetItemSlots = new Optional<List<LegacySetSlot>>(reader.ReadSlice(() => { var _Item = new LegacySetSlot(); _Item.Read(reader); return _Item; }));
			}
			reader.ReadByte(); // 常量标志位true
			ItemUseTransaction = new ItemUseInventoryTransaction();
			ItemUseTransaction.Read(reader);
		}

		public void Write(MemoryStreamWriter writer)
		{
			LegacyRequestID.Write(writer);
			if (LegacySetItemSlots != null && LegacySetItemSlots.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteSlice(LegacySetItemSlots.Value, v => v.Write(writer));
			}
			else
			{
				writer.WriteByte(0);
			}
			writer.WriteByte(1); // 常量标志位
			ItemUseTransaction.Write(writer);
		}
	}
}
