// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.AttributeLayerSyncPacketData
{
	public class UpdateAttributeLayersData
	{
		public List<EAS.AttributeLayerData> AttributeLayers { get; set; } = new List<EAS.AttributeLayerData>();

		public void Read(MemoryStreamReader reader)
		{
			AttributeLayers = reader.ReadSlice(() => { var _Item = new EAS.AttributeLayerData(); _Item.Read(reader); return _Item; });
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteSlice(AttributeLayers, v => v.Write(writer));
		}
	}
}
