// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>

namespace Protocol
{
	public enum ItemStackRequestActionType
	{
		Take = 0,
		Place = 1,
		Swap = 2,
		Drop = 3,
		Destroy = 4,
		Consume = 5,
		Create = 6,
		PlaceInItemContainer = 7,
		TakeFromItemContainer = 8,
		ScreenLabTableCombine = 9,
		ScreenBeaconPayment = 10,
		ScreenHUDMineBlock = 11,
		CraftRecipe = 12,
		CraftRecipeAuto = 13,
		CraftCreative = 14,
		CraftRecipeOptional = 15,
		CraftRepairAndDisenchant = 16,
		CraftLoom = 17,
		CraftNonImplemented = 18,
		CraftResults = 19,
	}
}
