// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class ItemStackResponseContainerInfo
	{
		public FullContainerName FullContainerName { get; set; }
		public List<ItemStackResponseSlotInfo> Slots { get; set; } = new List<ItemStackResponseSlotInfo>();

		public void Read(MemoryStreamReader reader)
		{
			FullContainerName = new FullContainerName();
			FullContainerName.Read(reader);
			Slots = reader.ReadSlice(() => { var _Item = new ItemStackResponseSlotInfo(); _Item.Read(reader); return _Item; });
		}

		public void Write(MemoryStreamWriter writer)
		{
			FullContainerName.Write(writer);
			writer.WriteSlice(Slots, v => v.Write(writer));
		}
	}
}
