// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class ItemStackResponseSlotInfo
	{
		public byte RequestedSlot { get; set; }
		public byte Slot { get; set; }
		public byte Amount { get; set; }
		public Optional<TypedServerNetId_struct_ItemStackNetIdTag_int32_t_0> ItemStackNetId { get; set; } = new Optional<TypedServerNetId_struct_ItemStackNetIdTag_int32_t_0>();
		public Bedrock.Safety.RedactableString CustomName { get; set; }
		public int DurabilityCorrection { get; set; } 

		public void Read(MemoryStreamReader reader)
		{
			RequestedSlot = (byte)reader.ReadByte();
			Slot = (byte)reader.ReadByte();
			Amount = (byte)reader.ReadByte();
			reader.ReadByte(); // 常量标志位true
			if (reader.ReadByte() != 0)
			{
				var _ItemStackNetIdValue = new TypedServerNetId_struct_ItemStackNetIdTag_int32_t_0();
				_ItemStackNetIdValue.Read(reader);
				ItemStackNetId = new Optional<TypedServerNetId_struct_ItemStackNetIdTag_int32_t_0>(_ItemStackNetIdValue);
			}
			CustomName = new Bedrock.Safety.RedactableString();
			CustomName.Read(reader);
			DurabilityCorrection = VarInt.ReadInt32(reader); 
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteByte(RequestedSlot);
			writer.WriteByte(Slot);
			writer.WriteByte(Amount);
			writer.WriteByte(1); // 常量标志位
			if (ItemStackNetId != null && ItemStackNetId.HasValue)
			{
				writer.WriteByte(1);
				ItemStackNetId.Value.Write(writer);
			}
			else
			{
				writer.WriteByte(0);
			}
			CustomName.Write(writer);
			writer.WriteVarInt32(DurabilityCorrection); 
		}
	}
}
