// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class ItemEnchants
	{
		public int Slot { get; set; }
		public List<EnchantmentInstance> ItemEnchants_1 { get; set; } = new List<EnchantmentInstance>();
		public List<EnchantmentInstance> ItemEnchants_2 { get; set; } = new List<EnchantmentInstance>();
		public List<EnchantmentInstance> ItemEnchants_3 { get; set; } = new List<EnchantmentInstance>();

		public void Read(MemoryStreamReader reader)
		{
			Slot = reader.ReadInt32();
			ItemEnchants_1 = reader.ReadSlice(() => { var _Item = new EnchantmentInstance(); _Item.Read(reader); return _Item; });
			ItemEnchants_2 = reader.ReadSlice(() => { var _Item = new EnchantmentInstance(); _Item.Read(reader); return _Item; });
			ItemEnchants_3 = reader.ReadSlice(() => { var _Item = new EnchantmentInstance(); _Item.Read(reader); return _Item; });
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteInt32(Slot);
			writer.WriteSlice(ItemEnchants_1, v => v.Write(writer));
			writer.WriteSlice(ItemEnchants_2, v => v.Write(writer));
			writer.WriteSlice(ItemEnchants_3, v => v.Write(writer));
		}
	}
}
