// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class ItemStackResponseInfo
	{
		public Protocol.ItemStackNetResult Result { get; set; }
		public TypedClientNetId_struct_ItemStackRequestIdTag_int32_t_0 ClientRequestId { get; set; }
		public Optional<List<ItemStackResponseContainerInfo>> Containers { get; set; } = new Optional<List<ItemStackResponseContainerInfo>>();

		public void Read(MemoryStreamReader reader)
		{
			Result = (Protocol.ItemStackNetResult)reader.ReadByte();
			ClientRequestId = new TypedClientNetId_struct_ItemStackRequestIdTag_int32_t_0();
			ClientRequestId.Read(reader);
			reader.ReadByte(); // 常量标志位true
			if (reader.ReadByte() != 0)
			{
				Containers = new Optional<List<ItemStackResponseContainerInfo>>(reader.ReadSlice(() => { var _Item = new ItemStackResponseContainerInfo(); _Item.Read(reader); return _Item; }));
			}
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteByte((byte)Result);
			ClientRequestId.Write(writer);
			writer.WriteByte(1); // 常量标志位
			if (Containers != null && Containers.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteSlice(Containers.Value, v => v.Write(writer));
			}
			else
			{
				writer.WriteByte(0);
			}
		}
	}
}
