// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class ItemData
	{
		public string ItemName { get; set; }
		public short ItemId { get; set; }
		public bool IsComponentBased { get; set; }
		public Protocol.ItemVersion ItemVersion { get; set; } 
		public CompoundTag ItemComponentData { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			ItemName = reader.ReadLengthPrefixedString();
			ItemId = reader.ReadInt16();
			IsComponentBased = reader.ReadByte() != 0;
			ItemVersion = (Protocol.ItemVersion)VarInt.ReadInt32(reader); 
			ItemComponentData = new CompoundTag();
			ItemComponentData.Read(reader);
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(ItemName);
			writer.WriteInt16(ItemId);
			writer.WriteByte(IsComponentBased ? (byte)1 : (byte)0);
			writer.WriteVarInt32((int)ItemVersion); 
			ItemComponentData.Write(writer);
		}
	}
}
