// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.ItemStackRequestPacketData
{
	public class RequestData
	{
		public TypedClientNetId_struct_ItemStackRequestIdTag_int32_t_0 ClientRequestId { get; set; }
		public List<OneOf<ItemStackRequestCereal.TakeActionData, ItemStackRequestCereal.PlaceActionData, ItemStackRequestCereal.SwapActionData, ItemStackRequestCereal.DropActionData, ItemStackRequestCereal.DestroyActionData, ItemStackRequestCereal.ConsumeActionData, ItemStackRequestCereal.CreateActionData, ItemStackRequestCereal.LabTableCombineActionData, ItemStackRequestCereal.BeaconPaymentActionData, ItemStackRequestCereal.MineBlockActionData, ItemStackRequestCereal.CraftRecipeActionData, ItemStackRequestCereal.CraftRecipeAutoActionData, ItemStackRequestCereal.CraftCreativeActionData, ItemStackRequestCereal.CraftRecipeOptionalActionData, ItemStackRequestCereal.CraftRepairAndDisenchantActionData, ItemStackRequestCereal.CraftLoomActionData, ItemStackRequestCereal.CraftNonImplementedActionData, ItemStackRequestCereal.CraftResultsActionData>> Actions { get; set; } = new List<OneOf<ItemStackRequestCereal.TakeActionData, ItemStackRequestCereal.PlaceActionData, ItemStackRequestCereal.SwapActionData, ItemStackRequestCereal.DropActionData, ItemStackRequestCereal.DestroyActionData, ItemStackRequestCereal.ConsumeActionData, ItemStackRequestCereal.CreateActionData, ItemStackRequestCereal.LabTableCombineActionData, ItemStackRequestCereal.BeaconPaymentActionData, ItemStackRequestCereal.MineBlockActionData, ItemStackRequestCereal.CraftRecipeActionData, ItemStackRequestCereal.CraftRecipeAutoActionData, ItemStackRequestCereal.CraftCreativeActionData, ItemStackRequestCereal.CraftRecipeOptionalActionData, ItemStackRequestCereal.CraftRepairAndDisenchantActionData, ItemStackRequestCereal.CraftLoomActionData, ItemStackRequestCereal.CraftNonImplementedActionData, ItemStackRequestCereal.CraftResultsActionData>>();
		public List<string> StringsToFilter { get; set; } = new List<string>();
		public Protocol.TextProcessingEventOrigin StringsToFilterOrigin { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			ClientRequestId = new TypedClientNetId_struct_ItemStackRequestIdTag_int32_t_0();
			ClientRequestId.Read(reader);
			var _ActionsCount = VarInt.ReadUInt32(reader); 
			Actions.Clear();
			for (int i = 0; i < _ActionsCount; i++)
			{
				OneOf<ItemStackRequestCereal.TakeActionData, ItemStackRequestCereal.PlaceActionData, ItemStackRequestCereal.SwapActionData, ItemStackRequestCereal.DropActionData, ItemStackRequestCereal.DestroyActionData, ItemStackRequestCereal.ConsumeActionData, ItemStackRequestCereal.CreateActionData, ItemStackRequestCereal.LabTableCombineActionData, ItemStackRequestCereal.BeaconPaymentActionData, ItemStackRequestCereal.MineBlockActionData, ItemStackRequestCereal.CraftRecipeActionData, ItemStackRequestCereal.CraftRecipeAutoActionData, ItemStackRequestCereal.CraftCreativeActionData, ItemStackRequestCereal.CraftRecipeOptionalActionData, ItemStackRequestCereal.CraftRepairAndDisenchantActionData, ItemStackRequestCereal.CraftLoomActionData, ItemStackRequestCereal.CraftNonImplementedActionData, ItemStackRequestCereal.CraftResultsActionData> _ActionsItem = default;
				var _ActionsDisc = VarInt.ReadUInt32(reader); 
				switch (_ActionsDisc)
				{
					case 0:
					{
					var _ActionsCase0 = new ItemStackRequestCereal.TakeActionData();
					_ActionsCase0.Read(reader);
					_ActionsItem = OneOf<ItemStackRequestCereal.TakeActionData, ItemStackRequestCereal.PlaceActionData, ItemStackRequestCereal.SwapActionData, ItemStackRequestCereal.DropActionData, ItemStackRequestCereal.DestroyActionData, ItemStackRequestCereal.ConsumeActionData, ItemStackRequestCereal.CreateActionData, ItemStackRequestCereal.LabTableCombineActionData, ItemStackRequestCereal.BeaconPaymentActionData, ItemStackRequestCereal.MineBlockActionData, ItemStackRequestCereal.CraftRecipeActionData, ItemStackRequestCereal.CraftRecipeAutoActionData, ItemStackRequestCereal.CraftCreativeActionData, ItemStackRequestCereal.CraftRecipeOptionalActionData, ItemStackRequestCereal.CraftRepairAndDisenchantActionData, ItemStackRequestCereal.CraftLoomActionData, ItemStackRequestCereal.CraftNonImplementedActionData, ItemStackRequestCereal.CraftResultsActionData>.FromT0(_ActionsCase0);
					break;
					}
					case 1:
					{
					var _ActionsCase1 = new ItemStackRequestCereal.PlaceActionData();
					_ActionsCase1.Read(reader);
					_ActionsItem = OneOf<ItemStackRequestCereal.TakeActionData, ItemStackRequestCereal.PlaceActionData, ItemStackRequestCereal.SwapActionData, ItemStackRequestCereal.DropActionData, ItemStackRequestCereal.DestroyActionData, ItemStackRequestCereal.ConsumeActionData, ItemStackRequestCereal.CreateActionData, ItemStackRequestCereal.LabTableCombineActionData, ItemStackRequestCereal.BeaconPaymentActionData, ItemStackRequestCereal.MineBlockActionData, ItemStackRequestCereal.CraftRecipeActionData, ItemStackRequestCereal.CraftRecipeAutoActionData, ItemStackRequestCereal.CraftCreativeActionData, ItemStackRequestCereal.CraftRecipeOptionalActionData, ItemStackRequestCereal.CraftRepairAndDisenchantActionData, ItemStackRequestCereal.CraftLoomActionData, ItemStackRequestCereal.CraftNonImplementedActionData, ItemStackRequestCereal.CraftResultsActionData>.FromT1(_ActionsCase1);
					break;
					}
					case 2:
					{
					var _ActionsCase2 = new ItemStackRequestCereal.SwapActionData();
					_ActionsCase2.Read(reader);
					_ActionsItem = OneOf<ItemStackRequestCereal.TakeActionData, ItemStackRequestCereal.PlaceActionData, ItemStackRequestCereal.SwapActionData, ItemStackRequestCereal.DropActionData, ItemStackRequestCereal.DestroyActionData, ItemStackRequestCereal.ConsumeActionData, ItemStackRequestCereal.CreateActionData, ItemStackRequestCereal.LabTableCombineActionData, ItemStackRequestCereal.BeaconPaymentActionData, ItemStackRequestCereal.MineBlockActionData, ItemStackRequestCereal.CraftRecipeActionData, ItemStackRequestCereal.CraftRecipeAutoActionData, ItemStackRequestCereal.CraftCreativeActionData, ItemStackRequestCereal.CraftRecipeOptionalActionData, ItemStackRequestCereal.CraftRepairAndDisenchantActionData, ItemStackRequestCereal.CraftLoomActionData, ItemStackRequestCereal.CraftNonImplementedActionData, ItemStackRequestCereal.CraftResultsActionData>.FromT2(_ActionsCase2);
					break;
					}
					case 3:
					{
					var _ActionsCase3 = new ItemStackRequestCereal.DropActionData();
					_ActionsCase3.Read(reader);
					_ActionsItem = OneOf<ItemStackRequestCereal.TakeActionData, ItemStackRequestCereal.PlaceActionData, ItemStackRequestCereal.SwapActionData, ItemStackRequestCereal.DropActionData, ItemStackRequestCereal.DestroyActionData, ItemStackRequestCereal.ConsumeActionData, ItemStackRequestCereal.CreateActionData, ItemStackRequestCereal.LabTableCombineActionData, ItemStackRequestCereal.BeaconPaymentActionData, ItemStackRequestCereal.MineBlockActionData, ItemStackRequestCereal.CraftRecipeActionData, ItemStackRequestCereal.CraftRecipeAutoActionData, ItemStackRequestCereal.CraftCreativeActionData, ItemStackRequestCereal.CraftRecipeOptionalActionData, ItemStackRequestCereal.CraftRepairAndDisenchantActionData, ItemStackRequestCereal.CraftLoomActionData, ItemStackRequestCereal.CraftNonImplementedActionData, ItemStackRequestCereal.CraftResultsActionData>.FromT3(_ActionsCase3);
					break;
					}
					case 4:
					{
					var _ActionsCase4 = new ItemStackRequestCereal.DestroyActionData();
					_ActionsCase4.Read(reader);
					_ActionsItem = OneOf<ItemStackRequestCereal.TakeActionData, ItemStackRequestCereal.PlaceActionData, ItemStackRequestCereal.SwapActionData, ItemStackRequestCereal.DropActionData, ItemStackRequestCereal.DestroyActionData, ItemStackRequestCereal.ConsumeActionData, ItemStackRequestCereal.CreateActionData, ItemStackRequestCereal.LabTableCombineActionData, ItemStackRequestCereal.BeaconPaymentActionData, ItemStackRequestCereal.MineBlockActionData, ItemStackRequestCereal.CraftRecipeActionData, ItemStackRequestCereal.CraftRecipeAutoActionData, ItemStackRequestCereal.CraftCreativeActionData, ItemStackRequestCereal.CraftRecipeOptionalActionData, ItemStackRequestCereal.CraftRepairAndDisenchantActionData, ItemStackRequestCereal.CraftLoomActionData, ItemStackRequestCereal.CraftNonImplementedActionData, ItemStackRequestCereal.CraftResultsActionData>.FromT4(_ActionsCase4);
					break;
					}
					case 5:
					{
					var _ActionsCase5 = new ItemStackRequestCereal.ConsumeActionData();
					_ActionsCase5.Read(reader);
					_ActionsItem = OneOf<ItemStackRequestCereal.TakeActionData, ItemStackRequestCereal.PlaceActionData, ItemStackRequestCereal.SwapActionData, ItemStackRequestCereal.DropActionData, ItemStackRequestCereal.DestroyActionData, ItemStackRequestCereal.ConsumeActionData, ItemStackRequestCereal.CreateActionData, ItemStackRequestCereal.LabTableCombineActionData, ItemStackRequestCereal.BeaconPaymentActionData, ItemStackRequestCereal.MineBlockActionData, ItemStackRequestCereal.CraftRecipeActionData, ItemStackRequestCereal.CraftRecipeAutoActionData, ItemStackRequestCereal.CraftCreativeActionData, ItemStackRequestCereal.CraftRecipeOptionalActionData, ItemStackRequestCereal.CraftRepairAndDisenchantActionData, ItemStackRequestCereal.CraftLoomActionData, ItemStackRequestCereal.CraftNonImplementedActionData, ItemStackRequestCereal.CraftResultsActionData>.FromT5(_ActionsCase5);
					break;
					}
					case 6:
					{
					var _ActionsCase6 = new ItemStackRequestCereal.CreateActionData();
					_ActionsCase6.Read(reader);
					_ActionsItem = OneOf<ItemStackRequestCereal.TakeActionData, ItemStackRequestCereal.PlaceActionData, ItemStackRequestCereal.SwapActionData, ItemStackRequestCereal.DropActionData, ItemStackRequestCereal.DestroyActionData, ItemStackRequestCereal.ConsumeActionData, ItemStackRequestCereal.CreateActionData, ItemStackRequestCereal.LabTableCombineActionData, ItemStackRequestCereal.BeaconPaymentActionData, ItemStackRequestCereal.MineBlockActionData, ItemStackRequestCereal.CraftRecipeActionData, ItemStackRequestCereal.CraftRecipeAutoActionData, ItemStackRequestCereal.CraftCreativeActionData, ItemStackRequestCereal.CraftRecipeOptionalActionData, ItemStackRequestCereal.CraftRepairAndDisenchantActionData, ItemStackRequestCereal.CraftLoomActionData, ItemStackRequestCereal.CraftNonImplementedActionData, ItemStackRequestCereal.CraftResultsActionData>.FromT6(_ActionsCase6);
					break;
					}
					case 7:
					{
					var _ActionsCase7 = new ItemStackRequestCereal.LabTableCombineActionData();
					_ActionsCase7.Read(reader);
					_ActionsItem = OneOf<ItemStackRequestCereal.TakeActionData, ItemStackRequestCereal.PlaceActionData, ItemStackRequestCereal.SwapActionData, ItemStackRequestCereal.DropActionData, ItemStackRequestCereal.DestroyActionData, ItemStackRequestCereal.ConsumeActionData, ItemStackRequestCereal.CreateActionData, ItemStackRequestCereal.LabTableCombineActionData, ItemStackRequestCereal.BeaconPaymentActionData, ItemStackRequestCereal.MineBlockActionData, ItemStackRequestCereal.CraftRecipeActionData, ItemStackRequestCereal.CraftRecipeAutoActionData, ItemStackRequestCereal.CraftCreativeActionData, ItemStackRequestCereal.CraftRecipeOptionalActionData, ItemStackRequestCereal.CraftRepairAndDisenchantActionData, ItemStackRequestCereal.CraftLoomActionData, ItemStackRequestCereal.CraftNonImplementedActionData, ItemStackRequestCereal.CraftResultsActionData>.FromT7(_ActionsCase7);
					break;
					}
					case 8:
					{
					var _ActionsCase8 = new ItemStackRequestCereal.BeaconPaymentActionData();
					_ActionsCase8.Read(reader);
					_ActionsItem = OneOf<ItemStackRequestCereal.TakeActionData, ItemStackRequestCereal.PlaceActionData, ItemStackRequestCereal.SwapActionData, ItemStackRequestCereal.DropActionData, ItemStackRequestCereal.DestroyActionData, ItemStackRequestCereal.ConsumeActionData, ItemStackRequestCereal.CreateActionData, ItemStackRequestCereal.LabTableCombineActionData, ItemStackRequestCereal.BeaconPaymentActionData, ItemStackRequestCereal.MineBlockActionData, ItemStackRequestCereal.CraftRecipeActionData, ItemStackRequestCereal.CraftRecipeAutoActionData, ItemStackRequestCereal.CraftCreativeActionData, ItemStackRequestCereal.CraftRecipeOptionalActionData, ItemStackRequestCereal.CraftRepairAndDisenchantActionData, ItemStackRequestCereal.CraftLoomActionData, ItemStackRequestCereal.CraftNonImplementedActionData, ItemStackRequestCereal.CraftResultsActionData>.FromT8(_ActionsCase8);
					break;
					}
					case 9:
					{
					var _ActionsCase9 = new ItemStackRequestCereal.MineBlockActionData();
					_ActionsCase9.Read(reader);
					_ActionsItem = OneOf<ItemStackRequestCereal.TakeActionData, ItemStackRequestCereal.PlaceActionData, ItemStackRequestCereal.SwapActionData, ItemStackRequestCereal.DropActionData, ItemStackRequestCereal.DestroyActionData, ItemStackRequestCereal.ConsumeActionData, ItemStackRequestCereal.CreateActionData, ItemStackRequestCereal.LabTableCombineActionData, ItemStackRequestCereal.BeaconPaymentActionData, ItemStackRequestCereal.MineBlockActionData, ItemStackRequestCereal.CraftRecipeActionData, ItemStackRequestCereal.CraftRecipeAutoActionData, ItemStackRequestCereal.CraftCreativeActionData, ItemStackRequestCereal.CraftRecipeOptionalActionData, ItemStackRequestCereal.CraftRepairAndDisenchantActionData, ItemStackRequestCereal.CraftLoomActionData, ItemStackRequestCereal.CraftNonImplementedActionData, ItemStackRequestCereal.CraftResultsActionData>.FromT9(_ActionsCase9);
					break;
					}
					case 10:
					{
					var _ActionsCase10 = new ItemStackRequestCereal.CraftRecipeActionData();
					_ActionsCase10.Read(reader);
					_ActionsItem = OneOf<ItemStackRequestCereal.TakeActionData, ItemStackRequestCereal.PlaceActionData, ItemStackRequestCereal.SwapActionData, ItemStackRequestCereal.DropActionData, ItemStackRequestCereal.DestroyActionData, ItemStackRequestCereal.ConsumeActionData, ItemStackRequestCereal.CreateActionData, ItemStackRequestCereal.LabTableCombineActionData, ItemStackRequestCereal.BeaconPaymentActionData, ItemStackRequestCereal.MineBlockActionData, ItemStackRequestCereal.CraftRecipeActionData, ItemStackRequestCereal.CraftRecipeAutoActionData, ItemStackRequestCereal.CraftCreativeActionData, ItemStackRequestCereal.CraftRecipeOptionalActionData, ItemStackRequestCereal.CraftRepairAndDisenchantActionData, ItemStackRequestCereal.CraftLoomActionData, ItemStackRequestCereal.CraftNonImplementedActionData, ItemStackRequestCereal.CraftResultsActionData>.FromT10(_ActionsCase10);
					break;
					}
					case 11:
					{
					var _ActionsCase11 = new ItemStackRequestCereal.CraftRecipeAutoActionData();
					_ActionsCase11.Read(reader);
					_ActionsItem = OneOf<ItemStackRequestCereal.TakeActionData, ItemStackRequestCereal.PlaceActionData, ItemStackRequestCereal.SwapActionData, ItemStackRequestCereal.DropActionData, ItemStackRequestCereal.DestroyActionData, ItemStackRequestCereal.ConsumeActionData, ItemStackRequestCereal.CreateActionData, ItemStackRequestCereal.LabTableCombineActionData, ItemStackRequestCereal.BeaconPaymentActionData, ItemStackRequestCereal.MineBlockActionData, ItemStackRequestCereal.CraftRecipeActionData, ItemStackRequestCereal.CraftRecipeAutoActionData, ItemStackRequestCereal.CraftCreativeActionData, ItemStackRequestCereal.CraftRecipeOptionalActionData, ItemStackRequestCereal.CraftRepairAndDisenchantActionData, ItemStackRequestCereal.CraftLoomActionData, ItemStackRequestCereal.CraftNonImplementedActionData, ItemStackRequestCereal.CraftResultsActionData>.FromT11(_ActionsCase11);
					break;
					}
					case 12:
					{
					var _ActionsCase12 = new ItemStackRequestCereal.CraftCreativeActionData();
					_ActionsCase12.Read(reader);
					_ActionsItem = OneOf<ItemStackRequestCereal.TakeActionData, ItemStackRequestCereal.PlaceActionData, ItemStackRequestCereal.SwapActionData, ItemStackRequestCereal.DropActionData, ItemStackRequestCereal.DestroyActionData, ItemStackRequestCereal.ConsumeActionData, ItemStackRequestCereal.CreateActionData, ItemStackRequestCereal.LabTableCombineActionData, ItemStackRequestCereal.BeaconPaymentActionData, ItemStackRequestCereal.MineBlockActionData, ItemStackRequestCereal.CraftRecipeActionData, ItemStackRequestCereal.CraftRecipeAutoActionData, ItemStackRequestCereal.CraftCreativeActionData, ItemStackRequestCereal.CraftRecipeOptionalActionData, ItemStackRequestCereal.CraftRepairAndDisenchantActionData, ItemStackRequestCereal.CraftLoomActionData, ItemStackRequestCereal.CraftNonImplementedActionData, ItemStackRequestCereal.CraftResultsActionData>.FromT12(_ActionsCase12);
					break;
					}
					case 13:
					{
					var _ActionsCase13 = new ItemStackRequestCereal.CraftRecipeOptionalActionData();
					_ActionsCase13.Read(reader);
					_ActionsItem = OneOf<ItemStackRequestCereal.TakeActionData, ItemStackRequestCereal.PlaceActionData, ItemStackRequestCereal.SwapActionData, ItemStackRequestCereal.DropActionData, ItemStackRequestCereal.DestroyActionData, ItemStackRequestCereal.ConsumeActionData, ItemStackRequestCereal.CreateActionData, ItemStackRequestCereal.LabTableCombineActionData, ItemStackRequestCereal.BeaconPaymentActionData, ItemStackRequestCereal.MineBlockActionData, ItemStackRequestCereal.CraftRecipeActionData, ItemStackRequestCereal.CraftRecipeAutoActionData, ItemStackRequestCereal.CraftCreativeActionData, ItemStackRequestCereal.CraftRecipeOptionalActionData, ItemStackRequestCereal.CraftRepairAndDisenchantActionData, ItemStackRequestCereal.CraftLoomActionData, ItemStackRequestCereal.CraftNonImplementedActionData, ItemStackRequestCereal.CraftResultsActionData>.FromT13(_ActionsCase13);
					break;
					}
					case 14:
					{
					var _ActionsCase14 = new ItemStackRequestCereal.CraftRepairAndDisenchantActionData();
					_ActionsCase14.Read(reader);
					_ActionsItem = OneOf<ItemStackRequestCereal.TakeActionData, ItemStackRequestCereal.PlaceActionData, ItemStackRequestCereal.SwapActionData, ItemStackRequestCereal.DropActionData, ItemStackRequestCereal.DestroyActionData, ItemStackRequestCereal.ConsumeActionData, ItemStackRequestCereal.CreateActionData, ItemStackRequestCereal.LabTableCombineActionData, ItemStackRequestCereal.BeaconPaymentActionData, ItemStackRequestCereal.MineBlockActionData, ItemStackRequestCereal.CraftRecipeActionData, ItemStackRequestCereal.CraftRecipeAutoActionData, ItemStackRequestCereal.CraftCreativeActionData, ItemStackRequestCereal.CraftRecipeOptionalActionData, ItemStackRequestCereal.CraftRepairAndDisenchantActionData, ItemStackRequestCereal.CraftLoomActionData, ItemStackRequestCereal.CraftNonImplementedActionData, ItemStackRequestCereal.CraftResultsActionData>.FromT14(_ActionsCase14);
					break;
					}
					case 15:
					{
					var _ActionsCase15 = new ItemStackRequestCereal.CraftLoomActionData();
					_ActionsCase15.Read(reader);
					_ActionsItem = OneOf<ItemStackRequestCereal.TakeActionData, ItemStackRequestCereal.PlaceActionData, ItemStackRequestCereal.SwapActionData, ItemStackRequestCereal.DropActionData, ItemStackRequestCereal.DestroyActionData, ItemStackRequestCereal.ConsumeActionData, ItemStackRequestCereal.CreateActionData, ItemStackRequestCereal.LabTableCombineActionData, ItemStackRequestCereal.BeaconPaymentActionData, ItemStackRequestCereal.MineBlockActionData, ItemStackRequestCereal.CraftRecipeActionData, ItemStackRequestCereal.CraftRecipeAutoActionData, ItemStackRequestCereal.CraftCreativeActionData, ItemStackRequestCereal.CraftRecipeOptionalActionData, ItemStackRequestCereal.CraftRepairAndDisenchantActionData, ItemStackRequestCereal.CraftLoomActionData, ItemStackRequestCereal.CraftNonImplementedActionData, ItemStackRequestCereal.CraftResultsActionData>.FromT15(_ActionsCase15);
					break;
					}
					case 16:
					{
					var _ActionsCase16 = new ItemStackRequestCereal.CraftNonImplementedActionData();
					_ActionsCase16.Read(reader);
					_ActionsItem = OneOf<ItemStackRequestCereal.TakeActionData, ItemStackRequestCereal.PlaceActionData, ItemStackRequestCereal.SwapActionData, ItemStackRequestCereal.DropActionData, ItemStackRequestCereal.DestroyActionData, ItemStackRequestCereal.ConsumeActionData, ItemStackRequestCereal.CreateActionData, ItemStackRequestCereal.LabTableCombineActionData, ItemStackRequestCereal.BeaconPaymentActionData, ItemStackRequestCereal.MineBlockActionData, ItemStackRequestCereal.CraftRecipeActionData, ItemStackRequestCereal.CraftRecipeAutoActionData, ItemStackRequestCereal.CraftCreativeActionData, ItemStackRequestCereal.CraftRecipeOptionalActionData, ItemStackRequestCereal.CraftRepairAndDisenchantActionData, ItemStackRequestCereal.CraftLoomActionData, ItemStackRequestCereal.CraftNonImplementedActionData, ItemStackRequestCereal.CraftResultsActionData>.FromT16(_ActionsCase16);
					break;
					}
					case 17:
					{
					var _ActionsCase17 = new ItemStackRequestCereal.CraftResultsActionData();
					_ActionsCase17.Read(reader);
					_ActionsItem = OneOf<ItemStackRequestCereal.TakeActionData, ItemStackRequestCereal.PlaceActionData, ItemStackRequestCereal.SwapActionData, ItemStackRequestCereal.DropActionData, ItemStackRequestCereal.DestroyActionData, ItemStackRequestCereal.ConsumeActionData, ItemStackRequestCereal.CreateActionData, ItemStackRequestCereal.LabTableCombineActionData, ItemStackRequestCereal.BeaconPaymentActionData, ItemStackRequestCereal.MineBlockActionData, ItemStackRequestCereal.CraftRecipeActionData, ItemStackRequestCereal.CraftRecipeAutoActionData, ItemStackRequestCereal.CraftCreativeActionData, ItemStackRequestCereal.CraftRecipeOptionalActionData, ItemStackRequestCereal.CraftRepairAndDisenchantActionData, ItemStackRequestCereal.CraftLoomActionData, ItemStackRequestCereal.CraftNonImplementedActionData, ItemStackRequestCereal.CraftResultsActionData>.FromT17(_ActionsCase17);
					break;
					}
					default:
						throw new InvalidDataException("Unknown Actions discriminant: " + _ActionsDisc);
				}
				Actions.Add(_ActionsItem);
			}
			StringsToFilter = reader.ReadSlice(() => reader.ReadLengthPrefixedString());
			StringsToFilterOrigin = (Protocol.TextProcessingEventOrigin)reader.ReadInt32();
		}

		public void Write(MemoryStreamWriter writer)
		{
			ClientRequestId.Write(writer);
			writer.WriteVarUInt32((uint)Actions.Count); 
			foreach (var _ActionsItem in Actions)
			{
				writer.WriteVarUInt32((uint)_ActionsItem.Index); 
				switch (_ActionsItem.Index)
				{
					case 0:
					{
					_ActionsItem.AsT0.Write(writer);
					break;
					}
					case 1:
					{
					_ActionsItem.AsT1.Write(writer);
					break;
					}
					case 2:
					{
					_ActionsItem.AsT2.Write(writer);
					break;
					}
					case 3:
					{
					_ActionsItem.AsT3.Write(writer);
					break;
					}
					case 4:
					{
					_ActionsItem.AsT4.Write(writer);
					break;
					}
					case 5:
					{
					_ActionsItem.AsT5.Write(writer);
					break;
					}
					case 6:
					{
					_ActionsItem.AsT6.Write(writer);
					break;
					}
					case 7:
					{
					_ActionsItem.AsT7.Write(writer);
					break;
					}
					case 8:
					{
					_ActionsItem.AsT8.Write(writer);
					break;
					}
					case 9:
					{
					_ActionsItem.AsT9.Write(writer);
					break;
					}
					case 10:
					{
					_ActionsItem.AsT10.Write(writer);
					break;
					}
					case 11:
					{
					_ActionsItem.AsT11.Write(writer);
					break;
					}
					case 12:
					{
					_ActionsItem.AsT12.Write(writer);
					break;
					}
					case 13:
					{
					_ActionsItem.AsT13.Write(writer);
					break;
					}
					case 14:
					{
					_ActionsItem.AsT14.Write(writer);
					break;
					}
					case 15:
					{
					_ActionsItem.AsT15.Write(writer);
					break;
					}
					case 16:
					{
					_ActionsItem.AsT16.Write(writer);
					break;
					}
					case 17:
					{
					_ActionsItem.AsT17.Write(writer);
					break;
					}
					default:
						throw new InvalidDataException("Invalid Actions OneOf index: " + _ActionsItem.Index);
				}
			}
			writer.WriteSlice(StringsToFilter, v => writer.WriteLengthPrefixedString(v));
			writer.WriteInt32((int)StringsToFilterOrigin);
		}
	}
}
