// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.NetworkItemStackDescriptor
{
	public class NetworkItemStackDescriptor
	{
		public short Id { get; set; }
		public ushort StackSize { get; set; }
		public uint AuxValue { get; set; } 
		public Optional<int> NetIdVariant { get; set; } = new Optional<int>(); 
		public uint BlockRuntimeId { get; set; } 
		public string UserDataBuffer { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			Id = reader.ReadInt16();
			StackSize = reader.ReadUInt16();
			AuxValue = VarInt.ReadUInt32(reader); 
			if (reader.ReadByte() != 0)
			{
				NetIdVariant = new Optional<int>(VarInt.ReadInt32(reader)); 
			}
			BlockRuntimeId = VarInt.ReadUInt32(reader); 
			UserDataBuffer = reader.ReadLengthPrefixedString();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteInt16(Id);
			writer.WriteUInt16(StackSize);
			writer.WriteVarUInt32(AuxValue); 
			if (NetIdVariant != null && NetIdVariant.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteVarInt32(NetIdVariant.Value); 
			}
			else
			{
				writer.WriteByte(0);
			}
			writer.WriteVarUInt32(BlockRuntimeId); 
			writer.WriteLengthPrefixedString(UserDataBuffer);
		}
	}
}
