// <auto-generated>
//     Stub: 文档中引用但未定义的类型, 请手动实现
// </auto-generated>
using System;
using System.Collections.Generic;
using System.IO;
using OneOf;
using Protocol.Utility.IO;

namespace Protocol.Types.cereal
{
	public class DynamicValue
	{
		public OneOf<bool, long, double, string, List<DynamicValue>, Dictionary<string, DynamicValue>>? Value { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			uint _Disc = reader.ReadUInt32();
			switch (_Disc)
			{
				case 0:
				{
					Value = null;
					break;
				}
				case 1:
				{
					Value = reader.ReadByte() != 0;
					break;
				}
				case 2:
				{
					Value = reader.ReadInt64();
					break;
				}
				case 3:
				{
					Value = reader.ReadDouble();
					break;
				}
				case 4:
				{
					Value = reader.ReadLengthPrefixedString();
					break;
				}
				case 5:
				{
					var _List = new List<DynamicValue>();
					uint _Count = VarInt.ReadUInt32(reader);
					for (int i = 0; i < _Count; i++)
					{
						var _Item = new DynamicValue();
						_Item.Read(reader);
						_List.Add(_Item);
					}
					Value = _List;
					break;
				}
				case 6:
				{
					var _Map = new Dictionary<string, DynamicValue>();
					uint _Count = VarInt.ReadUInt32(reader);
					for (int i = 0; i < _Count; i++)
					{
						var _Key = reader.ReadLengthPrefixedString();
						var _Item = new DynamicValue();
						_Item.Read(reader);
						_Map[_Key] = _Item;
					}
					Value = _Map;
					break;
				}
				default:
					throw new InvalidDataException("Unknown DynamicValue discriminant: " + _Disc);
			}
		}

		public void Write(MemoryStreamWriter writer)
		{
			if (Value == null)
			{
				writer.WriteUInt32(0);
				return;
			}

			switch (Value.Value.Index)
			{
				case 0:
				{
					writer.WriteUInt32(1);
					writer.WriteByte(Value.Value.AsT0 ? (byte)1 : (byte)0);
					break;
				}
				case 1:
				{
					writer.WriteUInt32(2);
					writer.WriteInt64(Value.Value.AsT1);
					break;
				}
				case 2:
				{
					writer.WriteUInt32(3);
					writer.WriteDouble(Value.Value.AsT2);
					break;
				}
				case 3:
				{
					writer.WriteUInt32(4);
					writer.WriteLengthPrefixedString(Value.Value.AsT3);
					break;
				}
				case 4:
				{
					writer.WriteUInt32(5);
					writer.WriteVarUInt32((uint)Value.Value.AsT4.Count);
					foreach (var item in Value.Value.AsT4)
					{
						item.Write(writer);
					}
					break;
				}
				case 5:
				{
					writer.WriteUInt32(6);
					writer.WriteVarUInt32((uint)Value.Value.AsT5.Count);
					foreach (var pair in Value.Value.AsT5)
					{
						writer.WriteLengthPrefixedString(pair.Key);
						pair.Value.Write(writer);
					}
					break;
				}
				default:
					throw new InvalidDataException("Invalid DynamicValue OneOf index: " + Value.Value.Index);
			}
		}
	}
}
