// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.ItemStackRequestCereal
{
	public class CraftLoomActionData
	{
		public Protocol.ItemStackRequestActionType ActionType { get; set; }
		public string PatternNameId { get; set; }
		public byte NumCrafts { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			ActionType = (Protocol.ItemStackRequestActionType)reader.ReadByte();
			PatternNameId = reader.ReadLengthPrefixedString();
			NumCrafts = (byte)reader.ReadByte();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteByte((byte)ActionType);
			writer.WriteLengthPrefixedString(PatternNameId);
			writer.WriteByte(NumCrafts);
		}
	}
}
