// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.ItemStackRequestCereal
{
	public class CraftRepairAndDisenchantActionData
	{
		public Protocol.ItemStackRequestActionType ActionType { get; set; }
		public int RecipeNetId { get; set; }
		public byte NumberOfRequestedCrafts { get; set; }
		public int RepairCost { get; set; } 

		public void Read(MemoryStreamReader reader)
		{
			ActionType = (Protocol.ItemStackRequestActionType)reader.ReadByte();
			RecipeNetId = reader.ReadInt32();
			NumberOfRequestedCrafts = (byte)reader.ReadByte();
			RepairCost = VarInt.ReadInt32(reader); 
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteByte((byte)ActionType);
			writer.WriteInt32(RecipeNetId);
			writer.WriteByte(NumberOfRequestedCrafts);
			writer.WriteVarInt32(RepairCost); 
		}
	}
}
