// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.ItemStackRequestCereal
{
	public class SlotInfoData
	{
		public FullContainerName FullContainerName { get; set; }
		public byte Slot { get; set; }
		public int NetIdVariant { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			FullContainerName = new FullContainerName();
			FullContainerName.Read(reader);
			Slot = (byte)reader.ReadByte();
			NetIdVariant = reader.ReadInt32();
		}

		public void Write(MemoryStreamWriter writer)
		{
			FullContainerName.Write(writer);
			writer.WriteByte(Slot);
			writer.WriteInt32(NetIdVariant);
		}
	}
}
