// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.ItemStackRequestCereal
{
	public class CraftRecipeActionData
	{
		public Protocol.ItemStackRequestActionType ActionType { get; set; }
		public TypedServerNetId_struct_RecipeNetIdTag RecipeNetId { get; set; }
		public byte NumberOfRequestedCrafts { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			ActionType = (Protocol.ItemStackRequestActionType)reader.ReadByte();
			RecipeNetId = new TypedServerNetId_struct_RecipeNetIdTag();
			RecipeNetId.Read(reader);
			NumberOfRequestedCrafts = (byte)reader.ReadByte();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteByte((byte)ActionType);
			RecipeNetId.Write(writer);
			writer.WriteByte(NumberOfRequestedCrafts);
		}
	}
}
