// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.ItemStackRequestCereal
{
	public class NetworkItemInstanceDescriptorData
	{
		public OneOf<EmptyItemDescriptorData, ItemNameDescriptorData, MolangItemDescriptorData, ItemTagDescriptorData> ItemDescriptor { get; set; }
		public ushort StackSize { get; set; }
		public uint BlockRuntimeId { get; set; } 
		public byte[] UserDataBuffer { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			var _ItemDescriptorDisc = VarInt.ReadUInt32(reader); 
			switch (_ItemDescriptorDisc)
			{
				case 0:
				{
				var _ItemDescriptorCase0 = new EmptyItemDescriptorData();
				_ItemDescriptorCase0.Read(reader);
				ItemDescriptor = OneOf<EmptyItemDescriptorData, ItemNameDescriptorData, MolangItemDescriptorData, ItemTagDescriptorData>.FromT0(_ItemDescriptorCase0);
				break;
				}
				case 1:
				{
				var _ItemDescriptorCase1 = new ItemNameDescriptorData();
				_ItemDescriptorCase1.Read(reader);
				ItemDescriptor = OneOf<EmptyItemDescriptorData, ItemNameDescriptorData, MolangItemDescriptorData, ItemTagDescriptorData>.FromT1(_ItemDescriptorCase1);
				break;
				}
				case 2:
				{
				var _ItemDescriptorCase2 = new MolangItemDescriptorData();
				_ItemDescriptorCase2.Read(reader);
				ItemDescriptor = OneOf<EmptyItemDescriptorData, ItemNameDescriptorData, MolangItemDescriptorData, ItemTagDescriptorData>.FromT2(_ItemDescriptorCase2);
				break;
				}
				case 3:
				{
				var _ItemDescriptorCase3 = new ItemTagDescriptorData();
				_ItemDescriptorCase3.Read(reader);
				ItemDescriptor = OneOf<EmptyItemDescriptorData, ItemNameDescriptorData, MolangItemDescriptorData, ItemTagDescriptorData>.FromT3(_ItemDescriptorCase3);
				break;
				}
				default:
					throw new InvalidDataException("Unknown ItemDescriptor discriminant: " + _ItemDescriptorDisc);
			}
			StackSize = reader.ReadUInt16();
			BlockRuntimeId = VarInt.ReadUInt32(reader); 
			UserDataBuffer = reader.ReadLengthPrefixedBytes().ToArray();
		}

		public void Write(MemoryStreamWriter writer)
		{
			switch (ItemDescriptor.Index)
			{
				case 0:
				{
				writer.WriteVarUInt32((uint)ItemDescriptor.Index); 
				ItemDescriptor.AsT0.Write(writer);
				break;
				}
				case 1:
				{
				writer.WriteVarUInt32((uint)ItemDescriptor.Index); 
				ItemDescriptor.AsT1.Write(writer);
				break;
				}
				case 2:
				{
				writer.WriteVarUInt32((uint)ItemDescriptor.Index); 
				ItemDescriptor.AsT2.Write(writer);
				break;
				}
				case 3:
				{
				writer.WriteVarUInt32((uint)ItemDescriptor.Index); 
				ItemDescriptor.AsT3.Write(writer);
				break;
				}
				default:
					throw new InvalidDataException("Invalid ItemDescriptor OneOf index: " + ItemDescriptor.Index);
			}
			writer.WriteUInt16(StackSize);
			writer.WriteVarUInt32(BlockRuntimeId); 
			writer.WriteLengthPrefixedBytes(UserDataBuffer);
		}
	}
}
