// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.ItemStackRequestCereal
{
	public class BeaconPaymentActionData
	{
		public Protocol.ItemStackRequestActionType ActionType { get; set; }
		public int PrimaryEffectId { get; set; } 
		public int SecondaryEffectId { get; set; } 

		public void Read(MemoryStreamReader reader)
		{
			ActionType = (Protocol.ItemStackRequestActionType)reader.ReadByte();
			PrimaryEffectId = VarInt.ReadInt32(reader); 
			SecondaryEffectId = VarInt.ReadInt32(reader); 
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteByte((byte)ActionType);
			writer.WriteVarInt32(PrimaryEffectId); 
			writer.WriteVarInt32(SecondaryEffectId); 
		}
	}
}
