// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>

namespace Protocol.ItemStackRequestCereal
{
	public enum ItemDescriptorType
	{
		Empty = 0,
		ItemName = 1,
		Molang = 2,
		ItemTag = 3,
	}
}
