// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.ItemStackRequestCereal
{
	public class EmptyItemDescriptorData
	{
		public Protocol.ItemStackRequestCereal.ItemDescriptorType DescriptorType { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			DescriptorType = (Protocol.ItemStackRequestCereal.ItemDescriptorType)reader.ReadByte();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteByte((byte)DescriptorType);
		}
	}
}
