// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>

namespace Protocol
{
	public enum TextProcessingEventOrigin
	{
		/// <summary>unknown</summary>
		Unknown = -1,
		ServerChatPublic = 0,
		ServerChatWhisper = 1,
		SignText = 2,
		AnvilText = 3,
		BookAndQuillText = 4,
		CommandBlockText = 5,
		BlockActorDataText = 6,
		JoinEventText = 7,
		LeaveEventText = 8,
		SlashCommandChat = 9,
		CartographyText = 10,
		KickCommand = 11,
		TitleCommand = 12,
		SummonCommand = 13,
		ServerForm = 14,
		DataDrivenUI = 15,
	}
}
