// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.ECS.Profiling.Diagnostics
{
	public class EntityDiagnosticTimingInfo
	{
		public string DisplayName { get; set; }
		public string Entity { get; set; }
		public ulong TimeInNS { get; set; }
		public byte PercentOfTotal { get; set; }
		public Optional<Vec3> Position { get; set; } = new Optional<Vec3>();
		public Optional<string> Dimension { get; set; } = new Optional<string>();

		public void Read(MemoryStreamReader reader)
		{
			DisplayName = reader.ReadLengthPrefixedString();
			Entity = reader.ReadLengthPrefixedString();
			TimeInNS = reader.ReadUInt64();
			PercentOfTotal = (byte)reader.ReadByte();
			if (reader.ReadByte() != 0)
			{
				var _PositionValue = new Vec3();
				_PositionValue.Read(reader);
				Position = new Optional<Vec3>(_PositionValue);
			}
			if (reader.ReadByte() != 0)
			{
				Dimension = new Optional<string>(reader.ReadLengthPrefixedString());
			}
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(DisplayName);
			writer.WriteLengthPrefixedString(Entity);
			writer.WriteUInt64(TimeInNS);
			writer.WriteByte(PercentOfTotal);
			if (Position != null && Position.HasValue)
			{
				writer.WriteByte(1);
				Position.Value.Write(writer);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (Dimension != null && Dimension.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteLengthPrefixedString(Dimension.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
		}
	}
}
