// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.ECS.Profiling.Diagnostics
{
	public class SystemDiagnosticTimingInfo
	{
		public string DisplayName { get; set; }
		public ulong SystemIndex { get; set; }
		public ulong TimeInNS { get; set; }
		public byte PercentOfTotal { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			DisplayName = reader.ReadLengthPrefixedString();
			SystemIndex = reader.ReadUInt64();
			TimeInNS = reader.ReadUInt64();
			PercentOfTotal = (byte)reader.ReadByte();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(DisplayName);
			writer.WriteUInt64(SystemIndex);
			writer.WriteUInt64(TimeInNS);
			writer.WriteByte(PercentOfTotal);
		}
	}
}
