// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.SharedTypes.v1_26_0
{
	public class CameraSplineProgressKeyFrame
	{
		public float Progress { get; set; }
		public float Time { get; set; }
		public Optional<Protocol.EasingType> Easing { get; set; } = new Optional<Protocol.EasingType>();

		public void Read(MemoryStreamReader reader)
		{
			Progress = reader.ReadSingle();
			Time = reader.ReadSingle();
			if (reader.ReadByte() != 0)
			{
				Easing = new Optional<Protocol.EasingType>(EnumCodec.FromString<Protocol.EasingType>(reader.ReadLengthPrefixedString()));
			}
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteSingle(Progress);
			writer.WriteSingle(Time);
			if (Easing != null && Easing.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteLengthPrefixedString(EnumCodec.ToString(Easing.Value));
			}
			else
			{
				writer.WriteByte(0);
			}
		}
	}
}
