// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.SharedTypes.v1_21_120
{
	public class CameraAimAssistPresetDefinition
	{
		public string Identifier { get; set; }
		public CameraAimAssistPresetExclusionDefinition ExclusionSettings { get; set; }
		public List<string> LiquidTargetingList { get; set; } = new List<string>();
		public Dictionary<string, string> ItemSettings { get; set; } = new Dictionary<string, string>();
		public Optional<string> DefaultItemSettings { get; set; } = new Optional<string>();
		public Optional<string> HandSettings { get; set; } = new Optional<string>();

		public void Read(MemoryStreamReader reader)
		{
			Identifier = reader.ReadLengthPrefixedString();
			ExclusionSettings = new CameraAimAssistPresetExclusionDefinition();
			ExclusionSettings.Read(reader);
			LiquidTargetingList = reader.ReadSlice(() => reader.ReadLengthPrefixedString());
			var _ItemSettingsCount = VarInt.ReadUInt32(reader); 
			ItemSettings.Clear();
			for (int i = 0; i < _ItemSettingsCount; i++)
			{
				var _ItemSettingsKey = reader.ReadLengthPrefixedString();
				var _ItemSettingsValue = reader.ReadLengthPrefixedString();
				ItemSettings[_ItemSettingsKey] = _ItemSettingsValue;
			}
			if (reader.ReadByte() != 0)
			{
				DefaultItemSettings = new Optional<string>(reader.ReadLengthPrefixedString());
			}
			if (reader.ReadByte() != 0)
			{
				HandSettings = new Optional<string>(reader.ReadLengthPrefixedString());
			}
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(Identifier);
			ExclusionSettings.Write(writer);
			writer.WriteSlice(LiquidTargetingList, v => writer.WriteLengthPrefixedString(v));
			writer.WriteVarUInt32((uint)ItemSettings.Count); 
			foreach (var _ItemSettingsPair in ItemSettings)
			{
				writer.WriteLengthPrefixedString(_ItemSettingsPair.Key);
				writer.WriteLengthPrefixedString(_ItemSettingsPair.Value);
			}
			if (DefaultItemSettings != null && DefaultItemSettings.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteLengthPrefixedString(DefaultItemSettings.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (HandSettings != null && HandSettings.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteLengthPrefixedString(HandSettings.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
		}
	}
}
