// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.SharedTypes.v1_21_90
{
	public class CameraPreset
	{
		public string Name { get; set; }
		public string InheritFrom { get; set; }
		public Optional<float> PosX { get; set; } = new Optional<float>();
		public Optional<float> PosY { get; set; } = new Optional<float>();
		public Optional<float> PosZ { get; set; } = new Optional<float>();
		public Optional<float> RotX { get; set; } = new Optional<float>();
		public Optional<float> RotY { get; set; } = new Optional<float>();
		public Optional<float> RotationSpeed { get; set; } = new Optional<float>();
		public Optional<bool> SnapToTarget { get; set; } = new Optional<bool>();
		public Optional<Vec2> HorizontalRotationLimit { get; set; } = new Optional<Vec2>();
		public Optional<Vec2> VerticalRotationLimit { get; set; } = new Optional<Vec2>();
		public Optional<bool> ContinueTargeting { get; set; } = new Optional<bool>();
		public Optional<float> BlockListeningRadius { get; set; } = new Optional<float>();
		public Optional<Vec2> ViewOffset { get; set; } = new Optional<Vec2>();
		public Optional<Vec3> EntityOffset { get; set; } = new Optional<Vec3>();
		public Optional<float> Radius { get; set; } = new Optional<float>();
		public Optional<float> YawLimitMin { get; set; } = new Optional<float>();
		public Optional<float> YawLimitMax { get; set; } = new Optional<float>();
		public Optional<Protocol.SharedTypes.v1_21_90.CameraPreset.AudioListener> Listener { get; set; } = new Optional<Protocol.SharedTypes.v1_21_90.CameraPreset.AudioListener>();
		public Optional<bool> PlayerEffects { get; set; } = new Optional<bool>();
		public Optional<SharedTypes.v1_21_50.CameraAimAssistCommandPresetDefinition> AimAssist { get; set; } = new Optional<SharedTypes.v1_21_50.CameraAimAssistCommandPresetDefinition>();
		public Optional<Protocol.ControlScheme.Scheme> ControlScheme { get; set; } = new Optional<Protocol.ControlScheme.Scheme>();

		public void Read(MemoryStreamReader reader)
		{
			Name = reader.ReadLengthPrefixedString();
			InheritFrom = reader.ReadLengthPrefixedString();
			if (reader.ReadByte() != 0)
			{
				PosX = new Optional<float>(reader.ReadSingle());
			}
			if (reader.ReadByte() != 0)
			{
				PosY = new Optional<float>(reader.ReadSingle());
			}
			if (reader.ReadByte() != 0)
			{
				PosZ = new Optional<float>(reader.ReadSingle());
			}
			if (reader.ReadByte() != 0)
			{
				RotX = new Optional<float>(reader.ReadSingle());
			}
			if (reader.ReadByte() != 0)
			{
				RotY = new Optional<float>(reader.ReadSingle());
			}
			if (reader.ReadByte() != 0)
			{
				RotationSpeed = new Optional<float>(reader.ReadSingle());
			}
			if (reader.ReadByte() != 0)
			{
				SnapToTarget = new Optional<bool>(reader.ReadByte() != 0);
			}
			if (reader.ReadByte() != 0)
			{
				var _HorizontalRotationLimitValue = new Vec2();
				_HorizontalRotationLimitValue.Read(reader);
				HorizontalRotationLimit = new Optional<Vec2>(_HorizontalRotationLimitValue);
			}
			if (reader.ReadByte() != 0)
			{
				var _VerticalRotationLimitValue = new Vec2();
				_VerticalRotationLimitValue.Read(reader);
				VerticalRotationLimit = new Optional<Vec2>(_VerticalRotationLimitValue);
			}
			if (reader.ReadByte() != 0)
			{
				ContinueTargeting = new Optional<bool>(reader.ReadByte() != 0);
			}
			if (reader.ReadByte() != 0)
			{
				BlockListeningRadius = new Optional<float>(reader.ReadSingle());
			}
			if (reader.ReadByte() != 0)
			{
				var _ViewOffsetValue = new Vec2();
				_ViewOffsetValue.Read(reader);
				ViewOffset = new Optional<Vec2>(_ViewOffsetValue);
			}
			if (reader.ReadByte() != 0)
			{
				var _EntityOffsetValue = new Vec3();
				_EntityOffsetValue.Read(reader);
				EntityOffset = new Optional<Vec3>(_EntityOffsetValue);
			}
			if (reader.ReadByte() != 0)
			{
				Radius = new Optional<float>(reader.ReadSingle());
			}
			if (reader.ReadByte() != 0)
			{
				YawLimitMin = new Optional<float>(reader.ReadSingle());
			}
			if (reader.ReadByte() != 0)
			{
				YawLimitMax = new Optional<float>(reader.ReadSingle());
			}
			if (reader.ReadByte() != 0)
			{
				Listener = new Optional<Protocol.SharedTypes.v1_21_90.CameraPreset.AudioListener>((Protocol.SharedTypes.v1_21_90.CameraPreset.AudioListener)reader.ReadByte());
			}
			if (reader.ReadByte() != 0)
			{
				PlayerEffects = new Optional<bool>(reader.ReadByte() != 0);
			}
			if (reader.ReadByte() != 0)
			{
				var _AimAssistValue = new SharedTypes.v1_21_50.CameraAimAssistCommandPresetDefinition();
				_AimAssistValue.Read(reader);
				AimAssist = new Optional<SharedTypes.v1_21_50.CameraAimAssistCommandPresetDefinition>(_AimAssistValue);
			}
			if (reader.ReadByte() != 0)
			{
				ControlScheme = new Optional<Protocol.ControlScheme.Scheme>((Protocol.ControlScheme.Scheme)reader.ReadByte());
			}
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(Name);
			writer.WriteLengthPrefixedString(InheritFrom);
			if (PosX != null && PosX.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteSingle(PosX.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (PosY != null && PosY.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteSingle(PosY.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (PosZ != null && PosZ.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteSingle(PosZ.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (RotX != null && RotX.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteSingle(RotX.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (RotY != null && RotY.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteSingle(RotY.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (RotationSpeed != null && RotationSpeed.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteSingle(RotationSpeed.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (SnapToTarget != null && SnapToTarget.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteByte(SnapToTarget.Value ? (byte)1 : (byte)0);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (HorizontalRotationLimit != null && HorizontalRotationLimit.HasValue)
			{
				writer.WriteByte(1);
				HorizontalRotationLimit.Value.Write(writer);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (VerticalRotationLimit != null && VerticalRotationLimit.HasValue)
			{
				writer.WriteByte(1);
				VerticalRotationLimit.Value.Write(writer);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (ContinueTargeting != null && ContinueTargeting.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteByte(ContinueTargeting.Value ? (byte)1 : (byte)0);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (BlockListeningRadius != null && BlockListeningRadius.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteSingle(BlockListeningRadius.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (ViewOffset != null && ViewOffset.HasValue)
			{
				writer.WriteByte(1);
				ViewOffset.Value.Write(writer);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (EntityOffset != null && EntityOffset.HasValue)
			{
				writer.WriteByte(1);
				EntityOffset.Value.Write(writer);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (Radius != null && Radius.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteSingle(Radius.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (YawLimitMin != null && YawLimitMin.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteSingle(YawLimitMin.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (YawLimitMax != null && YawLimitMax.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteSingle(YawLimitMax.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (Listener != null && Listener.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteByte((byte)Listener.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (PlayerEffects != null && PlayerEffects.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteByte(PlayerEffects.Value ? (byte)1 : (byte)0);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (AimAssist != null && AimAssist.HasValue)
			{
				writer.WriteByte(1);
				AimAssist.Value.Write(writer);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (ControlScheme != null && ControlScheme.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteByte((byte)ControlScheme.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
		}
	}
}
