// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.SharedTypes.v1_26_0
{
	public class CameraSplineControlPoint
	{
		public Vec3 Position { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			Position = new Vec3();
			Position.Read(reader);
		}

		public void Write(MemoryStreamWriter writer)
		{
			Position.Write(writer);
		}
	}
}
