// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.SharedTypes.v1_21_50
{
	public class CameraAimAssistCategoryDefinition
	{
		public string Name { get; set; }
		public CameraAimAssistCategoryPriorities Priorities { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			Name = reader.ReadLengthPrefixedString();
			Priorities = new CameraAimAssistCategoryPriorities();
			Priorities.Read(reader);
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(Name);
			Priorities.Write(writer);
		}
	}
}
