// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.SharedTypes.v1_21_50
{
	public class CameraAimAssistCategoryPriorities
	{
		public Dictionary<string, int> Entities { get; set; } = new Dictionary<string, int>();
		public Dictionary<string, int> Blocks { get; set; } = new Dictionary<string, int>();
		public Dictionary<string, int> BlockTags { get; set; } = new Dictionary<string, int>();
		public Dictionary<string, int> EntityTypeFamilies { get; set; } = new Dictionary<string, int>();
		public Optional<int> EntityDefault { get; set; } = new Optional<int>();
		public Optional<int> BlockDefault { get; set; } = new Optional<int>();

		public void Read(MemoryStreamReader reader)
		{
			var _EntitiesCount = VarInt.ReadUInt32(reader); 
			Entities.Clear();
			for (int i = 0; i < _EntitiesCount; i++)
			{
				var _EntitiesKey = reader.ReadLengthPrefixedString();
				var _EntitiesValue = reader.ReadInt32();
				Entities[_EntitiesKey] = _EntitiesValue;
			}
			var _BlocksCount = VarInt.ReadUInt32(reader); 
			Blocks.Clear();
			for (int i = 0; i < _BlocksCount; i++)
			{
				var _BlocksKey = reader.ReadLengthPrefixedString();
				var _BlocksValue = reader.ReadInt32();
				Blocks[_BlocksKey] = _BlocksValue;
			}
			var _BlockTagsCount = VarInt.ReadUInt32(reader); 
			BlockTags.Clear();
			for (int i = 0; i < _BlockTagsCount; i++)
			{
				var _BlockTagsKey = reader.ReadLengthPrefixedString();
				var _BlockTagsValue = reader.ReadInt32();
				BlockTags[_BlockTagsKey] = _BlockTagsValue;
			}
			var _EntityTypeFamiliesCount = VarInt.ReadUInt32(reader); 
			EntityTypeFamilies.Clear();
			for (int i = 0; i < _EntityTypeFamiliesCount; i++)
			{
				var _EntityTypeFamiliesKey = reader.ReadLengthPrefixedString();
				var _EntityTypeFamiliesValue = reader.ReadInt32();
				EntityTypeFamilies[_EntityTypeFamiliesKey] = _EntityTypeFamiliesValue;
			}
			if (reader.ReadByte() != 0)
			{
				EntityDefault = new Optional<int>(reader.ReadInt32());
			}
			if (reader.ReadByte() != 0)
			{
				BlockDefault = new Optional<int>(reader.ReadInt32());
			}
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteVarUInt32((uint)Entities.Count); 
			foreach (var _EntitiesPair in Entities)
			{
				writer.WriteLengthPrefixedString(_EntitiesPair.Key);
				writer.WriteInt32(_EntitiesPair.Value);
			}
			writer.WriteVarUInt32((uint)Blocks.Count); 
			foreach (var _BlocksPair in Blocks)
			{
				writer.WriteLengthPrefixedString(_BlocksPair.Key);
				writer.WriteInt32(_BlocksPair.Value);
			}
			writer.WriteVarUInt32((uint)BlockTags.Count); 
			foreach (var _BlockTagsPair in BlockTags)
			{
				writer.WriteLengthPrefixedString(_BlockTagsPair.Key);
				writer.WriteInt32(_BlockTagsPair.Value);
			}
			writer.WriteVarUInt32((uint)EntityTypeFamilies.Count); 
			foreach (var _EntityTypeFamiliesPair in EntityTypeFamilies)
			{
				writer.WriteLengthPrefixedString(_EntityTypeFamiliesPair.Key);
				writer.WriteInt32(_EntityTypeFamiliesPair.Value);
			}
			if (EntityDefault != null && EntityDefault.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteInt32(EntityDefault.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (BlockDefault != null && BlockDefault.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteInt32(BlockDefault.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
		}
	}
}
