// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.SharedTypes.v1_26_0
{
	public class CameraSplineDefinition
	{
		public string Name { get; set; }
		public float TotalTime { get; set; }
		public string SplineType { get; set; }
		public List<CameraSplineControlPoint> ControlPoints { get; set; } = new List<CameraSplineControlPoint>();
		public List<CameraSplineProgressKeyFrame> ProgressKeyFrames { get; set; } = new List<CameraSplineProgressKeyFrame>();
		public List<CameraSplineRotationKeyFrame> RotationKeyFrames { get; set; } = new List<CameraSplineRotationKeyFrame>();

		public void Read(MemoryStreamReader reader)
		{
			Name = reader.ReadLengthPrefixedString();
			TotalTime = reader.ReadSingle();
			SplineType = reader.ReadLengthPrefixedString();
			ControlPoints = reader.ReadSlice(() => { var _Item = new CameraSplineControlPoint(); _Item.Read(reader); return _Item; });
			ProgressKeyFrames = reader.ReadSlice(() => { var _Item = new CameraSplineProgressKeyFrame(); _Item.Read(reader); return _Item; });
			RotationKeyFrames = reader.ReadSlice(() => { var _Item = new CameraSplineRotationKeyFrame(); _Item.Read(reader); return _Item; });
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(Name);
			writer.WriteSingle(TotalTime);
			writer.WriteLengthPrefixedString(SplineType);
			writer.WriteSlice(ControlPoints, v => v.Write(writer));
			writer.WriteSlice(ProgressKeyFrames, v => v.Write(writer));
			writer.WriteSlice(RotationKeyFrames, v => v.Write(writer));
		}
	}
}
