// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.SharedTypes.v1_21_50
{
	public class CameraAimAssistCommandPresetDefinition
	{
		public Optional<string> PresetId { get; set; } = new Optional<string>();
		public Optional<Protocol.CameraAimAssist.TargetMode> TargetMode { get; set; } = new Optional<Protocol.CameraAimAssist.TargetMode>();
		public Optional<Vec2> ViewAngle { get; set; } = new Optional<Vec2>();
		public Optional<float> Distance { get; set; } = new Optional<float>();

		public void Read(MemoryStreamReader reader)
		{
			if (reader.ReadByte() != 0)
			{
				PresetId = new Optional<string>(reader.ReadLengthPrefixedString());
			}
			if (reader.ReadByte() != 0)
			{
				TargetMode = new Optional<Protocol.CameraAimAssist.TargetMode>((Protocol.CameraAimAssist.TargetMode)reader.ReadByte());
			}
			if (reader.ReadByte() != 0)
			{
				var _ViewAngleValue = new Vec2();
				_ViewAngleValue.Read(reader);
				ViewAngle = new Optional<Vec2>(_ViewAngleValue);
			}
			if (reader.ReadByte() != 0)
			{
				Distance = new Optional<float>(reader.ReadSingle());
			}
		}

		public void Write(MemoryStreamWriter writer)
		{
			if (PresetId != null && PresetId.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteLengthPrefixedString(PresetId.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (TargetMode != null && TargetMode.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteByte((byte)TargetMode.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (ViewAngle != null && ViewAngle.HasValue)
			{
				writer.WriteByte(1);
				ViewAngle.Value.Write(writer);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (Distance != null && Distance.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteSingle(Distance.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
		}
	}
}
