// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class ActorPickRequestPacket : IPacket
	{
		public int PacketId => 35;

		public long ActorID { get; set; }
		public byte MaxSlots { get; set; }
		public bool WithData { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			ActorID = reader.ReadInt64();
			MaxSlots = (byte)reader.ReadByte();
			WithData = reader.ReadByte() != 0;
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteInt64(ActorID);
			writer.WriteByte(MaxSlots);
			writer.WriteByte(WithData ? (byte)1 : (byte)0);
		}
	}
}
