// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// For automation
	/// </summary>
	public class AddBehaviorTreePacket : IPacket
	{
		public int PacketId => 89;

		public string BehaviorTreeStructureJSON { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			BehaviorTreeStructureJSON = reader.ReadLengthPrefixedString();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(BehaviorTreeStructureJSON);
		}
	}
}
