// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class AddPaintingPacket : IPacket
	{
		public int PacketId => 22;

		public Protocol.Types.ActorUniqueID TargetActorID { get; set; }
		public Protocol.Types.ActorRuntimeID TargetRuntimeID { get; set; }
		public Protocol.Types.Vec3 Position { get; set; }
		public int Direction { get; set; } 
		public string Motif { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			TargetActorID = new Protocol.Types.ActorUniqueID();
			TargetActorID.Read(reader);
			TargetRuntimeID = new Protocol.Types.ActorRuntimeID();
			TargetRuntimeID.Read(reader);
			Position = new Protocol.Types.Vec3();
			Position.Read(reader);
			Direction = VarInt.ReadInt32(reader); 
			Motif = reader.ReadLengthPrefixedString();
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			TargetActorID.Write(writer);
			TargetRuntimeID.Write(writer);
			Position.Write(writer);
			writer.WriteVarInt32(Direction); 
			writer.WriteLengthPrefixedString(Motif);
		}
	}
}
