// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// A new player joins the game; the server sends this packet to the other players.
	/// </summary>
	public class AddPlayerPacket : IPacket
	{
		public int PacketId => 12;

		public Protocol.Types.mce.UUID UUID { get; set; }
		public string PlayerName { get; set; }
		public Protocol.Types.ActorRuntimeID TargetRuntimeID { get; set; }
		public string PlatformChatId { get; set; }
		public Protocol.Types.Vec3 Position { get; set; }
		public Protocol.Types.Vec3 Velocity { get; set; }
		public Protocol.Types.Vec2 Rotation { get; set; }
		public float YHeadRotation { get; set; }
		public Protocol.Types.NetworkItemStackDescriptor.NetworkItemStackDescriptor CarriedItem { get; set; }
		public Protocol.GameType PlayerGameType { get; set; } 
		public Protocol.Types.SynchedActorData.CopyableDataList EntityData { get; set; }
		public Protocol.Types.PropertySyncData SynchedProperties { get; set; }
		public Protocol.Types.SerializedAbilitiesData AbilitiesData { get; set; }
		public List<Protocol.Types.ActorLink> ActorLinks { get; set; } = new List<Protocol.Types.ActorLink>();
		public string DeviceId { get; set; }
		public Protocol.BuildPlatform BuildPlatform { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			UUID = new Protocol.Types.mce.UUID();
			UUID.Read(reader);
			PlayerName = reader.ReadLengthPrefixedString();
			TargetRuntimeID = new Protocol.Types.ActorRuntimeID();
			TargetRuntimeID.Read(reader);
			PlatformChatId = reader.ReadLengthPrefixedString();
			Position = new Protocol.Types.Vec3();
			Position.Read(reader);
			Velocity = new Protocol.Types.Vec3();
			Velocity.Read(reader);
			Rotation = new Protocol.Types.Vec2();
			Rotation.Read(reader);
			YHeadRotation = reader.ReadSingle();
			CarriedItem = new Protocol.Types.NetworkItemStackDescriptor.NetworkItemStackDescriptor();
			CarriedItem.Read(reader);
			PlayerGameType = (Protocol.GameType)VarInt.ReadInt32(reader); 
			EntityData = new Protocol.Types.SynchedActorData.CopyableDataList();
			EntityData.Read(reader);
			SynchedProperties = new Protocol.Types.PropertySyncData();
			SynchedProperties.Read(reader);
			AbilitiesData = new Protocol.Types.SerializedAbilitiesData();
			AbilitiesData.Read(reader);
			ActorLinks = reader.ReadSlice(() => { var _Item = new Protocol.Types.ActorLink(); _Item.Read(reader); return _Item; });
			DeviceId = reader.ReadLengthPrefixedString();
			BuildPlatform = (Protocol.BuildPlatform)reader.ReadInt32();
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			UUID.Write(writer);
			writer.WriteLengthPrefixedString(PlayerName);
			TargetRuntimeID.Write(writer);
			writer.WriteLengthPrefixedString(PlatformChatId);
			Position.Write(writer);
			Velocity.Write(writer);
			Rotation.Write(writer);
			writer.WriteSingle(YHeadRotation);
			CarriedItem.Write(writer);
			writer.WriteVarInt32((int)PlayerGameType); 
			EntityData.Write(writer);
			SynchedProperties.Write(writer);
			AbilitiesData.Write(writer);
			writer.WriteSlice(ActorLinks, v => v.Write(writer));
			writer.WriteLengthPrefixedString(DeviceId);
			writer.WriteInt32((int)BuildPlatform);
		}
	}
}
