// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class AgentAnimationPacket : IPacket
	{
		public int PacketId => 304;

		public Protocol.AgentAnimation AgentAnimation { get; set; }
		public Protocol.Types.ActorRuntimeID RuntimeId { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			AgentAnimation = (Protocol.AgentAnimation)reader.ReadByte();
			RuntimeId = new Protocol.Types.ActorRuntimeID();
			RuntimeId.Read(reader);
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteByte((byte)AgentAnimation);
			RuntimeId.Write(writer);
		}
	}
}
