// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Combination of server bound and client bound packets to trigger animations.
	/// </summary>
	public class AnimatePacket : IPacket
	{
		public override int PacketId => 44;

		public Protocol.AnimatePacketPayload.Action Action { get; set; }
		public Protocol.Types.ActorRuntimeID TargetActorRuntimeID { get; set; }
		public float Data { get; set; }
		public Optional<Protocol.ActorSwingSource> SwingSource { get; set; } = new Optional<Protocol.ActorSwingSource>();

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			Action = (Protocol.AnimatePacketPayload.Action)reader.ReadByte();
			TargetActorRuntimeID = new Protocol.Types.ActorRuntimeID();
			TargetActorRuntimeID.Read(reader);
			Data = reader.ReadSingle();
			if (reader.ReadByte() != 0)
			{
				SwingSource = new Optional<Protocol.ActorSwingSource>(EnumCodec.FromString<Protocol.ActorSwingSource>(reader.ReadLengthPrefixedString()));
			}
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteByte((byte)Action);
			TargetActorRuntimeID.Write(writer);
			writer.WriteSingle(Data);
			if (SwingSource != null && SwingSource.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteLengthPrefixedString(EnumCodec.ToString(SwingSource.Value));
			}
			else
			{
				writer.WriteByte(0);
			}
		}
	}
}

namespace Protocol.AnimatePacketPayload
{
	public enum Action
	{
		NoAction = 0,
		Swing = 1,
		WakeUp = 3,
		CriticalHit = 4,
		MagicCriticalHit = 5,
	}
}
