// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Only used when Item Stack Net Manager is disabled on the server.
	/// 	Sends the position of the anvil that is requesting to be damaged from the client.
	/// </summary>
	public class AnvilDamagePacket : IPacket
	{
		public int PacketId => 141;

		public Protocol.Types.BlockPos BlockPosition { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			BlockPosition = new Protocol.Types.BlockPos();
			BlockPosition.Read(reader);
		}

		public void Write(MemoryStreamWriter writer)
		{
			BlockPosition.Write(writer);
		}
	}
}
