// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Only used though command to connect to server URLs. This is primarily used by EDU for connecting to their companion apps and other external applications through web sockets. Some mods/3rd party packs use it as well.
	/// </summary>
	public class AutomationClientConnectPacket : IPacket
	{
		public override int PacketId => 95;

		public Protocol.Types.WebSocketPacketData WebSocketData { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			WebSocketData = new Protocol.Types.WebSocketPacketData();
			WebSocketData.Read(reader);
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			WebSocketData.Write(writer);
		}
	}
}

namespace Protocol.Types
{
	public class WebSocketPacketData
	{
		public string WebsocketServerURI { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			WebsocketServerURI = reader.ReadLengthPrefixedString();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(WebsocketServerURI);
		}
	}
}
