// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class AvailableCommandsPacket : IPacket
	{
		public int PacketId => 76;

		public List<string> EnumValues { get; set; } = new List<string>();
		public List<string> ChainedSubcommandValues { get; set; } = new List<string>();
		public List<string> PostFixes { get; set; } = new List<string>();
		public List<Protocol.Types.AvailableCommandsPacketPayload.EnumData> EnumData { get; set; } = new List<Protocol.Types.AvailableCommandsPacketPayload.EnumData>();
		public List<Protocol.Types.AvailableCommandsPacketPayload.ChainedSubcommandData> ChainedSubcommandData { get; set; } = new List<Protocol.Types.AvailableCommandsPacketPayload.ChainedSubcommandData>();
		public List<Protocol.Types.AvailableCommandsPacketPayload.CommandData> Commands { get; set; } = new List<Protocol.Types.AvailableCommandsPacketPayload.CommandData>();
		public List<Protocol.Types.AvailableCommandsPacketPayload.SoftEnumData> SoftEnums { get; set; } = new List<Protocol.Types.AvailableCommandsPacketPayload.SoftEnumData>();
		public List<Protocol.Types.AvailableCommandsPacketPayload.ConstrainedValueData> Constraints { get; set; } = new List<Protocol.Types.AvailableCommandsPacketPayload.ConstrainedValueData>();

		public void Read(MemoryStreamReader reader)
		{
			EnumValues = reader.ReadSlice(() => reader.ReadLengthPrefixedString());
			ChainedSubcommandValues = reader.ReadSlice(() => reader.ReadLengthPrefixedString());
			PostFixes = reader.ReadSlice(() => reader.ReadLengthPrefixedString());
			EnumData = reader.ReadSlice(() => { var _Item = new Protocol.Types.AvailableCommandsPacketPayload.EnumData(); _Item.Read(reader); return _Item; });
			ChainedSubcommandData = reader.ReadSlice(() => { var _Item = new Protocol.Types.AvailableCommandsPacketPayload.ChainedSubcommandData(); _Item.Read(reader); return _Item; });
			Commands = reader.ReadSlice(() => { var _Item = new Protocol.Types.AvailableCommandsPacketPayload.CommandData(); _Item.Read(reader); return _Item; });
			SoftEnums = reader.ReadSlice(() => { var _Item = new Protocol.Types.AvailableCommandsPacketPayload.SoftEnumData(); _Item.Read(reader); return _Item; });
			Constraints = reader.ReadSlice(() => { var _Item = new Protocol.Types.AvailableCommandsPacketPayload.ConstrainedValueData(); _Item.Read(reader); return _Item; });
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteSlice(EnumValues, v => writer.WriteLengthPrefixedString(v));
			writer.WriteSlice(ChainedSubcommandValues, v => writer.WriteLengthPrefixedString(v));
			writer.WriteSlice(PostFixes, v => writer.WriteLengthPrefixedString(v));
			writer.WriteSlice(EnumData, v => v.Write(writer));
			writer.WriteSlice(ChainedSubcommandData, v => v.Write(writer));
			writer.WriteSlice(Commands, v => v.Write(writer));
			writer.WriteSlice(SoftEnums, v => v.Write(writer));
			writer.WriteSlice(Constraints, v => v.Write(writer));
		}
	}
}
