// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// - mBiomeData: map of biome string indices to biome definition data.
	/// - mStringList: list of biome name strings.
	/// </summary>
	public class BiomeDefinitionListPacket : IPacket
	{
		public int PacketId => 122;

		public Dictionary<ushort, Protocol.Types.BiomeDefinitionData> MapOfBiomeNamesToData { get; set; } = new Dictionary<ushort, Protocol.Types.BiomeDefinitionData>();
		public Protocol.Types.BiomeStringList StringList { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			var _MapOfBiomeNamesToDataCount = VarInt.ReadUInt32(reader); 
			MapOfBiomeNamesToData.Clear();
			for (int i = 0; i < _MapOfBiomeNamesToDataCount; i++)
			{
				var _MapOfBiomeNamesToDataKey = reader.ReadUInt16();
				var _MapOfBiomeNamesToDataValue = new Protocol.Types.BiomeDefinitionData();
				_MapOfBiomeNamesToDataValue.Read(reader);
				MapOfBiomeNamesToData[_MapOfBiomeNamesToDataKey] = _MapOfBiomeNamesToDataValue;
			}
			StringList = new Protocol.Types.BiomeStringList();
			StringList.Read(reader);
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteVarUInt32((uint)MapOfBiomeNamesToData.Count); 
			foreach (var _MapOfBiomeNamesToDataPair in MapOfBiomeNamesToData)
			{
				writer.WriteUInt16(_MapOfBiomeNamesToDataPair.Key);
				_MapOfBiomeNamesToDataPair.Value.Write(writer);
			}
			StringList.Write(writer);
		}
	}
}
