// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class BlockActorDataPacket : IPacket
	{
		public int PacketId => 56;

		public Protocol.Types.BlockPos BlockPosition { get; set; }
		public Protocol.Types.CompoundTag ActorDataTags { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			BlockPosition = new Protocol.Types.BlockPos();
			BlockPosition.Read(reader);
			ActorDataTags = new Protocol.Types.CompoundTag();
			ActorDataTags.Read(reader);
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			BlockPosition.Write(writer);
			ActorDataTags.Write(writer);
		}
	}
}
