// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class BlockPickRequestPacket : IPacket
	{
		public int PacketId => 34;

		public Protocol.Types.BlockPos Position { get; set; }
		public bool WithData { get; set; }
		public byte MaxSlots { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			Position = new Protocol.Types.BlockPos();
			Position.Read(reader);
			WithData = reader.ReadByte() != 0;
			MaxSlots = (byte)reader.ReadByte();
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			Position.Write(writer);
			writer.WriteByte(WithData ? (byte)1 : (byte)0);
			writer.WriteByte(MaxSlots);
		}
	}
}
