// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Sent by the server to clients for initializing custom spline data that can be played later through the camera command.
	/// </summary>
	public class CameraSplinePacket : IPacket
	{
		public override int PacketId => 338;

		public List<Protocol.Types.SharedTypes.v1_26_0.CameraSplineDefinition> CameraDataSplines { get; set; } = new List<Protocol.Types.SharedTypes.v1_26_0.CameraSplineDefinition>();

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			CameraDataSplines = reader.ReadSlice(() => { var _Item = new Protocol.Types.SharedTypes.v1_26_0.CameraSplineDefinition(); _Item.Read(reader); return _Item; });
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteSlice(CameraDataSplines, v => v.Write(writer));
		}
	}
}
