// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class CameraPacket : IPacket
	{
		public int PacketId => 73;

		public Protocol.Types.ActorUniqueID CameraID { get; set; }
		public Protocol.Types.ActorUniqueID TargetPlayerID { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			CameraID = new Protocol.Types.ActorUniqueID();
			CameraID.Read(reader);
			TargetPlayerID = new Protocol.Types.ActorUniqueID();
			TargetPlayerID.Read(reader);
		}

		public void Write(MemoryStreamWriter writer)
		{
			CameraID.Write(writer);
			TargetPlayerID.Write(writer);
		}
	}
}
