// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Sent by the server to clients for updating the actor priority for client aim-assist systems.
	/// </summary>
	public class CameraAimAssistActorPriorityPacket : IPacket
	{
		public int PacketId => 339;

		public List<Protocol.Types.CameraAimAssistActorPriority.PriorityData> CameraAimAssistActorPriorityList { get; set; } = new List<Protocol.Types.CameraAimAssistActorPriority.PriorityData>();

		public void Read(MemoryStreamReader reader)
		{
			CameraAimAssistActorPriorityList = reader.ReadSlice(() => { var _Item = new Protocol.Types.CameraAimAssistActorPriority.PriorityData(); _Item.Read(reader); return _Item; });
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteSlice(CameraAimAssistActorPriorityList, v => v.Write(writer));
		}
	}
}
