// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Sent by the server to clients for initializing and updating the client aim-assist registry.
	/// 	AddToExisting operations are sent by the server when new presets/categories are added to the registry through creator facing APIs.
	/// </summary>
	public class CameraAimAssistPresetsPacket : IPacket
	{
		public int PacketId => 320;

		public List<Protocol.Types.SharedTypes.v1_21_50.CameraAimAssistCategoryDefinition> CameraAimAssistPresets { get; set; } = new List<Protocol.Types.SharedTypes.v1_21_50.CameraAimAssistCategoryDefinition>();
		public List<Protocol.Types.SharedTypes.v1_21_120.CameraAimAssistPresetDefinition> CameraAimAssistCategories { get; set; } = new List<Protocol.Types.SharedTypes.v1_21_120.CameraAimAssistPresetDefinition>();
		public Protocol.CameraAimAssistPresetsPacketOperation Operation { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			CameraAimAssistPresets = reader.ReadSlice(() => { var _Item = new Protocol.Types.SharedTypes.v1_21_50.CameraAimAssistCategoryDefinition(); _Item.Read(reader); return _Item; });
			CameraAimAssistCategories = reader.ReadSlice(() => { var _Item = new Protocol.Types.SharedTypes.v1_21_120.CameraAimAssistPresetDefinition(); _Item.Read(reader); return _Item; });
			Operation = (Protocol.CameraAimAssistPresetsPacketOperation)reader.ReadByte();
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteSlice(CameraAimAssistPresets, v => v.Write(writer));
			writer.WriteSlice(CameraAimAssistCategories, v => v.Write(writer));
			writer.WriteByte((byte)Operation);
		}
	}
}
