// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class CameraAimAssistPacket : IPacket
	{
		public override int PacketId => 316;

		public string PresetId { get; set; }
		public Protocol.Types.Vec2 ViewAngle { get; set; }
		public float Distance { get; set; }
		public Protocol.CameraAimAssistPacketPayload.TargetMode TargetMode { get; set; }
		public Protocol.CameraAimAssistPacketPayload.Action Action { get; set; }
		public bool ShowDebugRender { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			PresetId = reader.ReadLengthPrefixedString();
			ViewAngle = new Protocol.Types.Vec2();
			ViewAngle.Read(reader);
			Distance = reader.ReadSingle();
			TargetMode = (Protocol.CameraAimAssistPacketPayload.TargetMode)reader.ReadByte();
			Action = (Protocol.CameraAimAssistPacketPayload.Action)reader.ReadByte();
			ShowDebugRender = reader.ReadByte() != 0;
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteLengthPrefixedString(PresetId);
			ViewAngle.Write(writer);
			writer.WriteSingle(Distance);
			writer.WriteByte((byte)TargetMode);
			writer.WriteByte((byte)Action);
			writer.WriteByte(ShowDebugRender ? (byte)1 : (byte)0);
		}
	}
}
