// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class CameraPresetsPacket : IPacket
	{
		public int PacketId => 198;

		public Protocol.Types.CameraPresets CameraPresets { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			CameraPresets = new Protocol.Types.CameraPresets();
			CameraPresets.Read(reader);
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			CameraPresets.Write(writer);
		}
	}
}
