// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class ChangeDimensionPacket : IPacket
	{
		public int PacketId => 61;

		public Protocol.Types.DimensionType DimensionID { get; set; }
		public Protocol.Types.Vec3 Position { get; set; }
		public bool Respawn { get; set; }
		public Optional<uint> LoadingScreenId { get; set; } = new Optional<uint>();

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			DimensionID = new Protocol.Types.DimensionType();
			DimensionID.Read(reader);
			Position = new Protocol.Types.Vec3();
			Position.Read(reader);
			Respawn = reader.ReadByte() != 0;
			if (reader.ReadByte() != 0)
			{
				LoadingScreenId = new Optional<uint>(reader.ReadUInt32());
			}
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			DimensionID.Write(writer);
			Position.Write(writer);
			writer.WriteByte(Respawn ? (byte)1 : (byte)0);
			if (LoadingScreenId != null && LoadingScreenId.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteUInt32(LoadingScreenId.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
		}
	}
}
