// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Only used in Server-Authoritative Movement. Sent periodically if the client has received corrections from the server. Contains information about client-predictions that are relevant to movement.
	/// </summary>
	public class ClientMovementPredictionSyncPacket : IPacket
	{
		public int PacketId => 322;

		public Protocol.Types.ActorDataFlagComponent ActorDataFlag { get; set; }
		public Protocol.Types.ActorDataBoundingBoxComponent ActorBoundingBox { get; set; }
		public float[] MovementAttributes { get; set; } = new float[9];
		public Protocol.Types.ActorUniqueID ActorUniqueID { get; set; }
		public bool ActorFlyingState { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			ActorDataFlag = new Protocol.Types.ActorDataFlagComponent();
			ActorDataFlag.Read(reader);
			ActorBoundingBox = new Protocol.Types.ActorDataBoundingBoxComponent();
			ActorBoundingBox.Read(reader);
			MovementAttributes = reader.ReadSliceOfLen(9, () => reader.ReadSingle());
			ActorUniqueID = new Protocol.Types.ActorUniqueID();
			ActorUniqueID.Read(reader);
			ActorFlyingState = reader.ReadByte() != 0;
		}

		public void Write(MemoryStreamWriter writer)
		{
			ActorDataFlag.Write(writer);
			ActorBoundingBox.Write(writer);
			writer.WriteSliceOfLen(MovementAttributes, 9, v => writer.WriteSingle(v));
			ActorUniqueID.Write(writer);
			writer.WriteByte(ActorFlyingState ? (byte)1 : (byte)0);
		}
	}
}
