// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class ClientboundTextureShiftPacket : IPacket
	{
		public override int PacketId => 336;

		public Protocol.ClientboundTextureShiftPacketPayload.Action ActionID { get; set; }
		public string CollectionName { get; set; }
		public string FromStep { get; set; }
		public string ToStep { get; set; }
		public List<string> AllSteps { get; set; } = new List<string>();
		public ulong CurrentLengthInTicks { get; set; } 
		public ulong TotalLengthInTicks { get; set; } 
		public bool Enabled { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			ActionID = (Protocol.ClientboundTextureShiftPacketPayload.Action)reader.ReadByte();
			CollectionName = reader.ReadLengthPrefixedString();
			FromStep = reader.ReadLengthPrefixedString();
			ToStep = reader.ReadLengthPrefixedString();
			AllSteps = reader.ReadSlice(() => reader.ReadLengthPrefixedString());
			CurrentLengthInTicks = VarInt.ReadUInt64(reader); 
			TotalLengthInTicks = VarInt.ReadUInt64(reader); 
			Enabled = reader.ReadByte() != 0;
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteByte((byte)ActionID);
			writer.WriteLengthPrefixedString(CollectionName);
			writer.WriteLengthPrefixedString(FromStep);
			writer.WriteLengthPrefixedString(ToStep);
			writer.WriteSlice(AllSteps, v => writer.WriteLengthPrefixedString(v));
			writer.WriteVarUInt64(CurrentLengthInTicks); 
			writer.WriteVarUInt64(TotalLengthInTicks); 
			writer.WriteByte(Enabled ? (byte)1 : (byte)0);
		}
	}
}

namespace Protocol.ClientboundTextureShiftPacketPayload
{
	public enum Action
	{
		Invalid = 0,
		Initialize = 1,
		Start = 2,
		SetEnabled = 3,
		Sync = 4,
	}
}
