// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Sent by clients to the server for activating/deactivating aim-assist.
	/// 	Activation uses the CameraPreset Id for server-side lookup and uses its aim_assist field
	/// 	for aim-assist activation settings.
	/// </summary>
	public class ClientCameraAimAssistPacket : IPacket
	{
		public int PacketId => 321;

		public string CameraPresetId { get; set; }
		public Protocol.ClientCameraAimAssistPacketAction Action { get; set; }
		public bool AllowAimAssist { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			CameraPresetId = reader.ReadLengthPrefixedString();
			Action = (Protocol.ClientCameraAimAssistPacketAction)reader.ReadByte();
			AllowAimAssist = reader.ReadByte() != 0;
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteLengthPrefixedString(CameraPresetId);
			writer.WriteByte((byte)Action);
			writer.WriteByte(AllowAimAssist ? (byte)1 : (byte)0);
		}
	}
}
