// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class ClientboundControlSchemeSetPacket : IPacket
	{
		public int PacketId => 327;

		public Protocol.ControlScheme.Scheme ControlScheme { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			ControlScheme = (Protocol.ControlScheme.Scheme)reader.ReadByte();
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteByte((byte)ControlScheme);
		}
	}
}
