// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class CodeBuilderSourcePacket : IPacket
	{
		public override int PacketId => 178;

		public Protocol.CodeBuilderStorageQueryOptions.Operation Operation { get; set; }
		public Protocol.CodeBuilderStorageQueryOptions.Category Category { get; set; }
		public Protocol.CodeBuilderExecutionState.CodeStatus CodeStatus { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			Operation = (Protocol.CodeBuilderStorageQueryOptions.Operation)reader.ReadByte();
			Category = (Protocol.CodeBuilderStorageQueryOptions.Category)reader.ReadByte();
			CodeStatus = (Protocol.CodeBuilderExecutionState.CodeStatus)reader.ReadByte();
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteByte((byte)Operation);
			writer.WriteByte((byte)Category);
			writer.WriteByte((byte)CodeStatus);
		}
	}
}

namespace Protocol.CodeBuilderExecutionState
{
	public enum CodeStatus
	{
		None = 0,
		NotStarted = 1,
		InProgress = 2,
		Paused = 3,
		Error = 4,
		Succeeded = 5,
	}
}

namespace Protocol.CodeBuilderStorageQueryOptions
{
	public enum Category
	{
		None = 0,
		CodeStatus = 1,
		Instantiation = 2,
	}
}

namespace Protocol.CodeBuilderStorageQueryOptions
{
	public enum Operation
	{
		None = 0,
		Get = 1,
		Set = 2,
		Reset = 3,
	}
}
