// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// This is EDU exclusively.It is sent once from _sendLevelData() in the start of a game from the server,
	/// 	and once per CodeBuilderCommand
	/// </summary>
	public class CodeBuilderPacket : IPacket
	{
		public int PacketId => 150;

		public string URL { get; set; }
		public bool ShouldOpenCodeBuilder { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			URL = reader.ReadLengthPrefixedString();
			ShouldOpenCodeBuilder = reader.ReadByte() != 0;
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(URL);
			writer.WriteByte(ShouldOpenCodeBuilder ? (byte)1 : (byte)0);
		}
	}
}
