// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class CommandOutputPacket : IPacket
	{
		public override int PacketId => 79;

		public Protocol.Types.CommandOriginData OriginData { get; set; }
		public Protocol.Types.CommandOutput Output { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			OriginData = new Protocol.Types.CommandOriginData();
			OriginData.Read(reader);
			Output = new Protocol.Types.CommandOutput();
			Output.Read(reader);
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			OriginData.Write(writer);
			Output.Write(writer);
		}
	}
}
