// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Sent when you close the command block screen on the client.
	/// </summary>
	public class CommandBlockUpdatePacket : IPacket
	{
		public int PacketId => 78;

		public OneOf<Protocol.Types.CommandBlockUpdatePacketPayload.EntityCommandTarget, Protocol.Types.CommandBlockUpdatePacketPayload.BlockCommandData> Target { get; set; }
		public string Command { get; set; }
		public string LastOutput { get; set; }
		public string Name { get; set; }
		public string FilteredName { get; set; }
		public bool TrackOutput { get; set; }
		public int TickDelay { get; set; }
		public bool ExecuteOnFirstTick { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			var _TargetDisc = VarInt.ReadUInt32(reader); 
			switch (_TargetDisc)
			{
				case 0:
				{
				var _TargetCase0 = new Protocol.Types.CommandBlockUpdatePacketPayload.EntityCommandTarget();
				_TargetCase0.Read(reader);
				Target = OneOf<Protocol.Types.CommandBlockUpdatePacketPayload.EntityCommandTarget, Protocol.Types.CommandBlockUpdatePacketPayload.BlockCommandData>.FromT0(_TargetCase0);
				break;
				}
				case 1:
				{
				var _TargetCase1 = new Protocol.Types.CommandBlockUpdatePacketPayload.BlockCommandData();
				_TargetCase1.Read(reader);
				Target = OneOf<Protocol.Types.CommandBlockUpdatePacketPayload.EntityCommandTarget, Protocol.Types.CommandBlockUpdatePacketPayload.BlockCommandData>.FromT1(_TargetCase1);
				break;
				}
				default:
					throw new InvalidDataException("Unknown Target discriminant: " + _TargetDisc);
			}
			Command = reader.ReadLengthPrefixedString();
			LastOutput = reader.ReadLengthPrefixedString();
			Name = reader.ReadLengthPrefixedString();
			FilteredName = reader.ReadLengthPrefixedString();
			TrackOutput = reader.ReadByte() != 0;
			TickDelay = reader.ReadInt32();
			ExecuteOnFirstTick = reader.ReadByte() != 0;
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			switch (Target.Index)
			{
				case 0:
				{
				writer.WriteVarUInt32((uint)Target.Index); 
				Target.AsT0.Write(writer);
				break;
				}
				case 1:
				{
				writer.WriteVarUInt32((uint)Target.Index); 
				Target.AsT1.Write(writer);
				break;
				}
				default:
					throw new InvalidDataException("Invalid Target OneOf index: " + Target.Index);
			}
			writer.WriteLengthPrefixedString(Command);
			writer.WriteLengthPrefixedString(LastOutput);
			writer.WriteLengthPrefixedString(Name);
			writer.WriteLengthPrefixedString(FilteredName);
			writer.WriteByte(TrackOutput ? (byte)1 : (byte)0);
			writer.WriteInt32(TickDelay);
			writer.WriteByte(ExecuteOnFirstTick ? (byte)1 : (byte)0);
		}
	}
}
