// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class ContainerOpenPacket : IPacket
	{
		public int PacketId => 46;

		public byte ContainerId { get; set; }
		public byte ContainerType { get; set; }
		public Protocol.Types.BlockPos Position { get; set; }
		public Protocol.Types.ActorUniqueID TargetActorID { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			ContainerId = (byte)reader.ReadByte();
			ContainerType = (byte)reader.ReadByte();
			Position = new Protocol.Types.BlockPos();
			Position.Read(reader);
			TargetActorID = new Protocol.Types.ActorUniqueID();
			TargetActorID.Read(reader);
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteByte(ContainerId);
			writer.WriteByte(ContainerType);
			Position.Write(writer);
			TargetActorID.Write(writer);
		}
	}
}
