// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class ContainerClosePacket : IPacket
	{
		public int PacketId => 47;

		public byte ContainerId { get; set; }
		public byte ContainerType { get; set; }
		public bool ServerInitiatedClose { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			ContainerId = (byte)reader.ReadByte();
			ContainerType = (byte)reader.ReadByte();
			ServerInitiatedClose = reader.ReadByte() != 0;
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteByte(ContainerId);
			writer.WriteByte(ContainerType);
			writer.WriteByte(ServerInitiatedClose ? (byte)1 : (byte)0);
		}
	}
}
