// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Whenever the serverside ContainerRegistry does a clean, identifiers for the removed containers are gathered in a ContainerRegistryCleanUp
	/// 	packet and sent to the client so that the clientside container registry can remove those same containers.
	/// </summary>
	public class ContainerRegistryCleanupPacket : IPacket
	{
		public int PacketId => 317;

		public List<Protocol.Types.FullContainerName> RemovedContainers { get; set; } = new List<Protocol.Types.FullContainerName>();

		public void Read(MemoryStreamReader reader)
		{
			RemovedContainers = reader.ReadSlice(() => { var _Item = new Protocol.Types.FullContainerName(); _Item.Read(reader); return _Item; });
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteSlice(RemovedContainers, v => v.Write(writer));
		}
	}
}
