// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Used only in server authoritative movement mode, see ServerAuthMovementMode documentation.<br>
	/// 	Since it is sent to the specified client the target player is implied to be the receiver.<br>
	/// 	It is an optional part of the server authoritative protocol. A server could choose to never send this or do all corrections
	/// 	through MovePlayerPacket, although doing so would likely provide less smooth results.
	/// </summary>
	public class CorrectPlayerMovePredictionPacket : IPacket
	{
		public override int PacketId => 161;

		public Protocol.RewindType PredictionType { get; set; }
		public Protocol.Types.Vec3 Pos { get; set; }
		public Protocol.Types.Vec3 PosDelta { get; set; }
		public Protocol.Types.Vec2 Rotation { get; set; }
		public Optional<float> VehicleAngularVelocity { get; set; } = new Optional<float>();
		public bool OnGround { get; set; }
		public Protocol.Types.PlayerInputTick Tick { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			PredictionType = (Protocol.RewindType)reader.ReadByte();
			Pos = new Protocol.Types.Vec3();
			Pos.Read(reader);
			PosDelta = new Protocol.Types.Vec3();
			PosDelta.Read(reader);
			Rotation = new Protocol.Types.Vec2();
			Rotation.Read(reader);
			if (reader.ReadByte() != 0)
			{
				VehicleAngularVelocity = new Optional<float>(reader.ReadSingle());
			}
			OnGround = reader.ReadByte() != 0;
			Tick = new Protocol.Types.PlayerInputTick();
			Tick.Read(reader);
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteByte((byte)PredictionType);
			Pos.Write(writer);
			PosDelta.Write(writer);
			Rotation.Write(writer);
			if (VehicleAngularVelocity != null && VehicleAngularVelocity.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteSingle(VehicleAngularVelocity.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
			writer.WriteByte(OnGround ? (byte)1 : (byte)0);
			Tick.Write(writer);
		}
	}
}

namespace Protocol
{
	public enum RewindType
	{
		Player = 0,
		Vehicle = 1,
	}
}
