// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class CreatePhotoPacket : IPacket
	{
		public int PacketId => 171;

		public ulong RawID { get; set; }
		public string PhotoName { get; set; }
		public string PhotoItemName { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			RawID = reader.ReadUInt64();
			PhotoName = reader.ReadLengthPrefixedString();
			PhotoItemName = reader.ReadLengthPrefixedString();
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteUInt64(RawID);
			writer.WriteLengthPrefixedString(PhotoName);
			writer.WriteLengthPrefixedString(PhotoItemName);
		}
	}
}
