// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Sent once by the server on startup to tell clients all of the items that can show up in the creative menu and recipe book.
	/// </summary>
	public class CreativeContentPacket : IPacket
	{
		public override int PacketId => 145;

		public List<Protocol.Types.CreativeGroupInfoPayload> Groups { get; set; } = new List<Protocol.Types.CreativeGroupInfoPayload>();
		public List<Protocol.Types.CreativeItemEntryPayload> Entries { get; set; } = new List<Protocol.Types.CreativeItemEntryPayload>();

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			Groups = reader.ReadSlice(() => { var _Item = new Protocol.Types.CreativeGroupInfoPayload(); _Item.Read(reader); return _Item; });
			Entries = reader.ReadSlice(() => { var _Item = new Protocol.Types.CreativeItemEntryPayload(); _Item.Read(reader); return _Item; });
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteSlice(Groups, v => v.Write(writer));
			writer.WriteSlice(Entries, v => v.Write(writer));
		}
	}
}
