// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Sends the name of the Structure Feature the player is currently occupying to the client.
	/// 	If the player is not in a structure, this packet contains an empty string.
	/// </summary>
	public class CurrentStructureFeaturePacket : IPacket
	{
		public int PacketId => 314;

		public string CurrentStructureFeature { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			CurrentStructureFeature = reader.ReadLengthPrefixedString();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(CurrentStructureFeature);
		}
	}
}
