// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Contains dimension definition data including height bounds and generator type for each dimension.
	/// </summary>
	public class DimensionDataPacket : IPacket
	{
		public override int PacketId => 180;

		public Dictionary<string, Protocol.Types.DimensionDefinitionGroup.DimensionDefinition> Definitions { get; set; } = new Dictionary<string, Protocol.Types.DimensionDefinitionGroup.DimensionDefinition>();

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			var _DefinitionsCount = VarInt.ReadUInt32(reader); 
			Definitions.Clear();
			for (int i = 0; i < _DefinitionsCount; i++)
			{
				var _DefinitionsKey = reader.ReadLengthPrefixedString();
				var _DefinitionsValue = new Protocol.Types.DimensionDefinitionGroup.DimensionDefinition();
				_DefinitionsValue.Read(reader);
				Definitions[_DefinitionsKey] = _DefinitionsValue;
			}
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteVarUInt32((uint)Definitions.Count); 
			foreach (var _DefinitionsPair in Definitions)
			{
				writer.WriteLengthPrefixedString(_DefinitionsPair.Key);
				_DefinitionsPair.Value.Write(writer);
			}
		}
	}
}
