// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class DisconnectPacket : IPacket
	{
		public override int PacketId => 5;

		public Protocol.Connection.DisconnectFailReason Reason { get; set; } 
		public OneOf<Protocol.Types.DisconnectPacketMessages, object> Messages { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			Reason = (Protocol.Connection.DisconnectFailReason)VarInt.ReadInt32(reader); 
			var _MessagesDisc = VarInt.ReadUInt32(reader); 
			switch (_MessagesDisc)
			{
				case 0:
				{
				var _MessagesCase0 = new Protocol.Types.DisconnectPacketMessages();
				_MessagesCase0.Read(reader);
				Messages = OneOf<Protocol.Types.DisconnectPacketMessages, object>.FromT0(_MessagesCase0);
				break;
				}
				case 1:
				{
				Messages = OneOf<Protocol.Types.DisconnectPacketMessages, object>.FromT1((object)null);
				break;
				}
				default:
					throw new InvalidDataException("Unknown Messages discriminant: " + _MessagesDisc);
			}
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteVarInt32((int)Reason); 
			switch (Messages.Index)
			{
				case 0:
				{
				writer.WriteVarUInt32((uint)Messages.Index); 
				Messages.AsT0.Write(writer);
				break;
				}
				case 1:
				{
				writer.WriteVarUInt32((uint)Messages.Index); 
				break;
				}
				default:
					throw new InvalidDataException("Invalid Messages OneOf index: " + Messages.Index);
			}
		}
	}
}

namespace Protocol.Types
{
	public class DisconnectPacketMessages
	{
		public string Message { get; set; }
		public string FilteredMessage { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			Message = reader.ReadLengthPrefixedString();
			FilteredMessage = reader.ReadLengthPrefixedString();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(Message);
			writer.WriteLengthPrefixedString(FilteredMessage);
		}
	}
}
