// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Currently transmits EducationLevelSettings to all clients when the game is starting.
	/// </summary>
	public class EducationSettingsPacket : IPacket
	{
		public int PacketId => 137;

		public Protocol.Types.EducationLevelSettings EducationLevelSettings { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			EducationLevelSettings = new Protocol.Types.EducationLevelSettings();
			EducationLevelSettings.Read(reader);
		}

		public void Write(MemoryStreamWriter writer)
		{
			EducationLevelSettings.Write(writer);
		}
	}
}
