// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class FeatureRegistryPacket : IPacket
	{
		public int PacketId => 191;

		public List<Protocol.Types.FeatureRegistry.FeatureBinaryJsonFormat> FeaturesDataList { get; set; } = new List<Protocol.Types.FeatureRegistry.FeatureBinaryJsonFormat>();

		public void Read(MemoryStreamReader reader)
		{
			FeaturesDataList = reader.ReadSlice(() => { var _Item = new Protocol.Types.FeatureRegistry.FeatureBinaryJsonFormat(); _Item.Read(reader); return _Item; });
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteSlice(FeaturesDataList, v => v.Write(writer));
		}
	}
}
