// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class GameTestRequestPacket : IPacket
	{
		public override int PacketId => 194;

		public int MaxTestsPerBatch { get; set; } 
		public int RepeatCount { get; set; } 
		public Protocol.Rotation Rotation { get; set; }
		public bool StopOnFailure { get; set; }
		public Protocol.Types.BlockPos TestPos { get; set; }
		public int TestsPerRow { get; set; } 
		public string TestName { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			MaxTestsPerBatch = VarInt.ReadInt32(reader); 
			RepeatCount = VarInt.ReadInt32(reader); 
			Rotation = (Protocol.Rotation)reader.ReadByte();
			StopOnFailure = reader.ReadByte() != 0;
			TestPos = new Protocol.Types.BlockPos();
			TestPos.Read(reader);
			TestsPerRow = VarInt.ReadInt32(reader); 
			TestName = reader.ReadLengthPrefixedString();
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteVarInt32(MaxTestsPerBatch); 
			writer.WriteVarInt32(RepeatCount); 
			writer.WriteByte((byte)Rotation);
			writer.WriteByte(StopOnFailure ? (byte)1 : (byte)0);
			TestPos.Write(writer);
			writer.WriteVarInt32(TestsPerRow); 
			writer.WriteLengthPrefixedString(TestName);
		}
	}
}
