// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Internal Text Packet
	/// </summary>
	public class GameTestResultsPacket : IPacket
	{
		public int PacketId => 195;

		public bool Succeeded { get; set; }
		public string Error { get; set; }
		public string TestName { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			Succeeded = reader.ReadByte() != 0;
			Error = reader.ReadLengthPrefixedString();
			TestName = reader.ReadLengthPrefixedString();
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteByte(Succeeded ? (byte)1 : (byte)0);
			writer.WriteLengthPrefixedString(Error);
			writer.WriteLengthPrefixedString(TestName);
		}
	}
}
