// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Informs client about any changes to the game rules.
	/// </summary>
	public class GameRulesChangedPacket : IPacket
	{
		public int PacketId => 72;

		public Protocol.Types.GameRulesChangedPacketData RuleData { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			RuleData = new Protocol.Types.GameRulesChangedPacketData();
			RuleData.Read(reader);
		}

		public void Write(MemoryStreamWriter writer)
		{
			RuleData.Write(writer);
		}
	}
}
