// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class GraphicsOverrideParameterPacket : IPacket
	{
		public int PacketId => 331;

		public Dictionary<float, Protocol.Types.Vec3> ParameterKeyframeValues { get; set; } = new Dictionary<float, Protocol.Types.Vec3>();
		public Optional<float> FloatValue { get; set; } = new Optional<float>();
		public Optional<Protocol.Types.Vec3> Vec3Value { get; set; } = new Optional<Protocol.Types.Vec3>();
		public string BiomeIdentifier { get; set; }
		public Optional<string> PlayerIdentifier { get; set; } = new Optional<string>();
		public Protocol.GraphicsOverrideParameterType IdentifierForParameter { get; set; }
		public bool ResetParameter { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			var _ParameterKeyframeValuesCount = VarInt.ReadUInt32(reader); 
			ParameterKeyframeValues.Clear();
			for (int i = 0; i < _ParameterKeyframeValuesCount; i++)
			{
				var _ParameterKeyframeValuesKey = reader.ReadSingle();
				var _ParameterKeyframeValuesValue = new Protocol.Types.Vec3();
				_ParameterKeyframeValuesValue.Read(reader);
				ParameterKeyframeValues[_ParameterKeyframeValuesKey] = _ParameterKeyframeValuesValue;
			}
			if (reader.ReadByte() != 0)
			{
				FloatValue = new Optional<float>(reader.ReadSingle());
			}
			if (reader.ReadByte() != 0)
			{
				var _Vec3ValueValue = new Protocol.Types.Vec3();
				_Vec3ValueValue.Read(reader);
				Vec3Value = new Optional<Protocol.Types.Vec3>(_Vec3ValueValue);
			}
			BiomeIdentifier = reader.ReadLengthPrefixedString();
			if (reader.ReadByte() != 0)
			{
				PlayerIdentifier = new Optional<string>(reader.ReadLengthPrefixedString());
			}
			IdentifierForParameter = (Protocol.GraphicsOverrideParameterType)reader.ReadByte();
			ResetParameter = reader.ReadByte() != 0;
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteVarUInt32((uint)ParameterKeyframeValues.Count); 
			foreach (var _ParameterKeyframeValuesPair in ParameterKeyframeValues)
			{
				writer.WriteSingle(_ParameterKeyframeValuesPair.Key);
				_ParameterKeyframeValuesPair.Value.Write(writer);
			}
			if (FloatValue != null && FloatValue.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteSingle(FloatValue.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (Vec3Value != null && Vec3Value.HasValue)
			{
				writer.WriteByte(1);
				Vec3Value.Value.Write(writer);
			}
			else
			{
				writer.WriteByte(0);
			}
			writer.WriteLengthPrefixedString(BiomeIdentifier);
			if (PlayerIdentifier != null && PlayerIdentifier.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteLengthPrefixedString(PlayerIdentifier.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
			writer.WriteByte((byte)IdentifierForParameter);
			writer.WriteByte(ResetParameter ? (byte)1 : (byte)0);
		}
	}
}

namespace Protocol
{
	public enum GraphicsOverrideParameterType
	{
		SkyZenithColor = 0,
		SkyHorizonColor = 1,
		HorizonBlendMin = 2,
		HorizonBlendMax = 3,
		HorizonBlendStart = 4,
		HorizonBlendMieStart = 5,
		RayleighStrength = 6,
		SunMieStrength = 7,
		MoonMieStrength = 8,
		SunGlareShape = 9,
		Chlorophyll = 10,
		CDOM = 11,
		SuspendedSediment = 12,
		WavesDepth = 13,
		WavesFrequency = 14,
		WavesFrequencyScaling = 15,
		WavesSpeed = 16,
		WavesSpeedScaling = 17,
		WavesShape = 18,
		WavesOctaves = 19,
		WavesMix = 20,
		WavesPull = 21,
		WavesDirectionIncrement = 22,
		MidtonesContrast = 23,
		HighlightsContrast = 24,
		ShadowsContrast = 25,
		HighlightsGain = 26,
		HighlightsGamma = 27,
		HighlightsOffset = 28,
		HighlightsSaturation = 29,
		MidtonesGain = 30,
		MidtonesGamma = 31,
		MidtonesOffset = 32,
		MidtonesSaturation = 33,
		ShadowsGain = 34,
		ShadowsGamma = 35,
		ShadowsOffset = 36,
		ShadowsSaturation = 37,
		HighlightsMin = 38,
		ShadowsMax = 39,
		Temperature = 40,
		SunColor = 41,
		SunIlluminance = 42,
		MoonColor = 43,
		MoonIlluminance = 44,
		FlashColor = 45,
		FlashIlluminance = 46,
		AmbientColor = 47,
		AmbientIlluminance = 48,
		EmissiveDesaturation = 49,
		SkyIntensity = 50,
		OrbitalOffsetDegrees = 51,
	}
}
