// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class InventoryContentPacket : IPacket
	{
		public int PacketId => 49;

		public uint ContainerId { get; set; } 
		public List<Protocol.Types.NetworkItemStackDescriptor.NetworkItemStackDescriptor> Slots { get; set; } = new List<Protocol.Types.NetworkItemStackDescriptor.NetworkItemStackDescriptor>();
		public Protocol.Types.FullContainerName FullContainerName { get; set; }
		public Protocol.Types.NetworkItemStackDescriptor.NetworkItemStackDescriptor StorageItem { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			ContainerId = VarInt.ReadUInt32(reader); 
			Slots = reader.ReadSlice(() => { var _Item = new Protocol.Types.NetworkItemStackDescriptor.NetworkItemStackDescriptor(); _Item.Read(reader); return _Item; });
			FullContainerName = new Protocol.Types.FullContainerName();
			FullContainerName.Read(reader);
			StorageItem = new Protocol.Types.NetworkItemStackDescriptor.NetworkItemStackDescriptor();
			StorageItem.Read(reader);
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteVarUInt32(ContainerId); 
			writer.WriteSlice(Slots, v => v.Write(writer));
			FullContainerName.Write(writer);
			StorageItem.Write(writer);
		}
	}
}
