// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class InventorySlotPacket : IPacket
	{
		public override int PacketId => 50;

		public byte ContainerId { get; set; }
		public uint Slot { get; set; } 
		public Optional<Protocol.Types.FullContainerName> FullContainerName { get; set; } = new Optional<Protocol.Types.FullContainerName>();
		public Optional<Protocol.Types.NetworkItemStackDescriptor.NetworkItemStackDescriptor> StorageItem { get; set; } = new Optional<Protocol.Types.NetworkItemStackDescriptor.NetworkItemStackDescriptor>();
		public Protocol.Types.NetworkItemStackDescriptor.NetworkItemStackDescriptor Item { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			ContainerId = (byte)reader.ReadByte();
			Slot = VarInt.ReadUInt32(reader); 
			if (reader.ReadByte() != 0)
			{
				var _FullContainerNameValue = new Protocol.Types.FullContainerName();
				_FullContainerNameValue.Read(reader);
				FullContainerName = new Optional<Protocol.Types.FullContainerName>(_FullContainerNameValue);
			}
			if (reader.ReadByte() != 0)
			{
				var _StorageItemValue = new Protocol.Types.NetworkItemStackDescriptor.NetworkItemStackDescriptor();
				_StorageItemValue.Read(reader);
				StorageItem = new Optional<Protocol.Types.NetworkItemStackDescriptor.NetworkItemStackDescriptor>(_StorageItemValue);
			}
			Item = new Protocol.Types.NetworkItemStackDescriptor.NetworkItemStackDescriptor();
			Item.Read(reader);
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteByte(ContainerId);
			writer.WriteVarUInt32(Slot); 
			if (FullContainerName != null && FullContainerName.HasValue)
			{
				writer.WriteByte(1);
				FullContainerName.Value.Write(writer);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (StorageItem != null && StorageItem.HasValue)
			{
				writer.WriteByte(1);
				StorageItem.Value.Write(writer);
			}
			else
			{
				writer.WriteByte(0);
			}
			Item.Write(writer);
		}
	}
}
