// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Sends the serialized jigsaw rule JSON to the client as it's needed on both the client and server.
	/// </summary>
	public class JigsawStructureDataPacket : IPacket
	{
		public int PacketId => 313;

		public Protocol.Types.CompoundTag JigsawStructureDataTag { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			JigsawStructureDataTag = new Protocol.Types.CompoundTag();
			JigsawStructureDataTag.Read(reader);
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			JigsawStructureDataTag.Write(writer);
		}
	}
}
