// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// It is a request from the client to either turn the page in the lectern or drop the book.
	/// </summary>
	public class LecternUpdatePacket : IPacket
	{
		public int PacketId => 125;

		public byte NewPageToShow { get; set; }
		public byte TotalPages { get; set; }
		public Protocol.Types.BlockPos PositionOfLecternToUpdate { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			NewPageToShow = (byte)reader.ReadByte();
			TotalPages = (byte)reader.ReadByte();
			PositionOfLecternToUpdate = new Protocol.Types.BlockPos();
			PositionOfLecternToUpdate.Read(reader);
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteByte(NewPageToShow);
			writer.WriteByte(TotalPages);
			PositionOfLecternToUpdate.Write(writer);
		}
	}
}
