// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Most sounds get launched on server and replicated to clients, but a handful of player initiated sounds are launched on their client and replicated through the network.
	/// 	(In most of the codebase 'Event' means telemetry events; this is not the case here, this is how sounds get replicated across the network in vanilla.)
	/// 	With support for custom entities. Entity Id is a string and Event Id is an integer.
	/// </summary>
	public class LevelSoundEventPacket : IPacket
	{
		public override int PacketId => 123;

		public string SoundEvent { get; set; }
		public Protocol.Types.Vec3 Position { get; set; }
		public int Data { get; set; } 
		public string ActorIdentifier { get; set; }
		public bool IsBaby { get; set; }
		public bool IsGlobal { get; set; }
		public long ActorUniqueId { get; set; }
		public Optional<Protocol.Types.Vec3> FireAtPosition { get; set; } = new Optional<Protocol.Types.Vec3>();

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			SoundEvent = reader.ReadLengthPrefixedString();
			Position = new Protocol.Types.Vec3();
			Position.Read(reader);
			Data = VarInt.ReadInt32(reader); 
			ActorIdentifier = reader.ReadLengthPrefixedString();
			IsBaby = reader.ReadByte() != 0;
			IsGlobal = reader.ReadByte() != 0;
			ActorUniqueId = reader.ReadInt64();
			if (reader.ReadByte() != 0)
			{
				var _FireAtPositionValue = new Protocol.Types.Vec3();
				_FireAtPositionValue.Read(reader);
				FireAtPosition = new Optional<Protocol.Types.Vec3>(_FireAtPositionValue);
			}
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteLengthPrefixedString(SoundEvent);
			Position.Write(writer);
			writer.WriteVarInt32(Data); 
			writer.WriteLengthPrefixedString(ActorIdentifier);
			writer.WriteByte(IsBaby ? (byte)1 : (byte)0);
			writer.WriteByte(IsGlobal ? (byte)1 : (byte)0);
			writer.WriteInt64(ActorUniqueId);
			if (FireAtPosition != null && FireAtPosition.HasValue)
			{
				writer.WriteByte(1);
				FireAtPosition.Value.Write(writer);
			}
			else
			{
				writer.WriteByte(0);
			}
		}
	}
}
