// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class LevelEventGenericPacket : IPacket
	{
		public override int PacketId => 124;

		public int EventId { get; set; } 
		public Protocol.Types.CompoundTag CTD { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			EventId = VarInt.ReadInt32(reader); 
			CTD = new Protocol.Types.CompoundTag();
			CTD.Deserialize(reader);
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteVarInt32(EventId); 
			CTD.Serialize(writer);
		}
	}
}
