// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class LoginPacket : IPacket
	{
		public override int PacketId => 1;

		public int ClientNetworkVersion { get; set; }
		public string ConnectionRequest { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			ClientNetworkVersion = BinaryPrimitives.ReverseEndianness(reader.ReadInt32());
			ConnectionRequest = reader.ReadLengthPrefixedString();
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteInt32(BinaryPrimitives.ReverseEndianness(ClientNetworkVersion));
			writer.WriteLengthPrefixedString(ConnectionRequest);
		}
	}
}
