// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// At the start of the game the server sends any mob effects with _sendAdditionalLevelData() if the joining player saved out with them,
	/// and then anytime a mob effect is added, removed, or updated this packet is sent.<br>
	/// It is important for player movement simulation to ensure that the following effects are sent for the player or any client predicted vehicle they are in control of:<br>
	/// - levitation<br>
	/// - slow_falling<br>
	/// - jump<br>
	/// - movement_speed<br>
	/// - movement_slowdown<br>
	/// - weaving
	/// </summary>
	public class MobEffectPacket : IPacket
	{
		public override int PacketId => 28;

		public Protocol.Types.ActorRuntimeID TargetRuntimeID { get; set; }
		public Protocol.MobEffectPacketPayload.Event EventID { get; set; }
		public int EffectID { get; set; } 
		public int EffectAmplifier { get; set; } 
		public bool ShowParticles { get; set; }
		public int EffectDurationTicks { get; set; } 
		public Protocol.Types.PlayerInputTick Tick { get; set; }
		public bool Ambient { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			TargetRuntimeID = new Protocol.Types.ActorRuntimeID();
			TargetRuntimeID.Read(reader);
			EventID = (Protocol.MobEffectPacketPayload.Event)reader.ReadByte();
			EffectID = VarInt.ReadInt32(reader); 
			EffectAmplifier = VarInt.ReadInt32(reader); 
			ShowParticles = reader.ReadByte() != 0;
			EffectDurationTicks = VarInt.ReadInt32(reader); 
			Tick = new Protocol.Types.PlayerInputTick();
			Tick.Read(reader);
			Ambient = reader.ReadByte() != 0;
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			TargetRuntimeID.Write(writer);
			writer.WriteByte((byte)EventID);
			writer.WriteVarInt32(EffectID); 
			writer.WriteVarInt32(EffectAmplifier); 
			writer.WriteByte(ShowParticles ? (byte)1 : (byte)0);
			writer.WriteVarInt32(EffectDurationTicks); 
			Tick.Write(writer);
			writer.WriteByte(Ambient ? (byte)1 : (byte)0);
		}
	}
}
