// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// This is from the server when spatial optimizations are enabled and the server does not send a spatial update.
	/// </summary>
	public class MotionPredictionHintsPacket : IPacket
	{
		public int PacketId => 157;

		public Protocol.Types.ActorRuntimeID MRuntimeId { get; set; }
		public Protocol.Types.Vec3 MMotion { get; set; }
		public bool MOnGround { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			MRuntimeId = new Protocol.Types.ActorRuntimeID();
			MRuntimeId.Read(reader);
			MMotion = new Protocol.Types.Vec3();
			MMotion.Read(reader);
			MOnGround = reader.ReadByte() != 0;
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			MRuntimeId.Write(writer);
			MMotion.Write(writer);
			writer.WriteByte(MOnGround ? (byte)1 : (byte)0);
		}
	}
}
