// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class MoveActorAbsolutePacket : IPacket
	{
		public int PacketId => 18;

		public Protocol.Types.MoveActorAbsoluteData MoveData { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			MoveData = new Protocol.Types.MoveActorAbsoluteData();
			MoveData.Read(reader);
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			MoveData.Write(writer);
		}
	}
}

namespace Protocol.Types
{
	public class MoveActorAbsoluteData
	{
		public ActorRuntimeID ActorRuntimeID { get; set; }
		public byte Header { get; set; }
		public Vec3 Position { get; set; }
		public byte RotationX { get; set; }
		public byte RotationY { get; set; }
		public byte RotationYHead { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			ActorRuntimeID = new ActorRuntimeID();
			ActorRuntimeID.Read(reader);
			Header = (byte)reader.ReadByte();
			Position = new Vec3();
			Position.Read(reader);
			RotationX = (byte)reader.ReadByte();
			RotationY = (byte)reader.ReadByte();
			RotationYHead = (byte)reader.ReadByte();
		}

		public void Write(MemoryStreamWriter writer)
		{
			ActorRuntimeID.Write(writer);
			writer.WriteByte(Header);
			Position.Write(writer);
			writer.WriteByte(RotationX);
			writer.WriteByte(RotationY);
			writer.WriteByte(RotationYHead);
		}
	}
}
