// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Each position, rotation and head-rotation component is sent as an independent optional, accompanied by flags indicating whether the actor is on the ground and whether this is a teleport.
	/// </summary>
	public class MoveActorDeltaPacket : IPacket
	{
		public override int PacketId => 111;

		public Protocol.Types.MoveActorDeltaData MoveData { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			MoveData = new Protocol.Types.MoveActorDeltaData();
			MoveData.Read(reader);
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			MoveData.Write(writer);
		}
	}
}

namespace Protocol.Types
{
	public class MoveActorDeltaData
	{
		public ActorRuntimeID ActorRuntimeID { get; set; }
		public Optional<float> NewPositionX { get; set; } = new Optional<float>();
		public Optional<float> NewPositionY { get; set; } = new Optional<float>();
		public Optional<float> NewPositionZ { get; set; } = new Optional<float>();
		public Optional<sbyte> RotationX { get; set; } = new Optional<sbyte>();
		public Optional<sbyte> RotationY { get; set; } = new Optional<sbyte>();
		public Optional<sbyte> RotationYHead { get; set; } = new Optional<sbyte>();
		public bool IsOnGround { get; set; }
		public bool ForceMove { get; set; }
		public bool ForceMoveLocalEntity { get; set; }
		public bool ForceCompletion { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			ActorRuntimeID = new ActorRuntimeID();
			ActorRuntimeID.Read(reader);
			if (reader.ReadByte() != 0)
			{
				NewPositionX = new Optional<float>(reader.ReadSingle());
			}
			if (reader.ReadByte() != 0)
			{
				NewPositionY = new Optional<float>(reader.ReadSingle());
			}
			if (reader.ReadByte() != 0)
			{
				NewPositionZ = new Optional<float>(reader.ReadSingle());
			}
			if (reader.ReadByte() != 0)
			{
				RotationX = new Optional<sbyte>((sbyte)reader.ReadByte());
			}
			if (reader.ReadByte() != 0)
			{
				RotationY = new Optional<sbyte>((sbyte)reader.ReadByte());
			}
			if (reader.ReadByte() != 0)
			{
				RotationYHead = new Optional<sbyte>((sbyte)reader.ReadByte());
			}
			IsOnGround = reader.ReadByte() != 0;
			ForceMove = reader.ReadByte() != 0;
			ForceMoveLocalEntity = reader.ReadByte() != 0;
			ForceCompletion = reader.ReadByte() != 0;
		}

		public void Write(MemoryStreamWriter writer)
		{
			ActorRuntimeID.Write(writer);
			if (NewPositionX != null && NewPositionX.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteSingle(NewPositionX.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (NewPositionY != null && NewPositionY.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteSingle(NewPositionY.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (NewPositionZ != null && NewPositionZ.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteSingle(NewPositionZ.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (RotationX != null && RotationX.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteByte((byte)RotationX.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (RotationY != null && RotationY.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteByte((byte)RotationY.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (RotationYHead != null && RotationYHead.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteByte((byte)RotationYHead.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
			writer.WriteByte(IsOnGround ? (byte)1 : (byte)0);
			writer.WriteByte(ForceMove ? (byte)1 : (byte)0);
			writer.WriteByte(ForceMoveLocalEntity ? (byte)1 : (byte)0);
			writer.WriteByte(ForceCompletion ? (byte)1 : (byte)0);
		}
	}
}
