// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class MovePlayerPacket : IPacket
	{
		public int PacketId => 19;

		public Protocol.Types.ActorRuntimeID PlayerRuntimeID { get; set; }
		public Protocol.Types.Vec3 Position { get; set; }
		public Protocol.Types.Vec2 Rotation { get; set; }
		public float YHeadRotation { get; set; }
		public Protocol.PlayerPositionModeComponent.PositionMode PositionMode { get; set; }
		public bool OnGround { get; set; }
		public Protocol.Types.ActorRuntimeID RidingRuntimeID { get; set; }
		public Optional<Protocol.Types.MovePlayerTeleportData> TeleportData { get; set; } = new Optional<Protocol.Types.MovePlayerTeleportData>();
		public Protocol.Types.PlayerInputTick Tick { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			PlayerRuntimeID = new Protocol.Types.ActorRuntimeID();
			PlayerRuntimeID.Read(reader);
			Position = new Protocol.Types.Vec3();
			Position.Read(reader);
			Rotation = new Protocol.Types.Vec2();
			Rotation.Read(reader);
			YHeadRotation = reader.ReadSingle();
			PositionMode = (Protocol.PlayerPositionModeComponent.PositionMode)reader.ReadByte();
			OnGround = reader.ReadByte() != 0;
			RidingRuntimeID = new Protocol.Types.ActorRuntimeID();
			RidingRuntimeID.Read(reader);
			if (reader.ReadByte() != 0)
			{
				var _TeleportDataValue = new Protocol.Types.MovePlayerTeleportData();
				_TeleportDataValue.Read(reader);
				TeleportData = new Optional<Protocol.Types.MovePlayerTeleportData>(_TeleportDataValue);
			}
			Tick = new Protocol.Types.PlayerInputTick();
			Tick.Read(reader);
		}

		public void Write(MemoryStreamWriter writer)
		{
			PlayerRuntimeID.Write(writer);
			Position.Write(writer);
			Rotation.Write(writer);
			writer.WriteSingle(YHeadRotation);
			writer.WriteByte((byte)PositionMode);
			writer.WriteByte(OnGround ? (byte)1 : (byte)0);
			RidingRuntimeID.Write(writer);
			if (TeleportData != null && TeleportData.HasValue)
			{
				writer.WriteByte(1);
				TeleportData.Value.Write(writer);
			}
			else
			{
				writer.WriteByte(0);
			}
			Tick.Write(writer);
		}
	}
}

namespace Protocol.Types
{
	public class MovePlayerTeleportData
	{
		public int TeleportationCause { get; set; }
		public int SourceActorType { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			TeleportationCause = reader.ReadInt32();
			SourceActorType = reader.ReadInt32();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteInt32(TeleportationCause);
			writer.WriteInt32(SourceActorType);
		}
	}
}
