// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// This is used by EDU for joining players and removing players from your session,
	/// 	the settings (there is only one) is an enum for enabling/disabling/refreshing multiplayer join codes.
	/// 	Starts on the client, and a response to the client is issued from the server.
	/// </summary>
	public class MultiplayerSettingsPacket : IPacket
	{
		public int PacketId => 139;

		public Protocol.MultiplayerSettingsPacketType PacketType { get; set; } 

		public void Read(MemoryStreamReader reader)
		{
			PacketType = (Protocol.MultiplayerSettingsPacketType)VarInt.ReadInt32(reader); 
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteVarInt32((int)PacketType); 
		}
	}
}
