// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Used (from the server) when a user's Chunk View moves, I.e. the area that determines what chunks exist. For ClientSideGeneration we also send the client a list of ChunkPos that the Server will fully build.
	/// </summary>
	public class NetworkChunkPublisherUpdatePacket : IPacket
	{
		public override int PacketId => 121;

		public Protocol.Types.BlockPos NewPositionForView { get; set; }
		public uint NewRadiusForView { get; set; } 
		public List<Protocol.Types.ChunkPos> ServerBuiltChunksList { get; set; } = new List<Protocol.Types.ChunkPos>();

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			NewPositionForView = new Protocol.Types.BlockPos();
			NewPositionForView.Read(reader);
			NewRadiusForView = VarInt.ReadUInt32(reader); 
			ServerBuiltChunksList = reader.ReadSliceUint32Length(() => { var _Item = new Protocol.Types.ChunkPos(); _Item.Read(reader); return _Item; });
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			NewPositionForView.Write(writer);
			writer.WriteVarUInt32(NewRadiusForView); 
			writer.WriteSliceUint32Length(ServerBuiltChunksList, v => v.Write(writer));
		}
	}
}
