// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class NetworkSettingsPacket : IPacket
	{
		public int PacketId => 143;

		public ushort CompressionThreshold { get; set; }
		public Protocol.PacketCompressionAlgorithm CompressionAlgorithm { get; set; }
		public bool ClientThrottleEnabled { get; set; }
		public byte ClientThrottleThreshold { get; set; }
		public float ClientThrottleScalar { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			CompressionThreshold = reader.ReadUInt16();
			CompressionAlgorithm = (Protocol.PacketCompressionAlgorithm)reader.ReadUInt16();
			ClientThrottleEnabled = reader.ReadByte() != 0;
			ClientThrottleThreshold = (byte)reader.ReadByte();
			ClientThrottleScalar = reader.ReadSingle();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteUInt16(CompressionThreshold);
			writer.WriteUInt16((ushort)CompressionAlgorithm);
			writer.WriteByte(ClientThrottleEnabled ? (byte)1 : (byte)0);
			writer.WriteByte(ClientThrottleThreshold);
			writer.WriteSingle(ClientThrottleScalar);
		}
	}
}
