// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class NpcDialoguePacket : IPacket
	{
		public int PacketId => 169;

		public ulong NpcIdRawId { get; set; }
		public Protocol.NpcDialoguePacketPayload.NpcDialogueActionType NpcDialogueActionType { get; set; } 
		public string Dialogue { get; set; }
		public string SceneName { get; set; }
		public string NpcName { get; set; }
		public string ActionJSON { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			NpcIdRawId = reader.ReadUInt64();
			NpcDialogueActionType = (Protocol.NpcDialoguePacketPayload.NpcDialogueActionType)VarInt.ReadInt32(reader); 
			Dialogue = reader.ReadLengthPrefixedString();
			SceneName = reader.ReadLengthPrefixedString();
			NpcName = reader.ReadLengthPrefixedString();
			ActionJSON = reader.ReadLengthPrefixedString();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteUInt64(NpcIdRawId);
			writer.WriteVarInt32((int)NpcDialogueActionType); 
			writer.WriteLengthPrefixedString(Dialogue);
			writer.WriteLengthPrefixedString(SceneName);
			writer.WriteLengthPrefixedString(NpcName);
			writer.WriteLengthPrefixedString(ActionJSON);
		}
	}
}

namespace Protocol.NpcDialoguePacketPayload
{
	public enum NpcDialogueActionType
	{
		Open = 0,
		Close = 1,
	}
}
