// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Sent from the player (and in one case from the village) to make those really cool animated effects for the hero of the village and the totem saving you. Just an id (unsigned int). At least thats what the code suggests. May be obsolete / deprecated.
	/// </summary>
	public class OnScreenTextureAnimationPacket : IPacket
	{
		public override int PacketId => 130;

		public uint EffectId { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			EffectId = reader.ReadUInt32();
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteUInt32(EffectId);
		}
	}
}
