// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class OpenSignPacket : IPacket
	{
		public int PacketId => 303;

		public Protocol.Types.BlockPos Pos { get; set; }
		public bool IsFrontSide { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			Pos = new Protocol.Types.BlockPos();
			Pos.Read(reader);
			IsFrontSide = reader.ReadByte() != 0;
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			Pos.Write(writer);
			writer.WriteByte(IsFrontSide ? (byte)1 : (byte)0);
		}
	}
}
