// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class PacketViolationWarningPacket : IPacket
	{
		public int PacketId => 156;

		public Protocol.PacketViolationType ViolationType { get; set; } 
		public Protocol.PacketViolationSeverity ViolationSeverity { get; set; } 
		public int ViolationPacketId { get; set; } 
		public string ViolationContext { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			ViolationType = (Protocol.PacketViolationType)VarInt.ReadInt32(reader); 
			ViolationSeverity = (Protocol.PacketViolationSeverity)VarInt.ReadInt32(reader); 
			ViolationPacketId = VarInt.ReadInt32(reader); 
			ViolationContext = reader.ReadLengthPrefixedString();
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteVarInt32((int)ViolationType); 
			writer.WriteVarInt32((int)ViolationSeverity); 
			writer.WriteVarInt32(ViolationPacketId); 
			writer.WriteLengthPrefixedString(ViolationContext);
		}
	}
}
