// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class PartyDestinationCookieResponsePacket : IPacket
	{
		public int PacketId => 350;

		public string Cookie { get; set; }
		public bool Accepted { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			Cookie = reader.ReadLengthPrefixedString();
			Accepted = reader.ReadByte() != 0;
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(Cookie);
			writer.WriteByte(Accepted ? (byte)1 : (byte)0);
		}
	}
}
