// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// When the player uses the camera item or adds a photo to the scrapbook it sends the photo to the server,
	/// 	then the server sends a response back on whether that was successful or not.
	/// 	Either uploads a photo to the server's photoStorage or request one from it to be stored in client's photoStorage.
	/// 	If no mPhotoData is provided it is a request for the given filename.
	/// </summary>
	public class PhotoTransferPacket : IPacket
	{
		public int PacketId => 99;

		public string PhotoName { get; set; }
		public string PhotoData { get; set; }
		public string BookID { get; set; }
		public Protocol.PhotoType Type_ { get; set; }
		public Protocol.PhotoType SourceType { get; set; }
		public long OwnerID { get; set; }
		public string NewPhotoName { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			PhotoName = reader.ReadLengthPrefixedString();
			PhotoData = reader.ReadLengthPrefixedString();
			BookID = reader.ReadLengthPrefixedString();
			Type_ = (Protocol.PhotoType)reader.ReadByte();
			SourceType = (Protocol.PhotoType)reader.ReadByte();
			OwnerID = reader.ReadInt64();
			NewPhotoName = reader.ReadLengthPrefixedString();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(PhotoName);
			writer.WriteLengthPrefixedString(PhotoData);
			writer.WriteLengthPrefixedString(BookID);
			writer.WriteByte((byte)Type_);
			writer.WriteByte((byte)SourceType);
			writer.WriteInt64(OwnerID);
			writer.WriteLengthPrefixedString(NewPhotoName);
		}
	}
}

namespace Protocol
{
	public enum PhotoType
	{
		Portfolio = 0,
		PhotoItem = 1,
		Book = 2,
	}
}
