// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// These are for Server Authoritative Movement to sync all player input with the server.
	/// </summary>
	public class PlayerAuthInputPacket : IPacket
	{
		public int PacketId => 144;

		public Protocol.Types.Vec2 PlayerRotation { get; set; }
		public Protocol.Types.Vec3 Position { get; set; }
		public Protocol.Types.Vec2 MoveVector { get; set; }
		public float PlayerHeadRotation { get; set; }
		public List<Protocol.PlayerAuthInputPacketPayload.InputData> InputData { get; set; } = new List<Protocol.PlayerAuthInputPacketPayload.InputData>(); 
		public Protocol.InputMode InputMode { get; set; } 
		public Protocol.ClientPlayMode PlayMode { get; set; } 
		public Protocol.NewInteractionModel NewInteractionModel { get; set; } 
		public Protocol.Types.Vec2 InteractRotation { get; set; }
		public Protocol.Types.PlayerInputTick ClientTick { get; set; }
		public Protocol.Types.Vec3 PosDelta { get; set; }
		public Optional<Protocol.Types.PackedItemUseLegacyInventoryTransaction> ItemUseTransaction { get; set; } = new Optional<Protocol.Types.PackedItemUseLegacyInventoryTransaction>();
		public Optional<Protocol.Types.ItemStackRequestCereal.RequestData> ItemStackRequest { get; set; } = new Optional<Protocol.Types.ItemStackRequestCereal.RequestData>();
		public Optional<List<Protocol.Types.PlayerBlockActionData>> PlayerBlockActions { get; set; } = new Optional<List<Protocol.Types.PlayerBlockActionData>>();
		public Optional<Protocol.Types.Vec2> VehicleRotation { get; set; } = new Optional<Protocol.Types.Vec2>();
		public Optional<Protocol.Types.ActorUniqueID> ClientPredictedVehicle { get; set; } = new Optional<Protocol.Types.ActorUniqueID>();
		public Protocol.Types.Vec2 AnalogMoveVector { get; set; }
		public Protocol.Types.Vec3 CameraOrientation { get; set; }
		public Protocol.Types.Vec2 RawMoveVector { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			PlayerRotation = new Protocol.Types.Vec2();
			PlayerRotation.Read(reader);
			Position = new Protocol.Types.Vec3();
			Position.Read(reader);
			MoveVector = new Protocol.Types.Vec2();
			MoveVector.Read(reader);
			PlayerHeadRotation = reader.ReadSingle();
			reader.ReadByte(); // 常量标志位true
			InputData = reader.ReadSlice(() => (Protocol.PlayerAuthInputPacketPayload.InputData)VarInt.ReadInt32(reader));
			InputMode = (Protocol.InputMode)VarInt.ReadUInt32(reader); 
			PlayMode = (Protocol.ClientPlayMode)VarInt.ReadUInt32(reader); 
			NewInteractionModel = (Protocol.NewInteractionModel)VarInt.ReadInt32(reader); 
			InteractRotation = new Protocol.Types.Vec2();
			InteractRotation.Read(reader);
			ClientTick = new Protocol.Types.PlayerInputTick();
			ClientTick.Read(reader);
			PosDelta = new Protocol.Types.Vec3();
			PosDelta.Read(reader);
			reader.ReadByte(); // 常量标志位true
			if (reader.ReadByte() != 0)
			{
				var _ItemUseTransactionValue = new Protocol.Types.PackedItemUseLegacyInventoryTransaction();
				_ItemUseTransactionValue.Read(reader);
				ItemUseTransaction = new Optional<Protocol.Types.PackedItemUseLegacyInventoryTransaction>(_ItemUseTransactionValue);
			}
			reader.ReadByte(); // 常量标志位true
			if (reader.ReadByte() != 0)
			{
				var _ItemStackRequestValue = new Protocol.Types.ItemStackRequestCereal.RequestData();
				_ItemStackRequestValue.Read(reader);
				ItemStackRequest = new Optional<Protocol.Types.ItemStackRequestCereal.RequestData>(_ItemStackRequestValue);
			}
			reader.ReadByte(); // 常量标志位true
			if (reader.ReadByte() != 0)
			{
				PlayerBlockActions = new Optional<List<Protocol.Types.PlayerBlockActionData>>(reader.ReadSlice(() => { var _Item = new Protocol.Types.PlayerBlockActionData(); _Item.Read(reader); return _Item; }));
			}
			reader.ReadByte(); // 常量标志位true
			if (reader.ReadByte() != 0)
			{
				var _VehicleRotationValue = new Protocol.Types.Vec2();
				_VehicleRotationValue.Read(reader);
				VehicleRotation = new Optional<Protocol.Types.Vec2>(_VehicleRotationValue);
			}
			reader.ReadByte(); // 常量标志位true
			if (reader.ReadByte() != 0)
			{
				var _ClientPredictedVehicleValue = new Protocol.Types.ActorUniqueID();
				_ClientPredictedVehicleValue.Read(reader);
				ClientPredictedVehicle = new Optional<Protocol.Types.ActorUniqueID>(_ClientPredictedVehicleValue);
			}
			AnalogMoveVector = new Protocol.Types.Vec2();
			AnalogMoveVector.Read(reader);
			CameraOrientation = new Protocol.Types.Vec3();
			CameraOrientation.Read(reader);
			RawMoveVector = new Protocol.Types.Vec2();
			RawMoveVector.Read(reader);
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			PlayerRotation.Write(writer);
			Position.Write(writer);
			MoveVector.Write(writer);
			writer.WriteSingle(PlayerHeadRotation);
			writer.WriteByte(1); // 常量标志位
			writer.WriteSlice(InputData, v => writer.WriteVarInt32((int)v));
			writer.WriteVarUInt32((uint)InputMode); 
			writer.WriteVarUInt32((uint)PlayMode); 
			writer.WriteVarInt32((int)NewInteractionModel); 
			InteractRotation.Write(writer);
			ClientTick.Write(writer);
			PosDelta.Write(writer);
			writer.WriteByte(1); // 常量标志位
			if (ItemUseTransaction != null && ItemUseTransaction.HasValue)
			{
				writer.WriteByte(1);
				ItemUseTransaction.Value.Write(writer);
			}
			else
			{
				writer.WriteByte(0);
			}
			writer.WriteByte(1); // 常量标志位
			if (ItemStackRequest != null && ItemStackRequest.HasValue)
			{
				writer.WriteByte(1);
				ItemStackRequest.Value.Write(writer);
			}
			else
			{
				writer.WriteByte(0);
			}
			writer.WriteByte(1); // 常量标志位
			if (PlayerBlockActions != null && PlayerBlockActions.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteSlice(PlayerBlockActions.Value, v => v.Write(writer));
			}
			else
			{
				writer.WriteByte(0);
			}
			writer.WriteByte(1); // 常量标志位
			if (VehicleRotation != null && VehicleRotation.HasValue)
			{
				writer.WriteByte(1);
				VehicleRotation.Value.Write(writer);
			}
			else
			{
				writer.WriteByte(0);
			}
			writer.WriteByte(1); // 常量标志位
			if (ClientPredictedVehicle != null && ClientPredictedVehicle.HasValue)
			{
				writer.WriteByte(1);
				ClientPredictedVehicle.Value.Write(writer);
			}
			else
			{
				writer.WriteByte(0);
			}
			AnalogMoveVector.Write(writer);
			CameraOrientation.Write(writer);
			RawMoveVector.Write(writer);
		}
	}
}

namespace Protocol
{
	public enum ClientPlayMode
	{
		Normal = 0,
		Teaser = 1,
		Screen = 2,
		Viewer = 3,
		Reality = 4,
		Placement = 5,
		LivingRoom = 6,
		ExitLevel = 7,
		ExitLevelLivingRoom = 8,
		NumModes = 9,
	}
}

namespace Protocol
{
	public enum InputMode
	{
		Undefined = 0,
		Mouse = 1,
		Touch = 2,
		GamePad = 3,
		MotionController = 4,
		Count = 5,
	}
}

namespace Protocol
{
	public enum NewInteractionModel
	{
		Touch = 0,
		Crosshair = 1,
		Classic = 2,
		Count = 3,
	}
}
