// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// The expected actions change depending on the ServerAuthMovementMode specified in the StartGamePacket.
	/// 	See the PlayerActionType enum for details on which have differing behavior.
	/// 	See also PlayerAuthInputPacket and InventoryTransactionPacket for similar types of player actions.
	/// </summary>
	public class PlayerActionPacket : IPacket
	{
		public int PacketId => 36;

		public Protocol.Types.ActorRuntimeID PlayerRuntimeID { get; set; }
		public Protocol.PlayerActionType Action { get; set; } 
		public Protocol.Types.BlockPos BlockPosition { get; set; }
		public Protocol.Types.BlockPos ResultPos { get; set; }
		public int Face { get; set; } 

		public void Read(MemoryStreamReader reader)
		{
			PlayerRuntimeID = new Protocol.Types.ActorRuntimeID();
			PlayerRuntimeID.Read(reader);
			Action = (Protocol.PlayerActionType)VarInt.ReadInt32(reader); 
			BlockPosition = new Protocol.Types.BlockPos();
			BlockPosition.Read(reader);
			ResultPos = new Protocol.Types.BlockPos();
			ResultPos.Read(reader);
			Face = VarInt.ReadInt32(reader); 
		}

		public void Write(MemoryStreamWriter writer)
		{
			PlayerRuntimeID.Write(writer);
			writer.WriteVarInt32((int)Action); 
			BlockPosition.Write(writer);
			ResultPos.Write(writer);
			writer.WriteVarInt32(Face); 
		}
	}
}
