// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Sent by PlayerLocationSender when a player position changes beyond a certain angle.
	/// </summary>
	public class PlayerLocationPacket : IPacket
	{
		public int PacketId => 326;

		public Protocol.Types.ActorUniqueID TargetActorID { get; set; }
		public OneOf<Protocol.Types.PlayerLocationPacketPayload.CoordinatesLocation, Protocol.Types.PlayerLocationPacketPayload.HiddenLocation> Location { get; set; }
		public Protocol.PlayerLocationPacketPayload.Type PacketType { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			TargetActorID = new Protocol.Types.ActorUniqueID();
			TargetActorID.Read(reader);
			var _LocationDisc = VarInt.ReadInt32(reader); 
			PacketType = (Protocol.PlayerLocationPacketPayload.Type)_LocationDisc;
			switch (_LocationDisc)
			{
				case 0:
				{
				var _LocationCase0 = new Protocol.Types.PlayerLocationPacketPayload.CoordinatesLocation();
				_LocationCase0.Read(reader);
				Location = OneOf<Protocol.Types.PlayerLocationPacketPayload.CoordinatesLocation, Protocol.Types.PlayerLocationPacketPayload.HiddenLocation>.FromT0(_LocationCase0);
				break;
				}
				case 1:
				{
				var _LocationCase1 = new Protocol.Types.PlayerLocationPacketPayload.HiddenLocation();
				_LocationCase1.Read(reader);
				Location = OneOf<Protocol.Types.PlayerLocationPacketPayload.CoordinatesLocation, Protocol.Types.PlayerLocationPacketPayload.HiddenLocation>.FromT1(_LocationCase1);
				break;
				}
				default:
					throw new InvalidDataException("Unknown Location discriminant: " + _LocationDisc);
			}
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			TargetActorID.Write(writer);
			writer.WriteVarInt32((int)PacketType); 
			switch (Location.Index)
			{
				case 0:
				{
				Location.AsT0.Write(writer);
				break;
				}
				case 1:
				{
				Location.AsT1.Write(writer);
				break;
				}
				default:
					throw new InvalidDataException("Invalid Location OneOf index: " + Location.Index);
			}
		}
	}
}
