// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Updates client entity property override data. Sets/removes an override for the indicated property for a specific entity on a client or clears all overrides for that entity.
	/// </summary>
	public class PlayerUpdateEntityOverridesPacket : IPacket
	{
		public int PacketId => 325;

		public Protocol.Types.ActorUniqueID TargetID { get; set; }
		public uint PropertyIndex { get; set; } 
		public OneOf<Protocol.Types.PlayerUpdateEntityOverridesPacketPayload.ClearOverride, Protocol.Types.PlayerUpdateEntityOverridesPacketPayload.RemoveOverride, Protocol.Types.PlayerUpdateEntityOverridesPacketPayload.IntOverride, Protocol.Types.PlayerUpdateEntityOverridesPacketPayload.FloatOverride> Update { get; set; }
		public Protocol.UpdateType Type_ { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			TargetID = new Protocol.Types.ActorUniqueID();
			TargetID.Read(reader);
			PropertyIndex = VarInt.ReadUInt32(reader); 
			var _UpdateDisc = (byte)reader.ReadByte();
			Type_ = (Protocol.UpdateType)_UpdateDisc;
			switch (_UpdateDisc)
			{
				case 0:
				{
				var _UpdateCase0 = new Protocol.Types.PlayerUpdateEntityOverridesPacketPayload.ClearOverride();
				_UpdateCase0.Read(reader);
				Update = OneOf<Protocol.Types.PlayerUpdateEntityOverridesPacketPayload.ClearOverride, Protocol.Types.PlayerUpdateEntityOverridesPacketPayload.RemoveOverride, Protocol.Types.PlayerUpdateEntityOverridesPacketPayload.IntOverride, Protocol.Types.PlayerUpdateEntityOverridesPacketPayload.FloatOverride>.FromT0(_UpdateCase0);
				break;
				}
				case 1:
				{
				var _UpdateCase1 = new Protocol.Types.PlayerUpdateEntityOverridesPacketPayload.RemoveOverride();
				_UpdateCase1.Read(reader);
				Update = OneOf<Protocol.Types.PlayerUpdateEntityOverridesPacketPayload.ClearOverride, Protocol.Types.PlayerUpdateEntityOverridesPacketPayload.RemoveOverride, Protocol.Types.PlayerUpdateEntityOverridesPacketPayload.IntOverride, Protocol.Types.PlayerUpdateEntityOverridesPacketPayload.FloatOverride>.FromT1(_UpdateCase1);
				break;
				}
				case 2:
				{
				var _UpdateCase2 = new Protocol.Types.PlayerUpdateEntityOverridesPacketPayload.IntOverride();
				_UpdateCase2.Read(reader);
				Update = OneOf<Protocol.Types.PlayerUpdateEntityOverridesPacketPayload.ClearOverride, Protocol.Types.PlayerUpdateEntityOverridesPacketPayload.RemoveOverride, Protocol.Types.PlayerUpdateEntityOverridesPacketPayload.IntOverride, Protocol.Types.PlayerUpdateEntityOverridesPacketPayload.FloatOverride>.FromT2(_UpdateCase2);
				break;
				}
				case 3:
				{
				var _UpdateCase3 = new Protocol.Types.PlayerUpdateEntityOverridesPacketPayload.FloatOverride();
				_UpdateCase3.Read(reader);
				Update = OneOf<Protocol.Types.PlayerUpdateEntityOverridesPacketPayload.ClearOverride, Protocol.Types.PlayerUpdateEntityOverridesPacketPayload.RemoveOverride, Protocol.Types.PlayerUpdateEntityOverridesPacketPayload.IntOverride, Protocol.Types.PlayerUpdateEntityOverridesPacketPayload.FloatOverride>.FromT3(_UpdateCase3);
				break;
				}
				default:
					throw new InvalidDataException("Unknown Update discriminant: " + _UpdateDisc);
			}
		}

		public void Write(MemoryStreamWriter writer)
		{
			TargetID.Write(writer);
			writer.WriteVarUInt32(PropertyIndex); 
			writer.WriteByte((byte)Type_);
			switch (Update.Index)
			{
				case 0:
				{
				Update.AsT0.Write(writer);
				break;
				}
				case 1:
				{
				Update.AsT1.Write(writer);
				break;
				}
				case 2:
				{
				Update.AsT2.Write(writer);
				break;
				}
				case 3:
				{
				Update.AsT3.Write(writer);
				break;
				}
				default:
					throw new InvalidDataException("Invalid Update OneOf index: " + Update.Index);
			}
		}
	}
}
