// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Sent from the Server at the start of the game or when a player is added to all clients. Lists the players.
	/// </summary>
	public class PlayerListPacket : IPacket
	{
		public int PacketId => 63;

		public List<OneOf<Protocol.Types.PlayerListPacketPayload.RemoveEntry, Protocol.Types.PlayerListPacketPayload.AddEntry>> Entries { get; set; } = new List<OneOf<Protocol.Types.PlayerListPacketPayload.RemoveEntry, Protocol.Types.PlayerListPacketPayload.AddEntry>>();
		public Protocol.PlayerListPacketType Action { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			var _EntriesCount = VarInt.ReadUInt32(reader); 
			Entries.Clear();
			for (int i = 0; i < _EntriesCount; i++)
			{
				OneOf<Protocol.Types.PlayerListPacketPayload.RemoveEntry, Protocol.Types.PlayerListPacketPayload.AddEntry> _EntriesItem = default;
				var _EntriesDisc = (byte)reader.ReadByte();
				switch (_EntriesDisc)
				{
					case 0:
					{
					var _EntriesCase0 = new Protocol.Types.PlayerListPacketPayload.RemoveEntry();
					_EntriesCase0.Read(reader);
					_EntriesItem = OneOf<Protocol.Types.PlayerListPacketPayload.RemoveEntry, Protocol.Types.PlayerListPacketPayload.AddEntry>.FromT0(_EntriesCase0);
					break;
					}
					case 1:
					{
					var _EntriesCase1 = new Protocol.Types.PlayerListPacketPayload.AddEntry();
					_EntriesCase1.Read(reader);
					_EntriesItem = OneOf<Protocol.Types.PlayerListPacketPayload.RemoveEntry, Protocol.Types.PlayerListPacketPayload.AddEntry>.FromT1(_EntriesCase1);
					break;
					}
					default:
						throw new InvalidDataException("Unknown Entries discriminant: " + _EntriesDisc);
				}
				Entries.Add(_EntriesItem);
			}
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteVarUInt32((uint)Entries.Count); 
			foreach (var _EntriesItem in Entries)
			{
				writer.WriteByte((byte)_EntriesItem.Index);
				switch (_EntriesItem.Index)
				{
					case 0:
					{
					_EntriesItem.AsT0.Write(writer);
					break;
					}
					case 1:
					{
					_EntriesItem.AsT1.Write(writer);
					break;
					}
					default:
						throw new InvalidDataException("Invalid Entries OneOf index: " + _EntriesItem.Index);
				}
			}
		}
	}
}
