// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class PlayerHotbarPacket : IPacket
	{
		public int PacketId => 48;

		public uint SelectedSlot { get; set; } 
		public byte ContainerID { get; set; }
		public bool ShouldSelectSlot { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			SelectedSlot = VarInt.ReadUInt32(reader); 
			ContainerID = (byte)reader.ReadByte();
			ShouldSelectSlot = reader.ReadByte() != 0;
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteVarUInt32(SelectedSlot); 
			writer.WriteByte(ContainerID);
			writer.WriteByte(ShouldSelectSlot ? (byte)1 : (byte)0);
		}
	}
}
