// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class PlaySoundPacket : IPacket
	{
		public override int PacketId => 86;

		public string Name { get; set; }
		public Protocol.Types.BlockPos Position { get; set; }
		public float Volume { get; set; }
		public float Pitch { get; set; }
		public int LoopCount { get; set; } 
		public Optional<Protocol.Types.ServerSoundHandle> ServerSoundHandle { get; set; } = new Optional<Protocol.Types.ServerSoundHandle>();

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			Name = reader.ReadLengthPrefixedString();
			Position = new Protocol.Types.BlockPos();
			Position.Read(reader);
			Volume = reader.ReadSingle();
			Pitch = reader.ReadSingle();
			LoopCount = VarInt.ReadInt32(reader); 
			if (reader.ReadByte() != 0)
			{
				var _ServerSoundHandleValue = new Protocol.Types.ServerSoundHandle();
				_ServerSoundHandleValue.Read(reader);
				ServerSoundHandle = new Optional<Protocol.Types.ServerSoundHandle>(_ServerSoundHandleValue);
			}
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteLengthPrefixedString(Name);
			Position.Write(writer);
			writer.WriteSingle(Volume);
			writer.WriteSingle(Pitch);
			writer.WriteVarInt32(LoopCount); 
			if (ServerSoundHandle != null && ServerSoundHandle.HasValue)
			{
				writer.WriteByte(1);
				ServerSoundHandle.Value.Write(writer);
			}
			else
			{
				writer.WriteByte(0);
			}
		}
	}
}

namespace Protocol.Types
{
	public class ServerSoundHandle
	{
		public ulong Value { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			Value = reader.ReadUInt64();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteUInt64(Value);
		}
	}
}
