// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// This is the packet that tracks the active fog stack from the server so the local players can apply different fog settings.
	/// </summary>
	public class PlayerFogPacket : IPacket
	{
		public override int PacketId => 160;

		public List<string> FogStack { get; set; } = new List<string>();

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			FogStack = reader.ReadSlice(() => reader.ReadLengthPrefixedString());
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteSlice(FogStack, v => writer.WriteLengthPrefixedString(v));
		}
	}
}
