// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class PlayerInputPacket : IPacket
	{
		public int PacketId => 57;

		public Protocol.Types.Vec2 Move { get; set; }
		public bool Jumping { get; set; }
		public bool Sneaking { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			Move = new Protocol.Types.Vec2();
			Move.Read(reader);
			Jumping = reader.ReadByte() != 0;
			Sneaking = reader.ReadByte() != 0;
		}

		public void Write(MemoryStreamWriter writer)
		{
			Move.Write(writer);
			writer.WriteByte(Jumping ? (byte)1 : (byte)0);
			writer.WriteByte(Sneaking ? (byte)1 : (byte)0);
		}
	}
}
