// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Client to server packet for server authoratative runtime database (with persistent LevelStorage backup) designed primarily to track lodestone stuff. See Position Tracking DB Notes.md in bedrock-docs. see PositionTrackingDBServerBroadcastPacket
	/// </summary>
	public class PositionTrackingDBClientRequestPacket : IPacket
	{
		public int PacketId => 154;

		public Protocol.PositionTrackingDBClientRequestPacketPayload.Action Action { get; set; }
		public Protocol.Types.PositionTrackingId Id { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			Action = (Protocol.PositionTrackingDBClientRequestPacketPayload.Action)reader.ReadByte();
			Id = new Protocol.Types.PositionTrackingId();
			Id.Read(reader);
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteByte((byte)Action);
			Id.Write(writer);
		}
	}
}

namespace Protocol.PositionTrackingDBClientRequestPacketPayload
{
	public enum Action
	{
		Query = 0,
	}
}

namespace Protocol.Types
{
	public class PositionTrackingId
	{
		public int Value { get; set; } 

		public void Read(MemoryStreamReader reader)
		{
			Value = VarInt.ReadInt32(reader); 
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteVarInt32(Value); 
		}
	}
}
