// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class PrimitiveShapesPacket : IPacket
	{
		public int PacketId => 328;

		public List<Protocol.Types.PrimitiveShapeDataPayload> ArrayOfPrimitiveShapesCanBeAMixOfNewUpdatedOrRemoved { get; set; } = new List<Protocol.Types.PrimitiveShapeDataPayload>();

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			ArrayOfPrimitiveShapesCanBeAMixOfNewUpdatedOrRemoved = reader.ReadSlice(() => { var _Item = new Protocol.Types.PrimitiveShapeDataPayload(); _Item.Read(reader); return _Item; });
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteSlice(ArrayOfPrimitiveShapesCanBeAMixOfNewUpdatedOrRemoved, v => v.Write(writer));
		}
	}
}
