// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Sent from the client after we make a purchase in the store OR if we login and our entitlements are verified.
	/// It sends a vector of purchase receipts(string).There is a handler and a multiple senders.
	/// </summary>
	public class PurchaseReceiptPacket : IPacket
	{
		public int PacketId => 92;

		public List<string> PurchaseReceipts { get; set; } = new List<string>();

		public void Read(MemoryStreamReader reader)
		{
			PurchaseReceipts = reader.ReadSlice(() => reader.ReadLengthPrefixedString());
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteSlice(PurchaseReceipts, v => writer.WriteLengthPrefixedString(v));
		}
	}
}
