// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class RemoveVolumeEntityPacket : IPacket
	{
		public override int PacketId => 167;

		public Protocol.Types.EntityNetId EntityNetworkId { get; set; }
		public Protocol.Types.DimensionType DimensionType { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			EntityNetworkId = new Protocol.Types.EntityNetId();
			EntityNetworkId.Read(reader);
			DimensionType = new Protocol.Types.DimensionType();
			DimensionType.Read(reader);
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			EntityNetworkId.Write(writer);
			DimensionType.Write(writer);
		}
	}
}
