// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// This is just the name of the objective.
	/// </summary>
	public class RemoveObjectivePacket : IPacket
	{
		public int PacketId => 106;

		public string ObjectiveName { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			ObjectiveName = reader.ReadLengthPrefixedString();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(ObjectiveName);
		}
	}
}
