// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// This packet is to make sure that the server expands/shrinks first. Additionally for ClientSide Chunk Generation we can send a byte, based on client's hardware capabilities what is the max chunk radius client can handle.
	/// </summary>
	public class RequestChunkRadiusPacket : IPacket
	{
		public override int PacketId => 69;

		public int ChunkRadius { get; set; } 
		public byte MaxChunkRadius { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			ChunkRadius = VarInt.ReadInt32(reader); 
			MaxChunkRadius = (byte)reader.ReadByte();
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteVarInt32(ChunkRadius); 
			writer.WriteByte(MaxChunkRadius);
		}
	}
}
