// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Once changed, the server will broadcast the updated state of abilities for that player. If the request is rejected, the caller will receive their reverted state of Abilities.  Can only be used to modify the calling player.  	- mVariable: Info about this variable
	/// </summary>
	public class RequestAbilityPacket : IPacket
	{
		public int PacketId => 184;

		public int Ability { get; set; } 
		public Protocol.RequestAbilityPacketPayload.Type ValueType_ { get; set; }
		public bool Bool { get; set; }
		public float Float { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			Ability = VarInt.ReadInt32(reader); 
			ValueType_ = (Protocol.RequestAbilityPacketPayload.Type)reader.ReadByte();
			Bool = reader.ReadByte() != 0;
			Float = reader.ReadSingle();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteVarInt32(Ability); 
			writer.WriteByte((byte)ValueType_);
			writer.WriteByte(Bool ? (byte)1 : (byte)0);
			writer.WriteSingle(Float);
		}
	}
}

namespace Protocol.RequestAbilityPacketPayload
{
	public enum Type
	{
		Unset = 0,
		Bool = 1,
		Float = 2,
	}
}
