// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Sends resource pack information to the client including pack IDs, versions, sizes, and content keys.
	/// </summary>
	public class ResourcePacksInfoPacket : IPacket
	{
		public override int PacketId => 6;

		public bool ResourcePackRequired { get; set; }
		public bool HasAddonPacks { get; set; }
		public bool HasScripts { get; set; }
		public bool ForceDisableVibrantVisuals { get; set; }
		public Protocol.Types.PackIdVersion WorldTemplateIdAndVersion { get; set; }
		public List<Protocol.Types.PackInfoData> ResourcePacks { get; set; } = new List<Protocol.Types.PackInfoData>();

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			ResourcePackRequired = reader.ReadByte() != 0;
			HasAddonPacks = reader.ReadByte() != 0;
			HasScripts = reader.ReadByte() != 0;
			ForceDisableVibrantVisuals = reader.ReadByte() != 0;
			WorldTemplateIdAndVersion = new Protocol.Types.PackIdVersion();
			WorldTemplateIdAndVersion.Read(reader);
			ResourcePacks = reader.ReadSlice(() => { var _Item = new Protocol.Types.PackInfoData(); _Item.Read(reader); return _Item; });
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteByte(ResourcePackRequired ? (byte)1 : (byte)0);
			writer.WriteByte(HasAddonPacks ? (byte)1 : (byte)0);
			writer.WriteByte(HasScripts ? (byte)1 : (byte)0);
			writer.WriteByte(ForceDisableVibrantVisuals ? (byte)1 : (byte)0);
			WorldTemplateIdAndVersion.Write(writer);
			writer.WriteSlice(ResourcePacks, v => v.Write(writer));
		}
	}
}
