// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Sent from the serverFileChunkUploader during the initialization of the file uploader. This packet is sent to the primary client.
	/// </summary>
	public class ResourcePackDataInfoPacket : IPacket
	{
		public int PacketId => 82;

		public string ResourceName { get; set; }
		public uint ChunkSize { get; set; }
		public uint NumberOfChunks { get; set; }
		public ulong FileSize { get; set; }
		public byte[] FileHash { get; set; }
		public bool IsPremiumPack { get; set; }
		public byte PackType { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			ResourceName = reader.ReadLengthPrefixedString();
			ChunkSize = reader.ReadUInt32();
			NumberOfChunks = reader.ReadUInt32();
			FileSize = reader.ReadUInt64();
			FileHash = reader.ReadLengthPrefixedBytes().ToArray();
			IsPremiumPack = reader.ReadByte() != 0;
			PackType = (byte)reader.ReadByte();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(ResourceName);
			writer.WriteUInt32(ChunkSize);
			writer.WriteUInt32(NumberOfChunks);
			writer.WriteUInt64(FileSize);
			writer.WriteLengthPrefixedBytes(FileHash);
			writer.WriteByte(IsPremiumPack ? (byte)1 : (byte)0);
			writer.WriteByte(PackType);
		}
	}
}
