// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// (only one marked for uncompressed) realms resource pack download
	/// </summary>
	public class ResourcePackChunkDataPacket : IPacket
	{
		public int PacketId => 83;

		public string ResourceName { get; set; }
		public uint ChunkID { get; set; }
		public ulong ByteOffset { get; set; }
		public string ChunkData { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			ResourceName = reader.ReadLengthPrefixedString();
			ChunkID = reader.ReadUInt32();
			ByteOffset = reader.ReadUInt64();
			ChunkData = reader.ReadLengthPrefixedString();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(ResourceName);
			writer.WriteUInt32(ChunkID);
			writer.WriteUInt64(ByteOffset);
			writer.WriteLengthPrefixedString(ChunkData);
		}
	}
}
