// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Sent to MinecraftGame to complete the resource pack loading process.
	/// </summary>
	public class ResourcePackClientResponsePacket : IPacket
	{
		public int PacketId => 8;

		public OneOf<Protocol.Types.ResourcePackClientResponsePacketPayload.Cancel, Protocol.Types.ResourcePackClientResponsePacketPayload.Downloading, Protocol.Types.ResourcePackClientResponsePacketPayload.DownloadingFinished, Protocol.Types.ResourcePackClientResponsePacketPayload.ResourcePackStackFinished> Response { get; set; }
		public Protocol.ResourcePackResponse ResponseType { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			var _ResponseDisc = (byte)reader.ReadByte();
			ResponseType = (Protocol.ResourcePackResponse)_ResponseDisc;
			switch (_ResponseDisc)
			{
				case 0:
				{
				var _ResponseCase0 = new Protocol.Types.ResourcePackClientResponsePacketPayload.Cancel();
				_ResponseCase0.Read(reader);
				Response = OneOf<Protocol.Types.ResourcePackClientResponsePacketPayload.Cancel, Protocol.Types.ResourcePackClientResponsePacketPayload.Downloading, Protocol.Types.ResourcePackClientResponsePacketPayload.DownloadingFinished, Protocol.Types.ResourcePackClientResponsePacketPayload.ResourcePackStackFinished>.FromT0(_ResponseCase0);
				break;
				}
				case 1:
				{
				var _ResponseCase1 = new Protocol.Types.ResourcePackClientResponsePacketPayload.Downloading();
				_ResponseCase1.Read(reader);
				Response = OneOf<Protocol.Types.ResourcePackClientResponsePacketPayload.Cancel, Protocol.Types.ResourcePackClientResponsePacketPayload.Downloading, Protocol.Types.ResourcePackClientResponsePacketPayload.DownloadingFinished, Protocol.Types.ResourcePackClientResponsePacketPayload.ResourcePackStackFinished>.FromT1(_ResponseCase1);
				break;
				}
				case 2:
				{
				var _ResponseCase2 = new Protocol.Types.ResourcePackClientResponsePacketPayload.DownloadingFinished();
				_ResponseCase2.Read(reader);
				Response = OneOf<Protocol.Types.ResourcePackClientResponsePacketPayload.Cancel, Protocol.Types.ResourcePackClientResponsePacketPayload.Downloading, Protocol.Types.ResourcePackClientResponsePacketPayload.DownloadingFinished, Protocol.Types.ResourcePackClientResponsePacketPayload.ResourcePackStackFinished>.FromT2(_ResponseCase2);
				break;
				}
				case 3:
				{
				var _ResponseCase3 = new Protocol.Types.ResourcePackClientResponsePacketPayload.ResourcePackStackFinished();
				_ResponseCase3.Read(reader);
				Response = OneOf<Protocol.Types.ResourcePackClientResponsePacketPayload.Cancel, Protocol.Types.ResourcePackClientResponsePacketPayload.Downloading, Protocol.Types.ResourcePackClientResponsePacketPayload.DownloadingFinished, Protocol.Types.ResourcePackClientResponsePacketPayload.ResourcePackStackFinished>.FromT3(_ResponseCase3);
				break;
				}
				default:
					throw new InvalidDataException("Unknown Response discriminant: " + _ResponseDisc);
			}
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteByte((byte)ResponseType);
			switch (Response.Index)
			{
				case 0:
				{
				Response.AsT0.Write(writer);
				break;
				}
				case 1:
				{
				Response.AsT1.Write(writer);
				break;
				}
				case 2:
				{
				Response.AsT2.Write(writer);
				break;
				}
				case 3:
				{
				Response.AsT3.Write(writer);
				break;
				}
				default:
					throw new InvalidDataException("Invalid Response OneOf index: " + Response.Index);
			}
		}
	}
}
