// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class ScriptMessagePacket : IPacket
	{
		public int PacketId => 177;

		public string MessageId { get; set; }
		public string MessageValue { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			MessageId = reader.ReadLengthPrefixedString();
			MessageValue = reader.ReadLengthPrefixedString();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(MessageId);
			writer.WriteLengthPrefixedString(MessageValue);
		}
	}
}
