// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class SendPartyDestinationCookiePacket : IPacket
	{
		public int PacketId => 349;

		public string Cookie { get; set; }
		public Protocol.PartyDestinationCookieIntent Intent { get; set; }
		public string DestinationName { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			Cookie = reader.ReadLengthPrefixedString();
			Intent = EnumCodec.FromString<Protocol.PartyDestinationCookieIntent>(reader.ReadLengthPrefixedString());
			DestinationName = reader.ReadLengthPrefixedString();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(Cookie);
			writer.WriteLengthPrefixedString(EnumCodec.ToString(Intent));
			writer.WriteLengthPrefixedString(DestinationName);
		}
	}
}

namespace Protocol
{
	public enum PartyDestinationCookieIntent
	{
		Notify = 0,
		OptIn = 1,
		OptOut = 2,
	}
}
