// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class ServerboundDataStorePacket : IPacket
	{
		public int PacketId => 332;

		public Protocol.Types.Bedrock.DDUI.DataStoreUpdate Update { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			Update = new Protocol.Types.Bedrock.DDUI.DataStoreUpdate();
			Update.Read(reader);
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			Update.Write(writer);
		}
	}
}
