// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class ServerboundDataDrivenScreenClosedPacket : IPacket
	{
		public int PacketId => 343;

		public uint FormId { get; set; }
		public Protocol.DataDrivenScreenClosedReason CloseReason { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			FormId = reader.ReadUInt32();
			CloseReason = EnumCodec.FromString<Protocol.DataDrivenScreenClosedReason>(reader.ReadLengthPrefixedString());
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteUInt32(FormId);
			writer.WriteLengthPrefixedString(EnumCodec.ToString(CloseReason));
		}
	}
}

namespace Protocol
{
	public enum DataDrivenScreenClosedReason
	{
		ProgrammaticClose = 0,
		ProgrammaticCloseAll = 1,
		ClientCanceled = 2,
		UserBusy = 3,
		InvalidForm = 4,
	}
}
