// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class ServerboundPackSettingChangePacket : IPacket
	{
		public int PacketId => 329;

		public Protocol.Types.mce.UUID PackId { get; set; }
		public string PackSettingName { get; set; }
		public OneOf<float, bool, string> PackSettingValue { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			PackId = new Protocol.Types.mce.UUID();
			PackId.Read(reader);
			PackSettingName = reader.ReadLengthPrefixedString();
			var _PackSettingValueDisc = VarInt.ReadUInt32(reader); 
			switch (_PackSettingValueDisc)
			{
				case 0:
				{
				PackSettingValue = OneOf<float, bool, string>.FromT0(reader.ReadSingle());
				break;
				}
				case 1:
				{
				PackSettingValue = OneOf<float, bool, string>.FromT1(reader.ReadByte() != 0);
				break;
				}
				case 2:
				{
				PackSettingValue = OneOf<float, bool, string>.FromT2(reader.ReadLengthPrefixedString());
				break;
				}
				default:
					throw new InvalidDataException("Unknown PackSettingValue discriminant: " + _PackSettingValueDisc);
			}
		}

		public void Write(MemoryStreamWriter writer)
		{
			PackId.Write(writer);
			writer.WriteLengthPrefixedString(PackSettingName);
			switch (PackSettingValue.Index)
			{
				case 0:
				{
				writer.WriteVarUInt32((uint)PackSettingValue.Index); 
				writer.WriteSingle(PackSettingValue.AsT0);
				break;
				}
				case 1:
				{
				writer.WriteVarUInt32((uint)PackSettingValue.Index); 
				writer.WriteByte(PackSettingValue.AsT1 ? (byte)1 : (byte)0);
				break;
				}
				case 2:
				{
				writer.WriteVarUInt32((uint)PackSettingValue.Index); 
				writer.WriteLengthPrefixedString(PackSettingValue.AsT2);
				break;
				}
				default:
					throw new InvalidDataException("Invalid PackSettingValue OneOf index: " + PackSettingValue.Index);
			}
		}
	}
}
