// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class ServerPresenceInfoPacket : IPacket
	{
		public override int PacketId => 347;

		public Optional<Protocol.Types.ServerConfiguration.PresenceConfiguration> PresenceConfiguration { get; set; } = new Optional<Protocol.Types.ServerConfiguration.PresenceConfiguration>();

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			if (reader.ReadByte() != 0)
			{
				var _PresenceConfigurationValue = new Protocol.Types.ServerConfiguration.PresenceConfiguration();
				_PresenceConfigurationValue.Read(reader);
				PresenceConfiguration = new Optional<Protocol.Types.ServerConfiguration.PresenceConfiguration>(_PresenceConfigurationValue);
			}
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			if (PresenceConfiguration != null && PresenceConfiguration.HasValue)
			{
				writer.WriteByte(1);
				PresenceConfiguration.Value.Write(writer);
			}
			else
			{
				writer.WriteByte(0);
			}
		}
	}
}
