// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// In order for the client to send a packet with StartLoadingScreen, the server needs to anticipate that this packet is coming.
	/// If the server doesn't expect that we are about to start a loading screen, the server will disconnect the client.
	/// EndLoadingScreen is sent by the client when the loading screen closes.
	/// The Loading Screen Id field will be empty if the loading screen is triggered by the initial loading into of a world.
	/// The Loading Screen Id field will have a value if sent by the server. This currently happens as part of ChangeDimensionPacket if the player is alive.
	/// </summary>
	public class ServerboundLoadingScreenPacket : IPacket
	{
		public int PacketId => 312;

		public Protocol.ServerboundLoadingScreenPacketType LoadingScreenPacketType { get; set; } 
		public Optional<uint> LoadingScreenId { get; set; } = new Optional<uint>();

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			LoadingScreenPacketType = (Protocol.ServerboundLoadingScreenPacketType)VarInt.ReadInt32(reader); 
			if (reader.ReadByte() != 0)
			{
				LoadingScreenId = new Optional<uint>(reader.ReadUInt32());
			}
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteVarInt32((int)LoadingScreenPacketType); 
			if (LoadingScreenId != null && LoadingScreenId.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteUInt32(LoadingScreenId.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
		}
	}
}

namespace Protocol
{
	public enum ServerboundLoadingScreenPacketType
	{
		Unknown = 0,
		StartLoadingScreen = 1,
		EndLoadingScreen = 2,
	}
}
