// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Sent from the server at the end of the login packet
	/// </summary>
	public class ServerToClientHandshakePacket : IPacket
	{
		public int PacketId => 3;

		public string HandshakeWebToken { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			HandshakeWebToken = reader.ReadLengthPrefixedString();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(HandshakeWebToken);
		}
	}
}
