// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Sent from server.
	/// </summary>
	public class ServerStatsPacket : IPacket
	{
		public int PacketId => 192;

		public float ServerTime { get; set; }
		public float NetworkTime { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			ServerTime = reader.ReadSingle();
			NetworkTime = reader.ReadSingle();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteSingle(ServerTime);
			writer.WriteSingle(NetworkTime);
		}
	}
}
