// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Sent when the player starts riding something. Two are sent at a time for some reason.
	/// </summary>
	public class SetActorLinkPacket : IPacket
	{
		public override int PacketId => 41;

		public Protocol.Types.ActorLink Link { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			Link = new Protocol.Types.ActorLink();
			Link.Read(reader);
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			Link.Write(writer);
		}
	}
}
