// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class SetActorDataPacket : IPacket
	{
		public int PacketId => 39;

		public Protocol.Types.ActorRuntimeID TargetRuntimeID { get; set; }
		public Protocol.Types.SynchedActorData.CopyableDataList ActorData { get; set; }
		public Protocol.Types.PropertySyncData SynchedProperties { get; set; }
		public Protocol.Types.PlayerInputTick Tick { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			TargetRuntimeID = new Protocol.Types.ActorRuntimeID();
			TargetRuntimeID.Read(reader);
			ActorData = new Protocol.Types.SynchedActorData.CopyableDataList();
			ActorData.Read(reader);
			SynchedProperties = new Protocol.Types.PropertySyncData();
			SynchedProperties.Read(reader);
			Tick = new Protocol.Types.PlayerInputTick();
			Tick.Read(reader);
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			TargetRuntimeID.Write(writer);
			ActorData.Write(writer);
			SynchedProperties.Write(writer);
			Tick.Write(writer);
		}
	}
}
