// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// see SimpleEventPacket
	/// </summary>
	public class SetCommandsEnabledPacket : IPacket
	{
		public int PacketId => 59;

		public bool CommandsEnabled { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			CommandsEnabled = reader.ReadByte() != 0;
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteByte(CommandsEnabled ? (byte)1 : (byte)0);
		}
	}
}
