// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class SetDisplayObjectivePacket : IPacket
	{
		public int PacketId => 107;

		public string DisplaySlotName { get; set; }
		public string ObjectiveName { get; set; }
		public string ObjectiveDisplayName { get; set; }
		public string CriteriaName { get; set; }
		public int SortOrder { get; set; } 

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			DisplaySlotName = reader.ReadLengthPrefixedString();
			ObjectiveName = reader.ReadLengthPrefixedString();
			ObjectiveDisplayName = reader.ReadLengthPrefixedString();
			CriteriaName = reader.ReadLengthPrefixedString();
			SortOrder = VarInt.ReadInt32(reader); 
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteLengthPrefixedString(DisplaySlotName);
			writer.WriteLengthPrefixedString(ObjectiveName);
			writer.WriteLengthPrefixedString(ObjectiveDisplayName);
			writer.WriteLengthPrefixedString(CriteriaName);
			writer.WriteVarInt32(SortOrder); 
		}
	}
}
