// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Used for when a client changes difficulty through the menu or when the server changes the difficulty.
	/// </summary>
	public class SetDifficultyPacket : IPacket
	{
		public int PacketId => 60;

		public uint Difficulty { get; set; } 

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			Difficulty = VarInt.ReadUInt32(reader); 
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteVarUInt32(Difficulty); 
		}
	}
}
