// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// This packet will toggle the HUD visibility.
	/// </summary>
	public class SetHudPacket : IPacket
	{
		public int PacketId => 308;

		public List<Protocol.HudElement> HudElement { get; set; } = new List<Protocol.HudElement>(); 
		public Protocol.HudVisibility HudVisible { get; set; } 

		public void Read(MemoryStreamReader reader)
		{
			HudElement = reader.ReadSlice(() => (Protocol.HudElement)VarInt.ReadInt32(reader));
			HudVisible = (Protocol.HudVisibility)VarInt.ReadInt32(reader); 
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteSlice(HudElement, v => writer.WriteVarInt32((int)v));
			writer.WriteVarInt32((int)HudVisible); 
		}
	}
}

namespace Protocol
{
	public enum HudElement
	{
		PaperDoll = 0,
		Armor = 1,
		ToolTips = 2,
		TouchControls = 3,
		Crosshair = 4,
		HotBar = 5,
		Health = 6,
		ProgressBar = 7,
		Hunger = 8,
		AirBubbles = 9,
		HorseHealth = 10,
		StatusEffects = 11,
		ItemText = 12,
	}
}

namespace Protocol
{
	public enum HudVisibility
	{
		Hide = 0,
		Reset = 1,
	}
}
