// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class SetHealthPacket : IPacket
	{
		public int PacketId => 42;

		public int Health { get; set; } 

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			Health = VarInt.ReadInt32(reader); 
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteVarInt32(Health); 
		}
	}
}
