// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class SetLastHurtByPacket : IPacket
	{
		public int PacketId => 96;

		public Protocol.ActorType LastHurtBy { get; set; } 

		public void Read(MemoryStreamReader reader)
		{
			LastHurtBy = (Protocol.ActorType)VarInt.ReadInt32(reader); 
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteVarInt32((int)LastHurtBy); 
		}
	}
}
