// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class SetPlayerInventoryOptionsPacket : IPacket
	{
		public int PacketId => 307;

		public Protocol.Types.InventoryOptions InventoryOptions { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			InventoryOptions = new Protocol.Types.InventoryOptions();
			InventoryOptions.Read(reader);
		}

		public void Write(MemoryStreamWriter writer)
		{
			InventoryOptions.Write(writer);
		}
	}
}
