// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// The client handles the change of the UI element (the gametype dropdown, although this can be avoided by changing via command or on the server), then the client sends a packet to the server, then the server changes the player's gametype and sends a packet back (UpdatePlayerGameTypePacket) to make sure it matches on the client.
	/// </summary>
	public class SetPlayerGameTypePacket : IPacket
	{
		public int PacketId => 62;

		public Protocol.GameType PlayerGameType { get; set; } 

		public void Read(MemoryStreamReader reader)
		{
			PlayerGameType = (Protocol.GameType)VarInt.ReadInt32(reader); 
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteVarInt32((int)PlayerGameType); 
		}
	}
}
