// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// see RespawnPacket
	/// </summary>
	public class SetSpawnPositionPacket : IPacket
	{
		public override int PacketId => 43;

		public Protocol.SpawnPositionType SpawnPositionType { get; set; } 
		public Protocol.Types.BlockPos BlockPosition { get; set; }
		public Protocol.Types.DimensionType DimensionType { get; set; }
		public Protocol.Types.BlockPos SpawnBlockPos { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			SpawnPositionType = (Protocol.SpawnPositionType)VarInt.ReadInt32(reader); 
			BlockPosition = new Protocol.Types.BlockPos();
			BlockPosition.Read(reader);
			DimensionType = new Protocol.Types.DimensionType();
			DimensionType.Read(reader);
			SpawnBlockPos = new Protocol.Types.BlockPos();
			SpawnBlockPos.Read(reader);
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteVarInt32((int)SpawnPositionType); 
			BlockPosition.Write(writer);
			DimensionType.Write(writer);
			SpawnBlockPos.Write(writer);
		}
	}
}
