// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Sets the scoreboard which is used for 3rd party content.
	/// </summary>
	public class SetScorePacket : IPacket
	{
		public int PacketId => 108;

		public List<OneOf<Protocol.Types.RemoveScore, Protocol.Types.ChangePlayerScore, Protocol.Types.ChangeEntityScore, Protocol.Types.ChangeFakePlayerScore>> ScoreInfo { get; set; } = new List<OneOf<Protocol.Types.RemoveScore, Protocol.Types.ChangePlayerScore, Protocol.Types.ChangeEntityScore, Protocol.Types.ChangeFakePlayerScore>>();
		public Protocol.ScorePacketEntryAction Action { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			var _ScoreInfoCount = VarInt.ReadUInt32(reader); 
			ScoreInfo.Clear();
			for (int i = 0; i < _ScoreInfoCount; i++)
			{
				OneOf<Protocol.Types.RemoveScore, Protocol.Types.ChangePlayerScore, Protocol.Types.ChangeEntityScore, Protocol.Types.ChangeFakePlayerScore> _ScoreInfoItem = default;
				var _ScoreInfoDisc = (byte)reader.ReadByte();
				switch (_ScoreInfoDisc)
				{
					case 0:
					{
					var _ScoreInfoCase0 = new Protocol.Types.RemoveScore();
					_ScoreInfoCase0.Read(reader);
					_ScoreInfoItem = OneOf<Protocol.Types.RemoveScore, Protocol.Types.ChangePlayerScore, Protocol.Types.ChangeEntityScore, Protocol.Types.ChangeFakePlayerScore>.FromT0(_ScoreInfoCase0);
					break;
					}
					case 1:
					{
					var _ScoreInfoCase1 = new Protocol.Types.ChangePlayerScore();
					_ScoreInfoCase1.Read(reader);
					_ScoreInfoItem = OneOf<Protocol.Types.RemoveScore, Protocol.Types.ChangePlayerScore, Protocol.Types.ChangeEntityScore, Protocol.Types.ChangeFakePlayerScore>.FromT1(_ScoreInfoCase1);
					break;
					}
					case 2:
					{
					var _ScoreInfoCase2 = new Protocol.Types.ChangeEntityScore();
					_ScoreInfoCase2.Read(reader);
					_ScoreInfoItem = OneOf<Protocol.Types.RemoveScore, Protocol.Types.ChangePlayerScore, Protocol.Types.ChangeEntityScore, Protocol.Types.ChangeFakePlayerScore>.FromT2(_ScoreInfoCase2);
					break;
					}
					case 3:
					{
					var _ScoreInfoCase3 = new Protocol.Types.ChangeFakePlayerScore();
					_ScoreInfoCase3.Read(reader);
					_ScoreInfoItem = OneOf<Protocol.Types.RemoveScore, Protocol.Types.ChangePlayerScore, Protocol.Types.ChangeEntityScore, Protocol.Types.ChangeFakePlayerScore>.FromT3(_ScoreInfoCase3);
					break;
					}
					default:
						throw new InvalidDataException("Unknown ScoreInfo discriminant: " + _ScoreInfoDisc);
				}
				ScoreInfo.Add(_ScoreInfoItem);
			}
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteVarUInt32((uint)ScoreInfo.Count); 
			foreach (var _ScoreInfoItem in ScoreInfo)
			{
				writer.WriteByte((byte)_ScoreInfoItem.Index);
				switch (_ScoreInfoItem.Index)
				{
					case 0:
					{
					_ScoreInfoItem.AsT0.Write(writer);
					break;
					}
					case 1:
					{
					_ScoreInfoItem.AsT1.Write(writer);
					break;
					}
					case 2:
					{
					_ScoreInfoItem.AsT2.Write(writer);
					break;
					}
					case 3:
					{
					_ScoreInfoItem.AsT3.Write(writer);
					break;
					}
					default:
						throw new InvalidDataException("Invalid ScoreInfo OneOf index: " + _ScoreInfoItem.Index);
				}
			}
		}
	}
}
