// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Every so often (and at login) the server sends the current time to the client, and additionally the client can set the server time through 2 commands: DayLockCommand and TimeCommand
	/// </summary>
	public class SetTimePacket : IPacket
	{
		public override int PacketId => 10;

		public int Time { get; set; } 

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			Time = VarInt.ReadInt32(reader); 
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteVarInt32(Time); 
		}
	}
}
