// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// There are 2 commands associated with it: title and titleraw.
	/// 	Both of which have functionality to change fade in/out time for titles, sub titles, and action bar text.
	/// 	titleraw is using json to format so it will be bigger (i don't have an example)
	/// </summary>
	public class SetTitlePacket : IPacket
	{
		public int PacketId => 88;

		public Protocol.SetTitlePacketPayload.TitleType TitleType { get; set; } 
		public string TitleText { get; set; }
		public int FadeInTime { get; set; } 
		public int StayTime { get; set; } 
		public int FadeOutTime { get; set; } 
		public string Xuid { get; set; }
		public string PlatformOnlineId { get; set; }
		public string FilteredTitleMessage { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			TitleType = (Protocol.SetTitlePacketPayload.TitleType)VarInt.ReadInt32(reader); 
			TitleText = reader.ReadLengthPrefixedString();
			FadeInTime = VarInt.ReadInt32(reader); 
			StayTime = VarInt.ReadInt32(reader); 
			FadeOutTime = VarInt.ReadInt32(reader); 
			Xuid = reader.ReadLengthPrefixedString();
			PlatformOnlineId = reader.ReadLengthPrefixedString();
			FilteredTitleMessage = reader.ReadLengthPrefixedString();
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteVarInt32((int)TitleType); 
			writer.WriteLengthPrefixedString(TitleText);
			writer.WriteVarInt32(FadeInTime); 
			writer.WriteVarInt32(StayTime); 
			writer.WriteVarInt32(FadeOutTime); 
			writer.WriteLengthPrefixedString(Xuid);
			writer.WriteLengthPrefixedString(PlatformOnlineId);
			writer.WriteLengthPrefixedString(FilteredTitleMessage);
		}
	}
}

namespace Protocol.SetTitlePacketPayload
{
	public enum TitleType
	{
		Clear = 0,
		Reset = 1,
		Title = 2,
		Subtitle = 3,
		Actionbar = 4,
		Times = 5,
		TitleTextObject = 6,
		SubtitleTextObject = 7,
		ActionbarTextObject = 8,
	}
}
