// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Used when the player changes the world settings like doDayNightCycle or WeatherCycle via the world settings menu
	/// </summary>
	public class SettingsCommandPacket : IPacket
	{
		public int PacketId => 140;

		public string Command { get; set; }
		public bool SuppressOutput { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			Command = reader.ReadLengthPrefixedString();
			SuppressOutput = reader.ReadByte() != 0;
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(Command);
			writer.WriteByte(SuppressOutput ? (byte)1 : (byte)0);
		}
	}
}
