// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// The server can redirect the user to a 3rd party server page, to a marketplace offer description page, or to a dressing room page containing desired offer.
	/// </summary>
	public class ShowStoreOfferPacket : IPacket
	{
		public override int PacketId => 91;

		public Protocol.Types.mce.UUID OfferId { get; set; }
		public Protocol.ShowStoreOfferRedirectType RedirectType { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			OfferId = new Protocol.Types.mce.UUID();
			OfferId.Read(reader);
			RedirectType = (Protocol.ShowStoreOfferRedirectType)reader.ReadByte();
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			OfferId.Write(writer);
			writer.WriteByte((byte)RedirectType);
		}
	}
}

namespace Protocol
{
	public enum ShowStoreOfferRedirectType
	{
		MarketplaceOffer = 0,
		DressingRoomOffer = 1,
		ThirdPartyServerPage = 2,
	}
}
