// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// This is fired from the client to the server and a SetCommandsEnabledPacket is sent back when enabling commands.
	/// </summary>
	public class SimpleEventPacket : IPacket
	{
		public int PacketId => 64;

		public Protocol.SimpleEventPacketPayload.Subtype Type_ { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			Type_ = (Protocol.SimpleEventPacketPayload.Subtype)reader.ReadUInt16();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteUInt16((ushort)Type_);
		}
	}
}

namespace Protocol.SimpleEventPacketPayload
{
	public enum Subtype
	{
		UninitializedSubtype = 0,
		EnableCommands = 1,
		DisableCommands = 2,
		UnlockWorldTemplateSettings = 3,
	}
}
