// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// This is not used for much anymore, only the Particle command (spawn particle by name at a location) and for ScriptServerSpawnParticleAttachedToActor and ScriptServerSpawnParticleInWorldEvent.
	/// </summary>
	public class SpawnParticleEffectPacket : IPacket
	{
		public override int PacketId => 118;

		public byte DimensionId { get; set; }
		public Protocol.Types.ActorUniqueID ActorId { get; set; }
		public Protocol.Types.Vec3 Position { get; set; }
		public string EffectName { get; set; }
		public Optional<string> MolangVariables { get; set; } = new Optional<string>();

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			DimensionId = (byte)reader.ReadByte();
			ActorId = new Protocol.Types.ActorUniqueID();
			ActorId.Read(reader);
			Position = new Protocol.Types.Vec3();
			Position.Read(reader);
			EffectName = reader.ReadLengthPrefixedString();
			if (reader.ReadByte() != 0)
			{
				MolangVariables = new Optional<string>(reader.ReadLengthPrefixedString());
			}
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteByte(DimensionId);
			ActorId.Write(writer);
			Position.Write(writer);
			writer.WriteLengthPrefixedString(EffectName);
			if (MolangVariables != null && MolangVariables.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteLengthPrefixedString(MolangVariables.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
		}
	}
}
