// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Note: This can be seen as "ContainerWantSetSlotPacket" when sent from client to server. Currently, the client handles side-effects relating to it's own inventory, regardless of the success of the operation.
	/// </summary>
	public class SpawnExperienceOrbPacket : IPacket
	{
		public int PacketId => 66;

		public Protocol.Types.Vec3 Position { get; set; }
		public int XPValue { get; set; } 

		public void Read(MemoryStreamReader reader)
		{
			Position = new Protocol.Types.Vec3();
			Position.Read(reader);
			XPValue = VarInt.ReadInt32(reader); 
		}

		public void Write(MemoryStreamWriter writer)
		{
			Position.Write(writer);
			writer.WriteVarInt32(XPValue); 
		}
	}
}
