// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// The player movement mode is also specified here, see ServerAuthMovementMode enum documentation for details on the modes.
	/// </summary>
	public class StartGamePacket : IPacket
	{
		public int PacketId => 11;

		public Protocol.Types.ActorUniqueID EntityID { get; set; }
		public Protocol.Types.ActorRuntimeID RuntimeID { get; set; }
		public Protocol.GameType GameType { get; set; } 
		public Protocol.Types.Vec3 Position { get; set; }
		public Protocol.Types.Vec2 Rotation { get; set; }
		public Protocol.Types.LevelSettings Settings { get; set; }
		public string LevelID { get; set; }
		public string LevelName { get; set; }
		public string TemplateContentIdentity { get; set; }
		public bool IsTrial { get; set; }
		public Protocol.Types.SyncedPlayerMovementSettings MovementSettings { get; set; }
		public ulong LevelCurrentTime { get; set; }
		public int EnchantmentSeed { get; set; } 
		public List<Protocol.Types.ServerBlockProperty> BlockProperties { get; set; } = new List<Protocol.Types.ServerBlockProperty>();
		public string MultiplayerCorrelationId { get; set; }
		public bool EnableItemStackNetManager { get; set; }
		public string ServerVersion { get; set; }
		public Protocol.Types.CompoundTag PlayerPropertyData { get; set; }
		public ulong ServerBlockTypeRegistryChecksum { get; set; }
		public Protocol.Types.mce.UUID WorldTemplateID { get; set; }
		public bool ServerEnabledClientSideGeneration { get; set; }
		public bool BlockNetworkIdsAreHashes { get; set; }
		public Protocol.Types.NetworkPermissions NetworkPermissions { get; set; }
		public Optional<Protocol.Types.ServerConfiguration.ServerConfigurationJoinInfo> ServerConfigurationJoinInfo { get; set; } = new Optional<Protocol.Types.ServerConfiguration.ServerConfigurationJoinInfo>();
		public Protocol.Types.Social.Events.ServerTelemetryData ServerTelemetryData { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			EntityID = new Protocol.Types.ActorUniqueID();
			EntityID.Read(reader);
			RuntimeID = new Protocol.Types.ActorRuntimeID();
			RuntimeID.Read(reader);
			GameType = (Protocol.GameType)VarInt.ReadInt32(reader); 
			Position = new Protocol.Types.Vec3();
			Position.Read(reader);
			Rotation = new Protocol.Types.Vec2();
			Rotation.Read(reader);
			Settings = new Protocol.Types.LevelSettings();
			Settings.Read(reader);
			LevelID = reader.ReadLengthPrefixedString();
			LevelName = reader.ReadLengthPrefixedString();
			TemplateContentIdentity = reader.ReadLengthPrefixedString();
			IsTrial = reader.ReadByte() != 0;
			MovementSettings = new Protocol.Types.SyncedPlayerMovementSettings();
			MovementSettings.Read(reader);
			LevelCurrentTime = reader.ReadUInt64();
			EnchantmentSeed = VarInt.ReadInt32(reader); 
			BlockProperties = reader.ReadSlice(() => { var _Item = new Protocol.Types.ServerBlockProperty(); _Item.Read(reader); return _Item; });
			MultiplayerCorrelationId = reader.ReadLengthPrefixedString();
			EnableItemStackNetManager = reader.ReadByte() != 0;
			ServerVersion = reader.ReadLengthPrefixedString();
			PlayerPropertyData = new Protocol.Types.CompoundTag();
			PlayerPropertyData.Read(reader);
			ServerBlockTypeRegistryChecksum = reader.ReadUInt64();
			WorldTemplateID = new Protocol.Types.mce.UUID();
			WorldTemplateID.Read(reader);
			ServerEnabledClientSideGeneration = reader.ReadByte() != 0;
			BlockNetworkIdsAreHashes = reader.ReadByte() != 0;
			NetworkPermissions = new Protocol.Types.NetworkPermissions();
			NetworkPermissions.Read(reader);
			if (reader.ReadByte() != 0)
			{
				var _ServerConfigurationJoinInfoValue = new Protocol.Types.ServerConfiguration.ServerConfigurationJoinInfo();
				_ServerConfigurationJoinInfoValue.Read(reader);
				ServerConfigurationJoinInfo = new Optional<Protocol.Types.ServerConfiguration.ServerConfigurationJoinInfo>(_ServerConfigurationJoinInfoValue);
			}
			ServerTelemetryData = new Protocol.Types.Social.Events.ServerTelemetryData();
			ServerTelemetryData.Read(reader);
		}

		public void Write(MemoryStreamWriter writer)
		{
			EntityID.Write(writer);
			RuntimeID.Write(writer);
			writer.WriteVarInt32((int)GameType); 
			Position.Write(writer);
			Rotation.Write(writer);
			Settings.Write(writer);
			writer.WriteLengthPrefixedString(LevelID);
			writer.WriteLengthPrefixedString(LevelName);
			writer.WriteLengthPrefixedString(TemplateContentIdentity);
			writer.WriteByte(IsTrial ? (byte)1 : (byte)0);
			MovementSettings.Write(writer);
			writer.WriteUInt64(LevelCurrentTime);
			writer.WriteVarInt32(EnchantmentSeed); 
			writer.WriteSlice(BlockProperties, v => v.Write(writer));
			writer.WriteLengthPrefixedString(MultiplayerCorrelationId);
			writer.WriteByte(EnableItemStackNetManager ? (byte)1 : (byte)0);
			writer.WriteLengthPrefixedString(ServerVersion);
			PlayerPropertyData.Write(writer);
			writer.WriteUInt64(ServerBlockTypeRegistryChecksum);
			WorldTemplateID.Write(writer);
			writer.WriteByte(ServerEnabledClientSideGeneration ? (byte)1 : (byte)0);
			writer.WriteByte(BlockNetworkIdsAreHashes ? (byte)1 : (byte)0);
			NetworkPermissions.Write(writer);
			if (ServerConfigurationJoinInfo != null && ServerConfigurationJoinInfo.HasValue)
			{
				writer.WriteByte(1);
				ServerConfigurationJoinInfo.Value.Write(writer);
			}
			else
			{
				writer.WriteByte(0);
			}
			ServerTelemetryData.Write(writer);
		}
	}
}

namespace Protocol.Types
{
	public class NetworkPermissions
	{
		public bool ServerAuthSoundEnabled { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			ServerAuthSoundEnabled = reader.ReadByte() != 0;
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteByte(ServerAuthSoundEnabled ? (byte)1 : (byte)0);
		}
	}
}
