// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class StopSoundPacket : IPacket
	{
		public int PacketId => 87;

		public string SoundName { get; set; }
		public bool StopAllSounds { get; set; }
		public bool StopMusicLegacy { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			SoundName = reader.ReadLengthPrefixedString();
			StopAllSounds = reader.ReadByte() != 0;
			StopMusicLegacy = reader.ReadByte() != 0;
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(SoundName);
			writer.WriteByte(StopAllSounds ? (byte)1 : (byte)0);
			writer.WriteByte(StopMusicLegacy ? (byte)1 : (byte)0);
		}
	}
}
