// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// This is used to kick off the process of loading and returning a structure in a Tag from the server back to the client. Currently this functionality is completely disabled and does nothing.
	/// </summary>
	public class StructureTemplateDataRequestPacket : IPacket
	{
		public int PacketId => 132;

		public string StructureName { get; set; }
		public Protocol.Types.BlockPos StructurePosition { get; set; }
		public Protocol.Types.StructureSettings StructureSettings { get; set; }
		public Protocol.StructureTemplateRequestOperation RequestedOperation { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			StructureName = reader.ReadLengthPrefixedString();
			StructurePosition = new Protocol.Types.BlockPos();
			StructurePosition.Read(reader);
			StructureSettings = new Protocol.Types.StructureSettings();
			StructureSettings.Read(reader);
			RequestedOperation = (Protocol.StructureTemplateRequestOperation)reader.ReadByte();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(StructureName);
			StructurePosition.Write(writer);
			StructureSettings.Write(writer);
			writer.WriteByte((byte)RequestedOperation);
		}
	}
}
