// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// The client sends a packet to the server, from there the structure is built and then put into a Tag where it is sent back to the client, from there you can view the structure in the Structure Block Screen. Currently this functionality is completely disabled and does nothing. Used to reply to a request for structure information.
	/// </summary>
	public class StructureTemplateDataResponsePacket : IPacket
	{
		public int PacketId => 133;

		public string StructureName { get; set; }
		public Protocol.Types.CompoundTag StructureSNBT { get; set; }
		public Protocol.StructureTemplateResponseType ResponseType { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			StructureName = reader.ReadLengthPrefixedString();
			StructureSNBT = new Protocol.Types.CompoundTag();
			StructureSNBT.Read(reader);
			ResponseType = (Protocol.StructureTemplateResponseType)reader.ReadByte();
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteLengthPrefixedString(StructureName);
			StructureSNBT.Write(writer);
			writer.WriteByte((byte)ResponseType);
		}
	}
}
