// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Sent from the server when a client joins to initialize all world clocks for the client and periodically to all clients to keep them in sync.
	/// 	It is also sent to all clients when a world clock's paused state changes or when time markers are added or removed.
	/// </summary>
	public class SyncWorldClocksPacket : IPacket
	{
		public override int PacketId => 344;

		public OneOf<Protocol.Types.SyncWorldClocksPacketPayload.SyncStateData, Protocol.Types.SyncWorldClocksPacketPayload.InitializeRegistryData, Protocol.Types.SyncWorldClocksPacketPayload.AddTimeMarkerData, Protocol.Types.SyncWorldClocksPacketPayload.RemoveTimeMarkerData> Data { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			var _DataDisc = VarInt.ReadUInt32(reader); 
			switch (_DataDisc)
			{
				case 0:
				{
				var _DataCase0 = new Protocol.Types.SyncWorldClocksPacketPayload.SyncStateData();
				_DataCase0.Read(reader);
				Data = OneOf<Protocol.Types.SyncWorldClocksPacketPayload.SyncStateData, Protocol.Types.SyncWorldClocksPacketPayload.InitializeRegistryData, Protocol.Types.SyncWorldClocksPacketPayload.AddTimeMarkerData, Protocol.Types.SyncWorldClocksPacketPayload.RemoveTimeMarkerData>.FromT0(_DataCase0);
				break;
				}
				case 1:
				{
				var _DataCase1 = new Protocol.Types.SyncWorldClocksPacketPayload.InitializeRegistryData();
				_DataCase1.Read(reader);
				Data = OneOf<Protocol.Types.SyncWorldClocksPacketPayload.SyncStateData, Protocol.Types.SyncWorldClocksPacketPayload.InitializeRegistryData, Protocol.Types.SyncWorldClocksPacketPayload.AddTimeMarkerData, Protocol.Types.SyncWorldClocksPacketPayload.RemoveTimeMarkerData>.FromT1(_DataCase1);
				break;
				}
				case 2:
				{
				var _DataCase2 = new Protocol.Types.SyncWorldClocksPacketPayload.AddTimeMarkerData();
				_DataCase2.Read(reader);
				Data = OneOf<Protocol.Types.SyncWorldClocksPacketPayload.SyncStateData, Protocol.Types.SyncWorldClocksPacketPayload.InitializeRegistryData, Protocol.Types.SyncWorldClocksPacketPayload.AddTimeMarkerData, Protocol.Types.SyncWorldClocksPacketPayload.RemoveTimeMarkerData>.FromT2(_DataCase2);
				break;
				}
				case 3:
				{
				var _DataCase3 = new Protocol.Types.SyncWorldClocksPacketPayload.RemoveTimeMarkerData();
				_DataCase3.Read(reader);
				Data = OneOf<Protocol.Types.SyncWorldClocksPacketPayload.SyncStateData, Protocol.Types.SyncWorldClocksPacketPayload.InitializeRegistryData, Protocol.Types.SyncWorldClocksPacketPayload.AddTimeMarkerData, Protocol.Types.SyncWorldClocksPacketPayload.RemoveTimeMarkerData>.FromT3(_DataCase3);
				break;
				}
				default:
					throw new InvalidDataException("Unknown Data discriminant: " + _DataDisc);
			}
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			switch (Data.Index)
			{
				case 0:
				{
				writer.WriteVarUInt32((uint)Data.Index); 
				Data.AsT0.Write(writer);
				break;
				}
				case 1:
				{
				writer.WriteVarUInt32((uint)Data.Index); 
				Data.AsT1.Write(writer);
				break;
				}
				case 2:
				{
				writer.WriteVarUInt32((uint)Data.Index); 
				Data.AsT2.Write(writer);
				break;
				}
				case 3:
				{
				writer.WriteVarUInt32((uint)Data.Index); 
				Data.AsT3.Write(writer);
				break;
				}
				default:
					throw new InvalidDataException("Invalid Data OneOf index: " + Data.Index);
			}
		}
	}
}
