// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Intended to one day replace SynchedActorData.
	/// </summary>
	public class SyncActorPropertyPacket : IPacket
	{
		public int PacketId => 165;

		public Protocol.Types.CompoundTag PropertyData { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			PropertyData = new Protocol.Types.CompoundTag();
			PropertyData.Read(reader);
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			PropertyData.Write(writer);
		}
	}
}
