// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class TickingAreasLoadStatusPacket : IPacket
	{
		public int PacketId => 179;

		public bool WaitingForPreload { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			WaitingForPreload = reader.ReadByte() != 0;
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteByte(WaitingForPreload ? (byte)1 : (byte)0);
		}
	}
}
