// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class ToastRequestPacket : IPacket
	{
		public int PacketId => 186;

		public string Title { get; set; }
		public string Content { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			Title = reader.ReadLengthPrefixedString();
			Content = reader.ReadLengthPrefixedString();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(Title);
			writer.WriteLengthPrefixedString(Content);
		}
	}
}
