// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class TransferPacket : IPacket
	{
		public int PacketId => 85;

		public string ServerAddress { get; set; }
		public ushort ServerPort { get; set; }
		public bool ReloadWorld { get; set; }
		public Optional<Protocol.Types.ServerConfiguration.GatheringsConfigurationJoinInfo> GatheringsConfiguration { get; set; } = new Optional<Protocol.Types.ServerConfiguration.GatheringsConfigurationJoinInfo>();

		public void Read(MemoryStreamReader reader)
		{
			ServerAddress = reader.ReadLengthPrefixedString();
			ServerPort = reader.ReadUInt16();
			ReloadWorld = reader.ReadByte() != 0;
			if (reader.ReadByte() != 0)
			{
				var _GatheringsConfigurationValue = new Protocol.Types.ServerConfiguration.GatheringsConfigurationJoinInfo();
				_GatheringsConfigurationValue.Read(reader);
				GatheringsConfiguration = new Optional<Protocol.Types.ServerConfiguration.GatheringsConfigurationJoinInfo>(_GatheringsConfigurationValue);
			}
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(ServerAddress);
			writer.WriteUInt16(ServerPort);
			writer.WriteByte(ReloadWorld ? (byte)1 : (byte)0);
			if (GatheringsConfiguration != null && GatheringsConfiguration.HasValue)
			{
				writer.WriteByte(1);
				GatheringsConfiguration.Value.Write(writer);
			}
			else
			{
				writer.WriteByte(0);
			}
		}
	}
}
