// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// - mTrimPatterns: vector of TrimPattern
	/// - mTrimMaterials: vector of TrimMaterial
	/// </summary>
	public class TrimDataPacket : IPacket
	{
		public int PacketId => 302;

		public List<Protocol.Types.TrimPattern> TrimPatternList { get; set; } = new List<Protocol.Types.TrimPattern>();
		public List<Protocol.Types.TrimMaterial> TrimMaterialList { get; set; } = new List<Protocol.Types.TrimMaterial>();

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			TrimPatternList = reader.ReadSlice(() => { var _Item = new Protocol.Types.TrimPattern(); _Item.Read(reader); return _Item; });
			TrimMaterialList = reader.ReadSlice(() => { var _Item = new Protocol.Types.TrimMaterial(); _Item.Read(reader); return _Item; });
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			writer.WriteSlice(TrimPatternList, v => v.Write(writer));
			writer.WriteSlice(TrimMaterialList, v => v.Write(writer));
		}
	}
}
