// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// This happens often. Luckily, the packets are small.
	/// </summary>
	public class UpdateBlockPacket : IPacket
	{
		public int PacketId => 21;

		public Protocol.Types.BlockPos BlockPosition { get; set; }
		public uint BlockRuntimeID { get; set; } 
		public uint Flags { get; set; } 
		public uint Layer { get; set; } 

		public void Read(MemoryStreamReader reader)
		{
			BlockPosition = new Protocol.Types.BlockPos();
			BlockPosition.Read(reader);
			BlockRuntimeID = VarInt.ReadUInt32(reader); 
			Flags = VarInt.ReadUInt32(reader); 
			Layer = VarInt.ReadUInt32(reader); 
		}

		public void Write(MemoryStreamWriter writer)
		{
			BlockPosition.Write(writer);
			writer.WriteVarUInt32(BlockRuntimeID); 
			writer.WriteVarUInt32(Flags); 
			writer.WriteVarUInt32(Layer); 
		}
	}
}
