// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class UpdatePlayerGameTypePacket : IPacket
	{
		public int PacketId => 151;

		public Protocol.GameType PlayerGameType { get; set; } 
		public Protocol.Types.ActorUniqueID TargetPlayer { get; set; }
		public Protocol.Types.PlayerInputTick Tick { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			PlayerGameType = (Protocol.GameType)VarInt.ReadInt32(reader); 
			TargetPlayer = new Protocol.Types.ActorUniqueID();
			TargetPlayer.Read(reader);
			Tick = new Protocol.Types.PlayerInputTick();
			Tick.Read(reader);
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteVarInt32((int)PlayerGameType); 
			TargetPlayer.Write(writer);
			Tick.Write(writer);
		}
	}
}
