// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Occasionally updating player attributes (buffs/debuffs, health, etc)
	/// </summary>
	public class UpdateAttributesPacket : IPacket
	{
		public override int PacketId => 29;

		public Protocol.Types.ActorRuntimeID TargetRuntimeID { get; set; }
		public List<Protocol.Types.AttributeData> AttributeList { get; set; } = new List<Protocol.Types.AttributeData>();
		public Protocol.Types.PlayerInputTick Tick { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			TargetRuntimeID = new Protocol.Types.ActorRuntimeID();
			TargetRuntimeID.Read(reader);
			AttributeList = reader.ReadSlice(() => { var _Item = new Protocol.Types.AttributeData(); _Item.Read(reader); return _Item; });
			Tick = new Protocol.Types.PlayerInputTick();
			Tick.Read(reader);
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			TargetRuntimeID.Write(writer);
			writer.WriteSlice(AttributeList, v => v.Write(writer));
			Tick.Write(writer);
		}
	}
}
