// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// This allows someone to sync between server and client tags and enums on mobs or on the level.
	/// </summary>
	public class UpdateSoftEnumPacket : IPacket
	{
		public int PacketId => 114;

		public string EnumName { get; set; }
		public List<string> Values { get; set; } = new List<string>();
		public Protocol.SoftEnumUpdateType UpdateType { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			EnumName = reader.ReadLengthPrefixedString();
			Values = reader.ReadSlice(() => reader.ReadLengthPrefixedString());
			UpdateType = (Protocol.SoftEnumUpdateType)reader.ReadByte();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(EnumName);
			writer.WriteSlice(Values, v => writer.WriteLengthPrefixedString(v));
			writer.WriteByte((byte)UpdateType);
		}
	}
}
