// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class UpdateTradePacket : IPacket
	{
		public int PacketId => 80;

		public byte ContainerId { get; set; }
		public byte Type_ { get; set; }
		public int Size { get; set; } 
		public int TraderTier { get; set; } 
		public Protocol.Types.ActorUniqueID EntityUniqueId { get; set; }
		public Protocol.Types.ActorUniqueID LastTradingPlayer { get; set; }
		public string DisplayName { get; set; }
		public bool UseNewTradeScreen { get; set; }
		public bool UsingEconomyTrade { get; set; }
		public Protocol.Types.CompoundTag Data { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			ContainerId = (byte)reader.ReadByte();
			Type_ = (byte)reader.ReadByte();
			Size = VarInt.ReadInt32(reader); 
			TraderTier = VarInt.ReadInt32(reader); 
			EntityUniqueId = new Protocol.Types.ActorUniqueID();
			EntityUniqueId.Read(reader);
			LastTradingPlayer = new Protocol.Types.ActorUniqueID();
			LastTradingPlayer.Read(reader);
			DisplayName = reader.ReadLengthPrefixedString();
			UseNewTradeScreen = reader.ReadByte() != 0;
			UsingEconomyTrade = reader.ReadByte() != 0;
			Data = new Protocol.Types.CompoundTag();
			Data.Read(reader);
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteByte(ContainerId);
			writer.WriteByte(Type_);
			writer.WriteVarInt32(Size); 
			writer.WriteVarInt32(TraderTier); 
			EntityUniqueId.Write(writer);
			LastTradingPlayer.Write(writer);
			writer.WriteLengthPrefixedString(DisplayName);
			writer.WriteByte(UseNewTradeScreen ? (byte)1 : (byte)0);
			writer.WriteByte(UsingEconomyTrade ? (byte)1 : (byte)0);
			Data.Write(writer);
		}
	}
}
