// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Sent by the server to update the state of AdventureSettings. Replaces the AdventureSettingsPacket for updating AdventureSettings from server to client.
	/// </summary>
	public class UpdateAdventureSettingsPacket : IPacket
	{
		public override int PacketId => 188;

		public Protocol.Types.AdventureSettings AdventureSettings { get; set; }

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			AdventureSettings = new Protocol.Types.AdventureSettings();
			AdventureSettings.Read(reader);
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			AdventureSettings.Write(writer);
		}
	}
}
