// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// The values in this packet are originally synced through the Connection Request and then updated via this packet.
	/// </summary>
	public class UpdateClientOptionsPacket : IPacket
	{
		public override int PacketId => 323;

		public Optional<Protocol.GraphicsMode> GraphicsModeChange { get; set; } = new Optional<Protocol.GraphicsMode>();
		public Optional<bool> FilterProfanityChange { get; set; } = new Optional<bool>();

		public override void Read(MemoryStreamReader reader)
		{
			base.Read(reader);
			if (reader.ReadByte() != 0)
			{
				GraphicsModeChange = new Optional<Protocol.GraphicsMode>((Protocol.GraphicsMode)reader.ReadByte());
			}
			if (reader.ReadByte() != 0)
			{
				FilterProfanityChange = new Optional<bool>(reader.ReadByte() != 0);
			}
		}

		public override void Write(MemoryStreamWriter writer)
		{
			base.Write(writer);
			if (GraphicsModeChange != null && GraphicsModeChange.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteByte((byte)GraphicsModeChange.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (FilterProfanityChange != null && FilterProfanityChange.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteByte(FilterProfanityChange.Value ? (byte)1 : (byte)0);
			}
			else
			{
				writer.WriteByte(0);
			}
		}
	}
}

namespace Protocol
{
	public enum GraphicsMode
	{
		Simple = 0,
		Fancy = 1,
		Advanced = 2,
		RayTraced = 3,
	}
}
