// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	/// <summary>
	/// Used to update the players input permissions. Sends the full permission set and the server position of the player at the time the permission was modified.
	/// </summary>
	public class UpdateClientInputLocksPacket : IPacket
	{
		public int PacketId => 196;

		public uint InputLockComponentData { get; set; } 

		public void Read(MemoryStreamReader reader)
		{
			InputLockComponentData = VarInt.ReadUInt32(reader); 
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteVarUInt32(InputLockComponentData); 
		}
	}
}
