// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public class UpdateAbilitiesPacket : IPacket
	{
		public int PacketId => 187;

		public Protocol.Types.SerializedAbilitiesData Data { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			Data = new Protocol.Types.SerializedAbilitiesData();
			Data.Read(reader);
		}

		public void Write(MemoryStreamWriter writer)
		{
			Data.Write(writer);
		}
	}
}
