// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.BookEditAction
{
	public class AddPage
	{
		public int PageIndex { get; set; } 
		public string PageText { get; set; }
		public string PhotoName { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			PageIndex = VarInt.ReadInt32(reader); 
			PageText = reader.ReadLengthPrefixedString();
			PhotoName = reader.ReadLengthPrefixedString();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteVarInt32(PageIndex); 
			writer.WriteLengthPrefixedString(PageText);
			writer.WriteLengthPrefixedString(PhotoName);
		}
	}
}
