// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.BookEditAction
{
	public class SwapPages
	{
		public int PageIndex { get; set; } 
		public int SwapWithIndex { get; set; } 

		public void Read(MemoryStreamReader reader)
		{
			PageIndex = VarInt.ReadInt32(reader); 
			SwapWithIndex = VarInt.ReadInt32(reader); 
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteVarInt32(PageIndex); 
			writer.WriteVarInt32(SwapWithIndex); 
		}
	}
}
