// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class IntArrayTag
	{
		public int[] Data { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			int _Size = VarInt.ReadSInt32(reader); 
			Data = new int[_Size];
			for (int i = 0; i < _Size; i++)
			{
				Data[i] = VarInt.ReadSInt32(reader); 
			}
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteSInt32(Data.Length); 
			foreach (int value in Data)
			{
				writer.WriteSInt32(value); 
			}
		}
	}
}
