// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class ListTag
	{
		public TagType Type { get; set; }
		public List<TagVariant> Value { get; set; } = new List<TagVariant>();

		public void Read(MemoryStreamReader reader)
		{
			Type = (TagType)reader.ReadByte();
			int _Size = VarInt.ReadSInt32(reader); 
			Value.Clear();
			for (int i = 0; i < _Size; i++)
			{
				var _Item = new TagVariant();
				_Item.Read(Type, reader);
				Value.Add(_Item);
			}
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteByte((byte)Type);
			writer.WriteSInt32(Value.Count); 
			foreach (var item in Value)
			{
				item.Write(writer);
			}
		}
	}
}
