// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.PlayerUpdateEntityOverridesPacketPayload
{
	public class RemoveOverride
	{
		public Protocol.UpdateType Type_ { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			Type_ = EnumCodec.FromString<Protocol.UpdateType>(reader.ReadLengthPrefixedString());
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(EnumCodec.ToString(Type_));
		}
	}
}
