// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>

namespace Protocol
{
	public enum PackType
	{
		Invalid = 0,
		Addon = 1,
		Cached = 2,
		CopyProtected = 3,
		Behavior = 4,
		PersonaPiece = 5,
		Resources = 6,
		Skins = 7,
		WorldTemplate = 8,
	}
}
