// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class PackIdVersion
	{
		public mce.UUID PackUUID { get; set; }
		public SemVersion PackVersion { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			PackUUID = new mce.UUID();
			PackUUID.Read(reader);
			PackVersion = new SemVersion();
			PackVersion.Read(reader);
		}

		public void Write(MemoryStreamWriter writer)
		{
			PackUUID.Write(writer);
			PackVersion.Write(writer);
		}
	}
}
