// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class PackInstanceId
	{
		public string PackID { get; set; }
		public string Version { get; set; }
		public string SubPackName { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			PackID = reader.ReadLengthPrefixedString();
			Version = reader.ReadLengthPrefixedString();
			SubPackName = reader.ReadLengthPrefixedString();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(PackID);
			writer.WriteLengthPrefixedString(Version);
			writer.WriteLengthPrefixedString(SubPackName);
		}
	}
}
