// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.LegacyTelemetryEventPacketPayload
{
	public class SlashCommand
	{
		public int SuccessCount { get; set; } 
		public int ErrorCount { get; set; } 
		public string CommandName { get; set; }
		public string ErrorList { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			SuccessCount = VarInt.ReadInt32(reader); 
			ErrorCount = VarInt.ReadInt32(reader); 
			CommandName = reader.ReadLengthPrefixedString();
			ErrorList = reader.ReadLengthPrefixedString();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteVarInt32(SuccessCount); 
			writer.WriteVarInt32(ErrorCount); 
			writer.WriteLengthPrefixedString(CommandName);
			writer.WriteLengthPrefixedString(ErrorList);
		}
	}
}
