// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.LegacyTelemetryEventPacketPayload
{
	public class POICauldronUsed
	{
		public Protocol.MinecraftEventing.POIBlockInteractionType BlockInteractionType { get; set; }
		public int ItemId { get; set; } 

		public void Read(MemoryStreamReader reader)
		{
			BlockInteractionType = (Protocol.MinecraftEventing.POIBlockInteractionType)reader.ReadByte();
			ItemId = VarInt.ReadInt32(reader); 
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteByte((byte)BlockInteractionType);
			writer.WriteVarInt32(ItemId); 
		}
	}
}
