// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.LegacyTelemetryEventPacketPayload
{
	public class MobBorn
	{
		public int BornBabyEntityType { get; set; } 
		public int BornBabyEntityVariant { get; set; } 
		public byte BornBabyColor { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			BornBabyEntityType = VarInt.ReadInt32(reader); 
			BornBabyEntityVariant = VarInt.ReadInt32(reader); 
			BornBabyColor = (byte)reader.ReadByte();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteVarInt32(BornBabyEntityType); 
			writer.WriteVarInt32(BornBabyEntityVariant); 
			writer.WriteByte(BornBabyColor);
		}
	}
}
