// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.LegacyTelemetryEventPacketPayload
{
	public class ItemUsed
	{
		public short ItemId { get; set; }
		public int ItemAux { get; set; }
		public int UseMethod { get; set; }
		public int Count { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			ItemId = reader.ReadInt16();
			ItemAux = reader.ReadInt32();
			UseMethod = reader.ReadInt32();
			Count = reader.ReadInt32();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteInt16(ItemId);
			writer.WriteInt32(ItemAux);
			writer.WriteInt32(UseMethod);
			writer.WriteInt32(Count);
		}
	}
}
