// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.LegacyTelemetryEventPacketPayload
{
	public class BossKilled
	{
		public long BossActorID { get; set; } 
		public int PartySize { get; set; } 
		public int BossType { get; set; } 

		public void Read(MemoryStreamReader reader)
		{
			BossActorID = VarInt.ReadInt64(reader); 
			PartySize = VarInt.ReadInt32(reader); 
			BossType = VarInt.ReadInt32(reader); 
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteVarInt64(BossActorID); 
			writer.WriteVarInt32(PartySize); 
			writer.WriteVarInt32(BossType); 
		}
	}
}
