// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.LegacyTelemetryEventPacketPayload
{
	public class CauldronUsed
	{
		public uint ContentsColor { get; set; } 
		public int ContentsType { get; set; } 
		public int FillLevel { get; set; } 

		public void Read(MemoryStreamReader reader)
		{
			ContentsColor = VarInt.ReadUInt32(reader); 
			ContentsType = VarInt.ReadInt32(reader); 
			FillLevel = VarInt.ReadInt32(reader); 
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteVarUInt32(ContentsColor); 
			writer.WriteVarInt32(ContentsType); 
			writer.WriteVarInt32(FillLevel); 
		}
	}
}
