// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.LegacyTelemetryEventPacketPayload
{
	public class Achievement
	{
		public Protocol.MinecraftEventing.AchievementIds AchievementID { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			AchievementID = (Protocol.MinecraftEventing.AchievementIds)reader.ReadByte();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteByte((byte)AchievementID);
		}
	}
}
