// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.CommandBlockUpdatePacketPayload
{
	public class BlockCommandData
	{
		public BlockPos BlockPosition { get; set; }
		public uint CommandBlockMode { get; set; } 
		public bool RedstoneMode { get; set; }
		public bool IsConditional { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			BlockPosition = new BlockPos();
			BlockPosition.Read(reader);
			CommandBlockMode = VarInt.ReadUInt32(reader); 
			RedstoneMode = reader.ReadByte() != 0;
			IsConditional = reader.ReadByte() != 0;
		}

		public void Write(MemoryStreamWriter writer)
		{
			BlockPosition.Write(writer);
			writer.WriteVarUInt32(CommandBlockMode); 
			writer.WriteByte(RedstoneMode ? (byte)1 : (byte)0);
			writer.WriteByte(IsConditional ? (byte)1 : (byte)0);
		}
	}
}
