// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>

namespace Protocol
{
	public enum CommandPermissionLevel
	{
		Any = 0,
		GameDirectors = 1,
		Admin = 2,
		Host = 3,
		Owner = 4,
		Internal = 5,
	}
}
