// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class CommandOriginData
	{
		public Protocol.CommandOriginType Type_ { get; set; }
		public mce.UUID UUID { get; set; }
		public string RequestId { get; set; }
		public long PlayerId { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			Type_ = EnumCodec.FromString<Protocol.CommandOriginType>(reader.ReadLengthPrefixedString());
			UUID = new mce.UUID();
			UUID.Read(reader);
			RequestId = reader.ReadLengthPrefixedString();
			PlayerId = reader.ReadInt64();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(EnumCodec.ToString(Type_));
			UUID.Write(writer);
			writer.WriteLengthPrefixedString(RequestId);
			writer.WriteInt64(PlayerId);
		}
	}
}
