// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>

namespace Protocol
{
	public enum CommandOutputType
	{
		None = 0,
		LastOutput = 1,
		Silent = 2,
		AllOutput = 3,
		DataSet = 4,
	}
}
