// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class CommandOutputMessage
	{
		public string MessageID { get; set; }
		public bool Successful { get; set; }
		public List<string> Parameters { get; set; } = new List<string>();

		public void Read(MemoryStreamReader reader)
		{
			MessageID = reader.ReadLengthPrefixedString();
			Successful = reader.ReadByte() != 0;
			Parameters = reader.ReadSlice(() => reader.ReadLengthPrefixedString());
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(MessageID);
			writer.WriteByte(Successful ? (byte)1 : (byte)0);
			writer.WriteSlice(Parameters, v => writer.WriteLengthPrefixedString(v));
		}
	}
}
