// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class MaterialReducerDataEntry
	{
		public int FromItemKey { get; set; } 
		public List<MaterialReducerEntryOutput> ItemIdsAndCounts { get; set; } = new List<MaterialReducerEntryOutput>();

		public void Read(MemoryStreamReader reader)
		{
			FromItemKey = VarInt.ReadInt32(reader); 
			ItemIdsAndCounts = reader.ReadSlice(() => { var _Item = new MaterialReducerEntryOutput(); _Item.Read(reader); return _Item; });
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteVarInt32(FromItemKey); 
			writer.WriteSlice(ItemIdsAndCounts, v => v.Write(writer));
		}
	}
}
