// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class MultiRecipePayload
	{
		public mce.UUID MultiRecipeUUID { get; set; }
		public TypedServerNetId_struct_RecipeNetIdTag NetId { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			MultiRecipeUUID = new mce.UUID();
			MultiRecipeUUID.Read(reader);
			NetId = new TypedServerNetId_struct_RecipeNetIdTag();
			NetId.Read(reader);
		}

		public void Write(MemoryStreamWriter writer)
		{
			MultiRecipeUUID.Write(writer);
			NetId.Write(writer);
		}
	}
}
