// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>

namespace Protocol
{
	public enum MultiplayerSettingsPacketType
	{
		EnableMultiplayer = 0,
		DisableMultiplayer = 1,
		RefreshJoincode = 2,
	}
}
