// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class PotionMixDataEntry
	{
		public int FromPotionId { get; set; } 
		public int FromItemAux { get; set; } 
		public int ReagentItemId { get; set; } 
		public int ReagentItemAux { get; set; } 
		public int ToPotionId { get; set; } 
		public int ToItemAux { get; set; } 

		public void Read(MemoryStreamReader reader)
		{
			FromPotionId = VarInt.ReadInt32(reader); 
			FromItemAux = VarInt.ReadInt32(reader); 
			ReagentItemId = VarInt.ReadInt32(reader); 
			ReagentItemAux = VarInt.ReadInt32(reader); 
			ToPotionId = VarInt.ReadInt32(reader); 
			ToItemAux = VarInt.ReadInt32(reader); 
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteVarInt32(FromPotionId); 
			writer.WriteVarInt32(FromItemAux); 
			writer.WriteVarInt32(ReagentItemId); 
			writer.WriteVarInt32(ReagentItemAux); 
			writer.WriteVarInt32(ToPotionId); 
			writer.WriteVarInt32(ToItemAux); 
		}
	}
}
