// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.RecipeUnlockingRequirement
{
	public class RecipeUnlockingRequirement
	{
		public Protocol.RecipeUnlockingRequirement.UnlockingContext UnlockingContext { get; set; } 
		public Optional<List<RecipeIngredient.RecipeIngredient>> UnlockingIngredients { get; set; } = new Optional<List<RecipeIngredient.RecipeIngredient>>();

		public void Read(MemoryStreamReader reader)
		{
			UnlockingContext = (Protocol.RecipeUnlockingRequirement.UnlockingContext)VarInt.ReadInt32(reader); 
			if (reader.ReadByte() != 0)
			{
				UnlockingIngredients = new Optional<List<RecipeIngredient.RecipeIngredient>>(reader.ReadSlice(() => { var _Item = new RecipeIngredient.RecipeIngredient(); _Item.Read(reader); return _Item; }));
			}
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteVarInt32((int)UnlockingContext); 
			if (UnlockingIngredients != null && UnlockingIngredients.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteSlice(UnlockingIngredients.Value, v => v.Write(writer));
			}
			else
			{
				writer.WriteByte(0);
			}
		}
	}
}
