// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>

namespace Protocol.RecipeUnlockingRequirement
{
	public enum UnlockingContext
	{
		None = 0,
		AlwaysUnlocked = 1,
		PlayerInWater = 2,
		PlayerHasManyItems = 3,
	}
}
