// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class ShapedRecipePayload
	{
		public string RecipeId { get; set; }
		public int Width { get; set; } 
		public int Height { get; set; } 
		public List<RecipeIngredient.RecipeIngredient> Ingredients { get; set; } = new List<RecipeIngredient.RecipeIngredient>();
		public List<NetworkItemInstanceDescriptor.NetworkItemInstanceDescriptor> Results { get; set; } = new List<NetworkItemInstanceDescriptor.NetworkItemInstanceDescriptor>();
		public mce.UUID UUID { get; set; }
		public string Tag { get; set; }
		public int Priority { get; set; } 
		public bool AssumeSymmetry { get; set; }
		public Optional<RecipeUnlockingRequirement.RecipeUnlockingRequirement> UnlockingRequirement { get; set; } = new Optional<RecipeUnlockingRequirement.RecipeUnlockingRequirement>();
		public TypedServerNetId_struct_RecipeNetIdTag NetId { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			RecipeId = reader.ReadLengthPrefixedString();
			Width = VarInt.ReadInt32(reader); 
			Height = VarInt.ReadInt32(reader); 
			Ingredients = reader.ReadSlice(() => { var _Item = new RecipeIngredient.RecipeIngredient(); _Item.Read(reader); return _Item; });
			Results = reader.ReadSlice(() => { var _Item = new NetworkItemInstanceDescriptor.NetworkItemInstanceDescriptor(); _Item.Read(reader); return _Item; });
			UUID = new mce.UUID();
			UUID.Read(reader);
			Tag = reader.ReadLengthPrefixedString();
			Priority = VarInt.ReadInt32(reader); 
			AssumeSymmetry = reader.ReadByte() != 0;
			if (reader.ReadByte() != 0)
			{
				var _UnlockingRequirementValue = new RecipeUnlockingRequirement.RecipeUnlockingRequirement();
				_UnlockingRequirementValue.Read(reader);
				UnlockingRequirement = new Optional<RecipeUnlockingRequirement.RecipeUnlockingRequirement>(_UnlockingRequirementValue);
			}
			NetId = new TypedServerNetId_struct_RecipeNetIdTag();
			NetId.Read(reader);
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(RecipeId);
			writer.WriteVarInt32(Width); 
			writer.WriteVarInt32(Height); 
			writer.WriteSlice(Ingredients, v => v.Write(writer));
			writer.WriteSlice(Results, v => v.Write(writer));
			UUID.Write(writer);
			writer.WriteLengthPrefixedString(Tag);
			writer.WriteVarInt32(Priority); 
			writer.WriteByte(AssumeSymmetry ? (byte)1 : (byte)0);
			if (UnlockingRequirement != null && UnlockingRequirement.HasValue)
			{
				writer.WriteByte(1);
				UnlockingRequirement.Value.Write(writer);
			}
			else
			{
				writer.WriteByte(0);
			}
			NetId.Write(writer);
		}
	}
}
