// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class TrimMaterial
	{
		public string MaterialId { get; set; }
		public string Color { get; set; }
		public string ItemName { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			MaterialId = reader.ReadLengthPrefixedString();
			Color = reader.ReadLengthPrefixedString();
			ItemName = reader.ReadLengthPrefixedString();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(MaterialId);
			writer.WriteLengthPrefixedString(Color);
			writer.WriteLengthPrefixedString(ItemName);
		}
	}
}
