// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>

namespace Protocol.UnlockedRecipesPacketPayload
{
	public enum PacketType
	{
		Empty = 0,
		InitiallyUnlockedRecipes = 1,
		NewlyUnlockedRecipes = 2,
		RemoveUnlockedRecipes = 3,
		RemoveAllUnlockedRecipes = 4,
	}
}
