// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class ActorUniqueID
	{
		public long Value { get; set; } 

		public void Read(MemoryStreamReader reader)
		{
			Value = VarInt.ReadSInt64(reader); 
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteSInt64(Value); 
		}
	}
}
