// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>

namespace Protocol
{
	public enum ActorEvent
	{
		NONE = 0,
		JUMP = 1,
		HURT = 2,
		DEATH = 3,
		/// <summary>START_ATTACKING</summary>
		STARTATTACKING = 4,
		/// <summary>STOP_ATTACKING</summary>
		STOPATTACKING = 5,
		/// <summary>TAMING_FAILED</summary>
		TAMINGFAILED = 6,
		/// <summary>TAMING_SUCCEEDED</summary>
		TAMINGSUCCEEDED = 7,
		/// <summary>SHAKE_WETNESS</summary>
		SHAKEWETNESS = 8,
		/// <summary>EAT_GRASS</summary>
		EATGRASS = 10,
		/// <summary>FISHHOOK_BUBBLE</summary>
		FISHHOOKBUBBLE = 11,
		/// <summary>FISHHOOK_FISHPOS</summary>
		FISHHOOKFISHPOS = 12,
		/// <summary>FISHHOOK_HOOKTIME</summary>
		FISHHOOKHOOKTIME = 13,
		/// <summary>FISHHOOK_TEASE</summary>
		FISHHOOKTEASE = 14,
		/// <summary>SQUID_FLEEING</summary>
		SQUIDFLEEING = 15,
		/// <summary>ZOMBIE_CONVERTING</summary>
		ZOMBIECONVERTING = 16,
		/// <summary>PLAY_AMBIENT</summary>
		PLAYAMBIENT = 17,
		/// <summary>SPAWN_ALIVE</summary>
		SPAWNALIVE = 18,
		/// <summary>START_OFFER_FLOWER</summary>
		STARTOFFERFLOWER = 19,
		/// <summary>STOP_OFFER_FLOWER</summary>
		STOPOFFERFLOWER = 20,
		/// <summary>LOVE_HEARTS</summary>
		LOVEHEARTS = 21,
		/// <summary>VILLAGER_ANGRY</summary>
		VILLAGERANGRY = 22,
		/// <summary>VILLAGER_HAPPY</summary>
		VILLAGERHAPPY = 23,
		/// <summary>WITCH_HAT_MAGIC</summary>
		WITCHHATMAGIC = 24,
		/// <summary>FIREWORKS_EXPLODE</summary>
		FIREWORKSEXPLODE = 25,
		/// <summary>IN_LOVE_HEARTS</summary>
		INLOVEHEARTS = 26,
		/// <summary>SILVERFISH_MERGE_ANIM</summary>
		SILVERFISHMERGEANIM = 27,
		/// <summary>GUARDIAN_ATTACK_SOUND</summary>
		GUARDIANATTACKSOUND = 28,
		/// <summary>DRINK_POTION</summary>
		DRINKPOTION = 29,
		/// <summary>THROW_POTION</summary>
		THROWPOTION = 30,
		/// <summary>PRIME_TNTCART</summary>
		PRIMETNTCART = 31,
		/// <summary>PRIME_CREEPER</summary>
		PRIMECREEPER = 32,
		/// <summary>AIR_SUPPLY</summary>
		AIRSUPPLY = 33,
		/// <summary>DEPRECATED_ADD_PLAYER_LEVELS</summary>
		DEPRECATEDADDPLAYERLEVELS = 34,
		/// <summary>GUARDIAN_MINING_FATIGUE</summary>
		GUARDIANMININGFATIGUE = 35,
		/// <summary>AGENT_SWING_ARM</summary>
		AGENTSWINGARM = 36,
		/// <summary>DRAGON_START_DEATH_ANIM</summary>
		DRAGONSTARTDEATHANIM = 37,
		/// <summary>GROUND_DUST</summary>
		GROUNDDUST = 38,
		SHAKE = 39,
		FEED = 57,
		/// <summary>BABY_AGE</summary>
		BABYAGE = 60,
		/// <summary>INSTANT_DEATH</summary>
		INSTANTDEATH = 61,
		/// <summary>NOTIFY_TRADE</summary>
		NOTIFYTRADE = 62,
		/// <summary>LEASH_DESTROYED</summary>
		LEASHDESTROYED = 63,
		/// <summary>CARAVAN_UPDATED</summary>
		CARAVANUPDATED = 64,
		/// <summary>TALISMAN_ACTIVATE</summary>
		TALISMANACTIVATE = 65,
		/// <summary>DEPRECATED_UPDATE_STRUCTURE_FEATURE</summary>
		DEPRECATEDUPDATESTRUCTUREFEATURE = 66,
		/// <summary>PLAYER_SPAWNED_MOB</summary>
		PLAYERSPAWNEDMOB = 67,
		PUKE = 68,
		/// <summary>UPDATE_STACK_SIZE</summary>
		UPDATESTACKSIZE = 69,
		/// <summary>START_SWIMMING</summary>
		STARTSWIMMING = 70,
		/// <summary>BALLOON_POP</summary>
		BALLOONPOP = 71,
		/// <summary>TREASURE_HUNT</summary>
		TREASUREHUNT = 72,
		/// <summary>SUMMON_AGENT</summary>
		SUMMONAGENT = 73,
		/// <summary>FINISHED_CHARGING_ITEM</summary>
		FINISHEDCHARGINGITEM = 74,
		/// <summary>ACTOR_GROW_UP</summary>
		ACTORGROWUP = 76,
		/// <summary>VIBRATION_DETECTED</summary>
		VIBRATIONDETECTED = 77,
		/// <summary>DRINK_MILK</summary>
		DRINKMILK = 78,
		/// <summary>SHAKE_WETNESS_STOP</summary>
		SHAKEWETNESSSTOP = 79,
		/// <summary>KINETIC_DAMAGE_DEALT</summary>
		KINETICDAMAGEDEALT = 80,
		/// <summary>HURT_WITHOUT_RECEIVING_DAMAGE</summary>
		HURTWITHOUTRECEIVINGDAMAGE = 81,
	}
}
