// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class ActorDataFlagComponent
	{
		public Bitset ActorFlagBitsetData { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			var _Bitset = new Bitset(130);
			int _BitIndex = 0;
			while (true)
			{
				byte _Value = (byte)reader.ReadByte();
				for (int i = 0; i < 7; i++)
				{
					int _Bit = _BitIndex + i;
					if (_Bit < _Bitset.Size && (_Value & (1 << i)) != 0)
					{
						_Bitset.Set(_Bit);
					}
				}
				if ((_Value & 0x80) == 0)
				{
					break;
				}
				_BitIndex += 7;
			}
			ActorFlagBitsetData = _Bitset;
		}

		public void Write(MemoryStreamWriter writer)
		{
			if (ActorFlagBitsetData.IntValue.IsZero)
			{
				writer.WriteByte(0);
				return;
			}

			int _BitIndex = 0;
			while (true)
			{
				byte _Value = 0;
				bool _HasHigherBits = false;
				for (int i = 0; i < 7; i++)
				{
					int _Bit = _BitIndex + i;
					if (_Bit < ActorFlagBitsetData.Size && ActorFlagBitsetData.Load(_Bit))
					{
						_Value |= (byte)(1 << i);
					}
				}
				for (int i = _BitIndex + 7; i < ActorFlagBitsetData.Size; i++)
				{
					if (ActorFlagBitsetData.Load(i))
					{
						_HasHigherBits = true;
						break;
					}
				}
				if (_HasHigherBits)
				{
					_Value |= 0x80;
				}
				writer.WriteByte(_Value);
				if (!_HasHigherBits)
				{
					break;
				}
				_BitIndex += 7;
			}
		}
	}
}
