// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class ActorDataBoundingBoxComponent
	{
		public float[] ActorDataBoundingBox { get; set; } = new float[3];

		public void Read(MemoryStreamReader reader)
		{
			ActorDataBoundingBox = reader.ReadSliceOfLen(3, () => reader.ReadSingle());
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteSliceOfLen(ActorDataBoundingBox, 3, v => writer.WriteSingle(v));
		}
	}
}
