// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>

namespace Protocol.MobEffectPacketPayload
{
	public enum Event
	{
		Invalid = 0,
		Add = 1,
		Update = 2,
		Remove = 3,
	}
}
