// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class PropertySyncData
	{
		public List<PropertySyncData.PropertySyncIntEntry> IntEntriesList { get; set; } = new List<PropertySyncData.PropertySyncIntEntry>();
		public List<PropertySyncData.PropertySyncFloatEntry> FloatEntriesList { get; set; } = new List<PropertySyncData.PropertySyncFloatEntry>();

		public void Read(MemoryStreamReader reader)
		{
			IntEntriesList = reader.ReadSlice(() => { var _Item = new PropertySyncData.PropertySyncIntEntry(); _Item.Read(reader); return _Item; });
			FloatEntriesList = reader.ReadSlice(() => { var _Item = new PropertySyncData.PropertySyncFloatEntry(); _Item.Read(reader); return _Item; });
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteSlice(IntEntriesList, v => v.Write(writer));
			writer.WriteSlice(FloatEntriesList, v => v.Write(writer));
		}

	public class PropertySyncFloatEntry
	{
		public uint PropertyIndex { get; set; } 
		public float Data { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			PropertyIndex = VarInt.ReadUInt32(reader); 
			Data = reader.ReadSingle();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteVarUInt32(PropertyIndex); 
			writer.WriteSingle(Data);
		}
	}

	public class PropertySyncIntEntry
	{
		public uint PropertyIndex { get; set; } 
		public int Data { get; set; } 

		public void Read(MemoryStreamReader reader)
		{
			PropertyIndex = VarInt.ReadUInt32(reader); 
			Data = VarInt.ReadInt32(reader); 
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteVarUInt32(PropertyIndex); 
			writer.WriteVarInt32(Data); 
		}
	}
	}
}
