// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.ResourcePackClientResponsePacketPayload
{
	public class ResourcePackStackFinished
	{
		public Protocol.ResourcePackResponse ResponseType { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			ResponseType = EnumCodec.FromString<Protocol.ResourcePackResponse>(reader.ReadLengthPrefixedString());
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(EnumCodec.ToString(ResponseType));
		}
	}
}
