// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.SubChunkPacketPayload
{
	public class HeightmapData
	{
		public Protocol.SubChunkPacketPayload.HeightMapDataType HeightMapType { get; set; }
		public Optional<sbyte[]> SubchunkHeightMap { get; set; } = new Optional<sbyte[]>();
		public Protocol.SubChunkPacketPayload.HeightMapDataType RenderHeightMapType { get; set; }
		public Optional<sbyte[]> SubchunkRenderHeightMap { get; set; } = new Optional<sbyte[]>();

		public void Read(MemoryStreamReader reader)
		{
			HeightMapType = (Protocol.SubChunkPacketPayload.HeightMapDataType)reader.ReadByte();
			if (reader.ReadByte() != 0)
			{
				SubchunkHeightMap = new Optional<sbyte[]>(reader.ReadSliceOfLen(256, () => (sbyte)reader.ReadByte()));
			}
			RenderHeightMapType = (Protocol.SubChunkPacketPayload.HeightMapDataType)reader.ReadByte();
			if (reader.ReadByte() != 0)
			{
				SubchunkRenderHeightMap = new Optional<sbyte[]>(reader.ReadSliceOfLen(256, () => (sbyte)reader.ReadByte()));
			}
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteByte((byte)HeightMapType);
			if (SubchunkHeightMap != null && SubchunkHeightMap.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteSliceOfLen(SubchunkHeightMap.Value, 256, v => writer.WriteByte((byte)v));
			}
			else
			{
				writer.WriteByte(0);
			}
			writer.WriteByte((byte)RenderHeightMapType);
			if (SubchunkRenderHeightMap != null && SubchunkRenderHeightMap.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteSliceOfLen(SubchunkRenderHeightMap.Value, 256, v => writer.WriteByte((byte)v));
			}
			else
			{
				writer.WriteByte(0);
			}
		}
	}
}
