// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.SubChunkPacketPayload
{
	public class HeightmapData
	{
		public Protocol.SubChunkPacketPayload.HeightMapDataType HeightMapType { get; set; }
		public Optional<sbyte[]> SubchunkHeightMap { get; set; } = new Optional<sbyte[]>();
		public Protocol.SubChunkPacketPayload.HeightMapDataType RenderHeightMapType { get; set; }
		public Optional<sbyte[]> SubchunkRenderHeightMap { get; set; } = new Optional<sbyte[]>();

		public void Read(MemoryStreamReader reader)
		{
			HeightMapType = (Protocol.SubChunkPacketPayload.HeightMapDataType)reader.ReadByte();
			if (reader.ReadByte() != 0)
			{
				var _SubchunkHeightMapValue = new List<sbyte>(256);
				for (int _i = 0; _i < 16; _i++)
				{
					_SubchunkHeightMapValue.AddRange(reader.ReadSlice(() => (sbyte)reader.ReadByte()));
				}
				SubchunkHeightMap = new Optional<sbyte[]>(_SubchunkHeightMapValue.ToArray());
			}
			RenderHeightMapType = (Protocol.SubChunkPacketPayload.HeightMapDataType)reader.ReadByte();
			if (reader.ReadByte() != 0)
			{
				var _SubchunkRenderHeightMapValue = new List<sbyte>(256);
				for (int _i = 0; _i < 16; _i++)
				{
					_SubchunkRenderHeightMapValue.AddRange(reader.ReadSlice(() => (sbyte)reader.ReadByte()));
				}
				SubchunkRenderHeightMap = new Optional<sbyte[]>(_SubchunkRenderHeightMapValue.ToArray());
			}
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteByte((byte)HeightMapType);
			if (SubchunkHeightMap != null && SubchunkHeightMap.HasValue)
			{
				writer.WriteByte(1);
				for (int _i = 0; _i < 16; _i++)
				{
					var _chunk = new List<sbyte>(16);
					for (int _j = 0; _j < 16 && _i * 16 + _j < SubchunkHeightMap.Value.Length; _j++)
					{
						_chunk.Add(SubchunkHeightMap.Value[_i * 16 + _j]);
					}
					writer.WriteSlice(_chunk, v => writer.WriteByte((byte)v));
				}
			}
			else
			{
				writer.WriteByte(0);
			}
			writer.WriteByte((byte)RenderHeightMapType);
			if (SubchunkRenderHeightMap != null && SubchunkRenderHeightMap.HasValue)
			{
				writer.WriteByte(1);
				for (int _i = 0; _i < 16; _i++)
				{
					var _chunk = new List<sbyte>(16);
					for (int _j = 0; _j < 16 && _i * 16 + _j < SubchunkRenderHeightMap.Value.Length; _j++)
					{
						_chunk.Add(SubchunkRenderHeightMap.Value[_i * 16 + _j]);
					}
					writer.WriteSlice(_chunk, v => writer.WriteByte((byte)v));
				}
			}
			else
			{
				writer.WriteByte(0);
			}
		}
	}
}
