// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.SubChunkPacketPayload
{
	public class SubChunkPacketData
	{
		public SubChunkPosOffset SubChunkPosOffset { get; set; }
		public Protocol.SubChunkPacketPayload.SubChunkRequestResult SubChunkRequestResult { get; set; }
		public Optional<byte[]> SerializedSubChunk { get; set; } = new Optional<byte[]>();
		public HeightmapData HeightMapData { get; set; }
		public Optional<ulong> BlobId { get; set; } = new Optional<ulong>();

		public void Read(MemoryStreamReader reader)
		{
			SubChunkPosOffset = new SubChunkPosOffset();
			SubChunkPosOffset.Read(reader);
			SubChunkRequestResult = (Protocol.SubChunkPacketPayload.SubChunkRequestResult)reader.ReadByte();
			if (reader.ReadByte() != 0)
			{
				SerializedSubChunk = new Optional<byte[]>(reader.ReadLengthPrefixedBytes().ToArray());
			}
			HeightMapData = new HeightmapData();
			HeightMapData.Read(reader);
			if (reader.ReadByte() != 0)
			{
				BlobId = new Optional<ulong>(reader.ReadUInt64());
			}
		}

		public void Write(MemoryStreamWriter writer)
		{
			SubChunkPosOffset.Write(writer);
			writer.WriteByte((byte)SubChunkRequestResult);
			if (SerializedSubChunk != null && SerializedSubChunk.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteLengthPrefixedBytes(SerializedSubChunk.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
			HeightMapData.Write(writer);
			if (BlobId != null && BlobId.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteUInt64(BlobId.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
		}
	}
}
