// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>

namespace Protocol.SubChunkPacketPayload
{
	public enum HeightMapDataType
	{
		NoData = 0,
		HasData = 1,
		AllTooHigh = 2,
		AllTooLow = 3,
		AllCopied = 4,
	}
}
