// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>

namespace Protocol
{
	public enum BuildPlatform
	{
		Google = 1,
		/// <summary>iOS</summary>
		IOS = 2,
		OSX = 3,
		Amazon = 4,
		GearVR = 5,
		UWP = 7,
		Win32 = 8,
		Dedicated = 9,
		/// <summary>tvOS</summary>
		TvOS = 10,
		Sony = 11,
		Nx = 12,
		Xbox = 13,
		WindowsPhone = 14,
		Linux = 15,
		Unknown = -1,
	}
}
