// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>

namespace Protocol
{
	public enum GameType
	{
		Undefined = -1,
		Survival = 0,
		Creative = 1,
		Adventure = 2,
		Default = 5,
		Spectator = 6,
		WorldDefault = 0,
	}
}
