// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.mce
{
	public class UUID
	{
		public ulong MostSignificantBits { get; set; }
		public ulong LeastSignificantBits { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			MostSignificantBits = reader.ReadUInt64();
			LeastSignificantBits = reader.ReadUInt64();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteUInt64(MostSignificantBits);
			writer.WriteUInt64(LeastSignificantBits);
		}
	}
}
