// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class PlayerPartyInfo
	{
		public string PartyId { get; set; }
		public bool IsPartyLeader { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			PartyId = reader.ReadLengthPrefixedString();
			IsPartyLeader = reader.ReadByte() != 0;
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(PartyId);
			writer.WriteByte(IsPartyLeader ? (byte)1 : (byte)0);
		}
	}
}
