// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class SerializedAbilitiesData
	{
		public long TargetPlayerRawId { get; set; }
		public Protocol.PlayerPermissionLevel PlayerPermissions { get; set; }
		public Protocol.CommandPermissionLevel CommandPermissions { get; set; }
		public List<SerializedAbilitiesData.SerializedLayer> Layers { get; set; } = new List<SerializedAbilitiesData.SerializedLayer>();

		public void Read(MemoryStreamReader reader)
		{
			TargetPlayerRawId = reader.ReadInt64();
			PlayerPermissions = (Protocol.PlayerPermissionLevel)(sbyte)reader.ReadByte();
			CommandPermissions = (Protocol.CommandPermissionLevel)reader.ReadByte();
			Layers = reader.ReadSlice(() => { var _Item = new SerializedAbilitiesData.SerializedLayer(); _Item.Read(reader); return _Item; });
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteInt64(TargetPlayerRawId);
			writer.WriteByte((byte)PlayerPermissions);
			writer.WriteByte((byte)CommandPermissions);
			writer.WriteSlice(Layers, v => v.Write(writer));
		}

	public class SerializedLayer
	{
		public ushort SerializedLayer_ { get; set; }
		public uint AbilitiesSet { get; set; }
		public uint AbilityValues { get; set; }
		public float FlySpeed { get; set; }
		public float VerticalFlySpeed { get; set; }
		public float WalkSpeed { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			SerializedLayer_ = reader.ReadUInt16();
			AbilitiesSet = reader.ReadUInt32();
			AbilityValues = reader.ReadUInt32();
			FlySpeed = reader.ReadSingle();
			VerticalFlySpeed = reader.ReadSingle();
			WalkSpeed = reader.ReadSingle();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteUInt16(SerializedLayer_);
			writer.WriteUInt32(AbilitiesSet);
			writer.WriteUInt32(AbilityValues);
			writer.WriteSingle(FlySpeed);
			writer.WriteSingle(VerticalFlySpeed);
			writer.WriteSingle(WalkSpeed);
		}
	}
	}
}
