// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class SerializedSkinRef
	{
		public string ID { get; set; }
		public string PlayFabID { get; set; }
		public string ResourcePatch { get; set; }
		public SkinImage ImageData { get; set; }
		public List<AnimatedImageData> AnimatedImageData { get; set; } = new List<AnimatedImageData>();
		public SkinImage CapeImageData { get; set; }
		public string GeometryData { get; set; }
		public string GeometryDataMinEngineVersion { get; set; }
		public string AnimationData { get; set; }
		public string CapeID { get; set; }
		public string FullID { get; set; }
		public Protocol.SharedTypes.persona.ArmSizeType ArmSize { get; set; }
		public mce.Color SkinColor { get; set; }
		public List<SerializedPersonaPieceHandle> PersonaPieces { get; set; } = new List<SerializedPersonaPieceHandle>();
		public Dictionary<Protocol.SharedTypes.persona.PieceType, TintMapColor> PieceTintColors { get; set; } = new Dictionary<Protocol.SharedTypes.persona.PieceType, TintMapColor>();
		public bool IsPremium { get; set; }
		public bool IsPersona { get; set; }
		public bool IsPersonaCapeOnClassicSkin { get; set; }
		public bool IsPrimaryUser { get; set; }
		public bool OverridesPlayerAppearance { get; set; }
		public Protocol.TrustedSkinFlag TrustedSkinFlag { get; set; }
		public string ProfileHash { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			ID = reader.ReadLengthPrefixedString();
			PlayFabID = reader.ReadLengthPrefixedString();
			ResourcePatch = reader.ReadLengthPrefixedString();
			ImageData = new SkinImage();
			ImageData.Read(reader);
			AnimatedImageData = reader.ReadSlice(() => { var _Item = new AnimatedImageData(); _Item.Read(reader); return _Item; });
			CapeImageData = new SkinImage();
			CapeImageData.Read(reader);
			GeometryData = reader.ReadLengthPrefixedString();
			GeometryDataMinEngineVersion = reader.ReadLengthPrefixedString();
			AnimationData = reader.ReadLengthPrefixedString();
			CapeID = reader.ReadLengthPrefixedString();
			FullID = reader.ReadLengthPrefixedString();
			ArmSize = (Protocol.SharedTypes.persona.ArmSizeType)reader.ReadByte();
			SkinColor = new mce.Color();
			SkinColor.Read(reader);
			PersonaPieces = reader.ReadSlice(() => { var _Item = new SerializedPersonaPieceHandle(); _Item.Read(reader); return _Item; });
			var _PieceTintColorsCount = VarInt.ReadUInt32(reader); 
			PieceTintColors.Clear();
			for (int i = 0; i < _PieceTintColorsCount; i++)
			{
				var _PieceTintColorsKey = EnumCodec.FromString<Protocol.SharedTypes.persona.PieceType>(reader.ReadLengthPrefixedString());
				var _PieceTintColorsValue = new TintMapColor();
				_PieceTintColorsValue.Read(reader);
				PieceTintColors[_PieceTintColorsKey] = _PieceTintColorsValue;
			}
			IsPremium = reader.ReadByte() != 0;
			IsPersona = reader.ReadByte() != 0;
			IsPersonaCapeOnClassicSkin = reader.ReadByte() != 0;
			IsPrimaryUser = reader.ReadByte() != 0;
			OverridesPlayerAppearance = reader.ReadByte() != 0;
			TrustedSkinFlag = EnumCodec.FromString<Protocol.TrustedSkinFlag>(reader.ReadLengthPrefixedString());
			ProfileHash = reader.ReadLengthPrefixedString();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(ID);
			writer.WriteLengthPrefixedString(PlayFabID);
			writer.WriteLengthPrefixedString(ResourcePatch);
			ImageData.Write(writer);
			writer.WriteSlice(AnimatedImageData, v => v.Write(writer));
			CapeImageData.Write(writer);
			writer.WriteLengthPrefixedString(GeometryData);
			writer.WriteLengthPrefixedString(GeometryDataMinEngineVersion);
			writer.WriteLengthPrefixedString(AnimationData);
			writer.WriteLengthPrefixedString(CapeID);
			writer.WriteLengthPrefixedString(FullID);
			writer.WriteByte((byte)ArmSize);
			SkinColor.Write(writer);
			writer.WriteSlice(PersonaPieces, v => v.Write(writer));
			writer.WriteVarUInt32((uint)PieceTintColors.Count); 
			foreach (var _PieceTintColorsPair in PieceTintColors)
			{
				writer.WriteLengthPrefixedString(EnumCodec.ToString(_PieceTintColorsPair.Key));
				_PieceTintColorsPair.Value.Write(writer);
			}
			writer.WriteByte(IsPremium ? (byte)1 : (byte)0);
			writer.WriteByte(IsPersona ? (byte)1 : (byte)0);
			writer.WriteByte(IsPersonaCapeOnClassicSkin ? (byte)1 : (byte)0);
			writer.WriteByte(IsPrimaryUser ? (byte)1 : (byte)0);
			writer.WriteByte(OverridesPlayerAppearance ? (byte)1 : (byte)0);
			writer.WriteLengthPrefixedString(EnumCodec.ToString(TrustedSkinFlag));
			writer.WriteLengthPrefixedString(ProfileHash);
		}
	}
}
