// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class SkinImage
	{
		public uint Width { get; set; }
		public uint Height { get; set; }
		public List<byte> ImageBytes { get; set; } = new List<byte>();

		public void Read(MemoryStreamReader reader)
		{
			Width = reader.ReadUInt32();
			Height = reader.ReadUInt32();
			ImageBytes = reader.ReadSlice(() => (byte)reader.ReadByte());
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteUInt32(Width);
			writer.WriteUInt32(Height);
			writer.WriteSlice(ImageBytes, v => writer.WriteByte(v));
		}
	}
}
