// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class ArrowDataPayload
	{
		public Optional<Vec3> ArrowEndLocation { get; set; } = new Optional<Vec3>();
		public Optional<float> ArrowHeadLength { get; set; } = new Optional<float>();
		public Optional<float> ArrowHeadRadius { get; set; } = new Optional<float>();
		public Optional<byte> NumSegments { get; set; } = new Optional<byte>();

		public void Read(MemoryStreamReader reader)
		{
			if (reader.ReadByte() != 0)
			{
				var _ArrowEndLocationValue = new Vec3();
				_ArrowEndLocationValue.Read(reader);
				ArrowEndLocation = new Optional<Vec3>(_ArrowEndLocationValue);
			}
			if (reader.ReadByte() != 0)
			{
				ArrowHeadLength = new Optional<float>(reader.ReadSingle());
			}
			if (reader.ReadByte() != 0)
			{
				ArrowHeadRadius = new Optional<float>(reader.ReadSingle());
			}
			if (reader.ReadByte() != 0)
			{
				NumSegments = new Optional<byte>((byte)reader.ReadByte());
			}
		}

		public void Write(MemoryStreamWriter writer)
		{
			if (ArrowEndLocation != null && ArrowEndLocation.HasValue)
			{
				writer.WriteByte(1);
				ArrowEndLocation.Value.Write(writer);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (ArrowHeadLength != null && ArrowHeadLength.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteSingle(ArrowHeadLength.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (ArrowHeadRadius != null && ArrowHeadRadius.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteSingle(ArrowHeadRadius.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (NumSegments != null && NumSegments.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteByte(NumSegments.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
		}
	}
}
