// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.Bedrock.DDUI
{
	public class DataStoreUpdate
	{
		public string DataStoreName { get; set; }
		public string Property { get; set; }
		public string Path { get; set; }
		public OneOf<double, bool, string> Data { get; set; }
		public uint PropertyUpdateCount { get; set; }
		public uint PathUpdateCount { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			DataStoreName = reader.ReadLengthPrefixedString();
			Property = reader.ReadLengthPrefixedString();
			Path = reader.ReadLengthPrefixedString();
			var _DataDisc = VarInt.ReadUInt32(reader); 
			switch (_DataDisc)
			{
				case 0:
				{
				Data = OneOf<double, bool, string>.FromT0(reader.ReadDouble());
				break;
				}
				case 1:
				{
				Data = OneOf<double, bool, string>.FromT1(reader.ReadByte() != 0);
				break;
				}
				case 2:
				{
				Data = OneOf<double, bool, string>.FromT2(reader.ReadLengthPrefixedString());
				break;
				}
				default:
					throw new InvalidDataException("Unknown Data discriminant: " + _DataDisc);
			}
			PropertyUpdateCount = reader.ReadUInt32();
			PathUpdateCount = reader.ReadUInt32();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(DataStoreName);
			writer.WriteLengthPrefixedString(Property);
			writer.WriteLengthPrefixedString(Path);
			switch (Data.Index)
			{
				case 0:
				{
				writer.WriteVarUInt32((uint)Data.Index); 
				writer.WriteDouble(Data.AsT0);
				break;
				}
				case 1:
				{
				writer.WriteVarUInt32((uint)Data.Index); 
				writer.WriteByte(Data.AsT1 ? (byte)1 : (byte)0);
				break;
				}
				case 2:
				{
				writer.WriteVarUInt32((uint)Data.Index); 
				writer.WriteLengthPrefixedString(Data.AsT2);
				break;
				}
				default:
					throw new InvalidDataException("Invalid Data OneOf index: " + Data.Index);
			}
			writer.WriteUInt32(PropertyUpdateCount);
			writer.WriteUInt32(PathUpdateCount);
		}
	}
}
