// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.Bedrock.DDUI
{
	public class DataStoreChange
	{
		public string DataStoreName { get; set; }
		public string Property { get; set; }
		public uint UpdateCount { get; set; }
		public cereal.DynamicValue TheNewPropertyValue { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			DataStoreName = reader.ReadLengthPrefixedString();
			Property = reader.ReadLengthPrefixedString();
			UpdateCount = reader.ReadUInt32();
			TheNewPropertyValue = new cereal.DynamicValue();
			TheNewPropertyValue.Read(reader);
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(DataStoreName);
			writer.WriteLengthPrefixedString(Property);
			writer.WriteUInt32(UpdateCount);
			TheNewPropertyValue.Write(writer);
		}
	}
}
