// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.DimensionDefinitionGroup
{
	public class DimensionDefinition
	{
		public int MinimumY { get; set; } 
		public int HeightRange { get; set; } 
		public Protocol.GeneratorType GeneratorType { get; set; } 
		public DimensionType DimensionType { get; set; }
		public mce.UUID PackId { get; set; }
		public string DefaultBiome { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			MinimumY = VarInt.ReadInt32(reader); 
			HeightRange = VarInt.ReadInt32(reader); 
			GeneratorType = (Protocol.GeneratorType)VarInt.ReadInt32(reader); 
			DimensionType = new DimensionType();
			DimensionType.Read(reader);
			PackId = new mce.UUID();
			PackId.Read(reader);
			DefaultBiome = reader.ReadLengthPrefixedString();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteVarInt32(MinimumY); 
			writer.WriteVarInt32(HeightRange); 
			writer.WriteVarInt32((int)GeneratorType); 
			DimensionType.Write(writer);
			PackId.Write(writer);
			writer.WriteLengthPrefixedString(DefaultBiome);
		}
	}
}
