// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>

namespace Protocol.Editor
{
	public enum WorldType
	{
		NonEditor = 0,
		EditorProject = 1,
		EditorTestLevel = 2,
		EditorRealmsUpload = 3,
	}
}
