// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.ExperimentsAnon
{
	public class ExperimentToggle
	{
		public string Name { get; set; }
		public bool Enabled { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			Name = reader.ReadLengthPrefixedString();
			Enabled = reader.ReadByte() != 0;
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(Name);
			writer.WriteByte(Enabled ? (byte)1 : (byte)0);
		}
	}
}
