// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class ExternalLinkSettings
	{
		public string URL { get; set; }
		public string DisplayName { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			URL = reader.ReadLengthPrefixedString();
			DisplayName = reader.ReadLengthPrefixedString();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(URL);
			writer.WriteLengthPrefixedString(DisplayName);
		}
	}
}
