// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.FeatureRegistry
{
	public class FeatureBinaryJsonFormat
	{
		public string FeatureName { get; set; }
		public string BinaryJsonOutput { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			FeatureName = reader.ReadLengthPrefixedString();
			BinaryJsonOutput = reader.ReadLengthPrefixedString();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(FeatureName);
			writer.WriteLengthPrefixedString(BinaryJsonOutput);
		}
	}
}
