// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class GameRule
	{
		public string RuleName { get; set; }
		public bool RuleCanBeModified { get; set; }
		public OneOf<object, bool, int, float> RuleValue { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			RuleName = reader.ReadLengthPrefixedString();
			RuleCanBeModified = reader.ReadByte() != 0;
			var _RuleValueDisc = VarInt.ReadUInt32(reader); 
			switch (_RuleValueDisc)
			{
				case 0:
				{
				RuleValue = OneOf<object, bool, int, float>.FromT0((object)null);
				break;
				}
				case 1:
				{
				RuleValue = OneOf<object, bool, int, float>.FromT1(reader.ReadByte() != 0);
				break;
				}
				case 2:
				{
				RuleValue = OneOf<object, bool, int, float>.FromT2(reader.ReadInt32());
				break;
				}
				case 3:
				{
				RuleValue = OneOf<object, bool, int, float>.FromT3(reader.ReadSingle());
				break;
				}
				default:
					throw new InvalidDataException("Unknown RuleValue discriminant: " + _RuleValueDisc);
			}
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(RuleName);
			writer.WriteByte(RuleCanBeModified ? (byte)1 : (byte)0);
			switch (RuleValue.Index)
			{
				case 0:
				{
				writer.WriteVarUInt32((uint)RuleValue.Index); 
				break;
				}
				case 1:
				{
				writer.WriteVarUInt32((uint)RuleValue.Index); 
				writer.WriteByte(RuleValue.AsT1 ? (byte)1 : (byte)0);
				break;
				}
				case 2:
				{
				writer.WriteVarUInt32((uint)RuleValue.Index); 
				writer.WriteInt32(RuleValue.AsT2);
				break;
				}
				case 3:
				{
				writer.WriteVarUInt32((uint)RuleValue.Index); 
				writer.WriteSingle(RuleValue.AsT3);
				break;
				}
				default:
					throw new InvalidDataException("Invalid RuleValue OneOf index: " + RuleValue.Index);
			}
		}
	}
}
