// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>

namespace Protocol
{
	public enum GeneratorType
	{
		Legacy = 0,
		Overworld = 1,
		Flat = 2,
		Nether = 3,
		TheEnd = 4,
		Void = 5,
		Undefined = 6,
	}
}
