// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class PyramidDataPayload
	{
		public float Width { get; set; }
		public Optional<float> Depth { get; set; } = new Optional<float>();
		public float Height { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			Width = reader.ReadSingle();
			if (reader.ReadByte() != 0)
			{
				Depth = new Optional<float>(reader.ReadSingle());
			}
			Height = reader.ReadSingle();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteSingle(Width);
			if (Depth != null && Depth.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteSingle(Depth.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
			writer.WriteSingle(Height);
		}
	}
}
