// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class SerializedNoiseBlockSpecifier
	{
		public string Noise { get; set; }
		public float Threshold { get; set; }
		public SharedTypes.FloatRange Range { get; set; }
		public uint Block { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			Noise = reader.ReadLengthPrefixedString();
			Threshold = reader.ReadSingle();
			Range = new SharedTypes.FloatRange();
			Range.Read(reader);
			Block = reader.ReadUInt32();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(Noise);
			writer.WriteSingle(Threshold);
			Range.Write(writer);
			writer.WriteUInt32(Block);
		}
	}
}
