// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.ServerConfiguration
{
	public class ServerConfigurationJoinInfo
	{
		public Optional<GatheringsConfigurationJoinInfo> Gathering { get; set; } = new Optional<GatheringsConfigurationJoinInfo>();
		public Optional<ClientStoreEntryPointConfiguration> ClientStoreEntryPoint { get; set; } = new Optional<ClientStoreEntryPointConfiguration>();
		public Optional<PresenceConfiguration> Presence { get; set; } = new Optional<PresenceConfiguration>();

		public void Read(MemoryStreamReader reader)
		{
			if (reader.ReadByte() != 0)
			{
				var _GatheringValue = new GatheringsConfigurationJoinInfo();
				_GatheringValue.Read(reader);
				Gathering = new Optional<GatheringsConfigurationJoinInfo>(_GatheringValue);
			}
			if (reader.ReadByte() != 0)
			{
				var _ClientStoreEntryPointValue = new ClientStoreEntryPointConfiguration();
				_ClientStoreEntryPointValue.Read(reader);
				ClientStoreEntryPoint = new Optional<ClientStoreEntryPointConfiguration>(_ClientStoreEntryPointValue);
			}
			if (reader.ReadByte() != 0)
			{
				var _PresenceValue = new PresenceConfiguration();
				_PresenceValue.Read(reader);
				Presence = new Optional<PresenceConfiguration>(_PresenceValue);
			}
		}

		public void Write(MemoryStreamWriter writer)
		{
			if (Gathering != null && Gathering.HasValue)
			{
				writer.WriteByte(1);
				Gathering.Value.Write(writer);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (ClientStoreEntryPoint != null && ClientStoreEntryPoint.HasValue)
			{
				writer.WriteByte(1);
				ClientStoreEntryPoint.Value.Write(writer);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (Presence != null && Presence.HasValue)
			{
				writer.WriteByte(1);
				Presence.Value.Write(writer);
			}
			else
			{
				writer.WriteByte(0);
			}
		}
	}
}
