// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.ServerConfiguration
{
	public class GatheringsConfigurationJoinInfo
	{
		public mce.UUID ExperienceId { get; set; }
		public string ExperienceName { get; set; }
		public Optional<mce.UUID> WorldId { get; set; } = new Optional<mce.UUID>();
		public Optional<string> WorldName { get; set; } = new Optional<string>();
		public string CreatorId { get; set; }
		public Optional<mce.UUID> TargetId { get; set; } = new Optional<mce.UUID>();
		public Optional<string> ScenarioId { get; set; } = new Optional<string>();
		public Optional<string> ServerId { get; set; } = new Optional<string>();

		public void Read(MemoryStreamReader reader)
		{
			ExperienceId = new mce.UUID();
			ExperienceId.Read(reader);
			ExperienceName = reader.ReadLengthPrefixedString();
			if (reader.ReadByte() != 0)
			{
				var _WorldIdValue = new mce.UUID();
				_WorldIdValue.Read(reader);
				WorldId = new Optional<mce.UUID>(_WorldIdValue);
			}
			if (reader.ReadByte() != 0)
			{
				WorldName = new Optional<string>(reader.ReadLengthPrefixedString());
			}
			CreatorId = reader.ReadLengthPrefixedString();
			if (reader.ReadByte() != 0)
			{
				var _TargetIdValue = new mce.UUID();
				_TargetIdValue.Read(reader);
				TargetId = new Optional<mce.UUID>(_TargetIdValue);
			}
			if (reader.ReadByte() != 0)
			{
				ScenarioId = new Optional<string>(reader.ReadLengthPrefixedString());
			}
			if (reader.ReadByte() != 0)
			{
				ServerId = new Optional<string>(reader.ReadLengthPrefixedString());
			}
		}

		public void Write(MemoryStreamWriter writer)
		{
			ExperienceId.Write(writer);
			writer.WriteLengthPrefixedString(ExperienceName);
			if (WorldId != null && WorldId.HasValue)
			{
				writer.WriteByte(1);
				WorldId.Value.Write(writer);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (WorldName != null && WorldName.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteLengthPrefixedString(WorldName.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
			writer.WriteLengthPrefixedString(CreatorId);
			if (TargetId != null && TargetId.HasValue)
			{
				writer.WriteByte(1);
				TargetId.Value.Write(writer);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (ScenarioId != null && ScenarioId.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteLengthPrefixedString(ScenarioId.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (ServerId != null && ServerId.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteLengthPrefixedString(ServerId.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
		}
	}
}
