// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.ServerConfiguration
{
	public class PresenceConfiguration
	{
		public Optional<string> RichPresenceId { get; set; } = new Optional<string>();

		public void Read(MemoryStreamReader reader)
		{
			if (reader.ReadByte() != 0)
			{
				RichPresenceId = new Optional<string>(reader.ReadLengthPrefixedString());
			}
		}

		public void Write(MemoryStreamWriter writer)
		{
			if (RichPresenceId != null && RichPresenceId.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteLengthPrefixedString(RichPresenceId.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
		}
	}
}
