// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.SharedTypes.v1_26_30
{
	public class NoiseDescriptor
	{
		public string Name { get; set; }
		public int FirstOctave { get; set; }
		public List<float> Amplitudes { get; set; } = new List<float>();

		public void Read(MemoryStreamReader reader)
		{
			Name = reader.ReadLengthPrefixedString();
			FirstOctave = reader.ReadInt32();
			Amplitudes = reader.ReadSlice(() => reader.ReadSingle());
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(Name);
			writer.WriteInt32(FirstOctave);
			writer.WriteSlice(Amplitudes, v => writer.WriteSingle(v));
		}
	}
}
