// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>

namespace Protocol.SharedTypes.v1_21_10
{
	public enum RandomDistributionType
	{
		SingleValued = 0,
		Uniform = 1,
		Gaussian = 2,
		InverseGaussian = 3,
		FixedGrid = 4,
		JitteredGrid = 5,
		Triangle = 6,
	}
}
