// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>

namespace Protocol.SharedTypes
{
	public enum VillageType
	{
		Desert = 0,
		Ice = 1,
		Savanna = 2,
		Taiga = 3,
		Default = 4,
	}
}
