// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class StructureSettings
	{
		public string StructurePaletteName { get; set; }
		public bool ShouldIgnoreEntities { get; set; }
		public bool ShouldIgnoreBlocks { get; set; }
		public bool ShouldAllowNonTickingPlayerAndTickingAreaChunks { get; set; }
		public BlockPos StructureSize { get; set; }
		public BlockPos StructureOffset { get; set; }
		public ActorUniqueID LastEditPlayer { get; set; }
		public Protocol.Rotation Rotation { get; set; }
		public Protocol.Mirror Mirror { get; set; }
		public Protocol.AnimationMode AnimationMode { get; set; }
		public float AnimationSeconds { get; set; }
		public float IntegrityValue { get; set; }
		public uint IntegritySeed { get; set; }
		public Vec3 RotationPivot { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			StructurePaletteName = reader.ReadLengthPrefixedString();
			ShouldIgnoreEntities = reader.ReadByte() != 0;
			ShouldIgnoreBlocks = reader.ReadByte() != 0;
			ShouldAllowNonTickingPlayerAndTickingAreaChunks = reader.ReadByte() != 0;
			StructureSize = new BlockPos();
			StructureSize.Read(reader);
			StructureOffset = new BlockPos();
			StructureOffset.Read(reader);
			LastEditPlayer = new ActorUniqueID();
			LastEditPlayer.Read(reader);
			Rotation = (Protocol.Rotation)reader.ReadByte();
			Mirror = (Protocol.Mirror)reader.ReadByte();
			AnimationMode = (Protocol.AnimationMode)reader.ReadByte();
			AnimationSeconds = reader.ReadSingle();
			IntegrityValue = reader.ReadSingle();
			IntegritySeed = reader.ReadUInt32();
			RotationPivot = new Vec3();
			RotationPivot.Read(reader);
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(StructurePaletteName);
			writer.WriteByte(ShouldIgnoreEntities ? (byte)1 : (byte)0);
			writer.WriteByte(ShouldIgnoreBlocks ? (byte)1 : (byte)0);
			writer.WriteByte(ShouldAllowNonTickingPlayerAndTickingAreaChunks ? (byte)1 : (byte)0);
			StructureSize.Write(writer);
			StructureOffset.Write(writer);
			LastEditPlayer.Write(writer);
			writer.WriteByte((byte)Rotation);
			writer.WriteByte((byte)Mirror);
			writer.WriteByte((byte)AnimationMode);
			writer.WriteSingle(AnimationSeconds);
			writer.WriteSingle(IntegrityValue);
			writer.WriteUInt32(IntegritySeed);
			RotationPivot.Write(writer);
		}
	}
}
