// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>

namespace Protocol
{
	public enum StructureTemplateRequestOperation
	{
		None = 0,
		ExportFromSaveMode = 1,
		ExportFromLoadMode = 2,
		QuerySavedStructure = 3,
	}
}
