// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class StructureEditorData
	{
		public Bedrock.Safety.RedactableString StructureName { get; set; }
		public string DataField { get; set; }
		public bool ShouldIncludePlayers { get; set; }
		public bool ShouldShowBoundingBox { get; set; }
		public Protocol.StructureBlockType StructureBlockType { get; set; } 
		public StructureSettings StructureSettings { get; set; }
		public Protocol.StructureRedstoneSaveMode RedstoneSaveMode { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			StructureName = new Bedrock.Safety.RedactableString();
			StructureName.Read(reader);
			DataField = reader.ReadLengthPrefixedString();
			ShouldIncludePlayers = reader.ReadByte() != 0;
			ShouldShowBoundingBox = reader.ReadByte() != 0;
			StructureBlockType = (Protocol.StructureBlockType)VarInt.ReadInt32(reader); 
			StructureSettings = new StructureSettings();
			StructureSettings.Read(reader);
			RedstoneSaveMode = (Protocol.StructureRedstoneSaveMode)reader.ReadByte();
		}

		public void Write(MemoryStreamWriter writer)
		{
			StructureName.Write(writer);
			writer.WriteLengthPrefixedString(DataField);
			writer.WriteByte(ShouldIncludePlayers ? (byte)1 : (byte)0);
			writer.WriteByte(ShouldShowBoundingBox ? (byte)1 : (byte)0);
			writer.WriteVarInt32((int)StructureBlockType); 
			StructureSettings.Write(writer);
			writer.WriteByte((byte)RedstoneSaveMode);
		}
	}
}
