// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>

namespace Protocol
{
	public enum StructureBlockType
	{
		Data = 0,
		Save = 1,
		Load = 2,
		Corner = 3,
		Invalid = 4,
		Export = 5,
	}
}
