// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.SynchedActorData
{
	public class CopyableDataList
	{
		public List<DataItemEntry> Data { get; set; } = new List<DataItemEntry>();

		public void Read(MemoryStreamReader reader)
		{
			Data = reader.ReadSlice(() => { var _Item = new DataItemEntry(); _Item.Read(reader); return _Item; });
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteSlice(Data, v => v.Write(writer));
		}
	}
}
