// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class TimeMarkerData
	{
		public ulong Id { get; set; } 
		public string Name { get; set; }
		public int Time { get; set; } 
		public Optional<int> Period { get; set; } = new Optional<int>();

		public void Read(MemoryStreamReader reader)
		{
			Id = VarInt.ReadUInt64(reader); 
			Name = reader.ReadLengthPrefixedString();
			Time = VarInt.ReadInt32(reader); 
			if (reader.ReadByte() != 0)
			{
				Period = new Optional<int>(reader.ReadInt32());
			}
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteVarUInt64(Id); 
			writer.WriteLengthPrefixedString(Name);
			writer.WriteVarInt32(Time); 
			if (Period != null && Period.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteInt32(Period.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
		}
	}
}
