// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class WorldPosition
	{
		public Vec3 Position { get; set; }
		public DimensionType DimensionType { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			Position = new Vec3();
			Position.Read(reader);
			DimensionType = new DimensionType();
			DimensionType.Read(reader);
		}

		public void Write(MemoryStreamWriter writer)
		{
			Position.Write(writer);
			DimensionType.Write(writer);
		}
	}
}
