// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class WorldClockData
	{
		public ulong Id { get; set; } 
		public string Name { get; set; }
		public int Time { get; set; } 
		public bool IsPaused { get; set; }
		public List<TimeMarkerData> TimeMarkers { get; set; } = new List<TimeMarkerData>();

		public void Read(MemoryStreamReader reader)
		{
			Id = VarInt.ReadUInt64(reader); 
			Name = reader.ReadLengthPrefixedString();
			Time = VarInt.ReadInt32(reader); 
			IsPaused = reader.ReadByte() != 0;
			TimeMarkers = reader.ReadSlice(() => { var _Item = new TimeMarkerData(); _Item.Read(reader); return _Item; });
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteVarUInt64(Id); 
			writer.WriteLengthPrefixedString(Name);
			writer.WriteVarInt32(Time); 
			writer.WriteByte(IsPaused ? (byte)1 : (byte)0);
			writer.WriteSlice(TimeMarkers, v => v.Write(writer));
		}
	}
}
