// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

namespace OneOf;

public readonly struct OneOf<T0, T1, T2> : IOneOf, IEquatable<OneOf<T0, T1, T2>>
{
	private readonly T0 _value0;
	private readonly T1 _value1;
	private readonly T2 _value2;
	private readonly int _index;

	private OneOf(int index, T0 value0 = default!, T1 value1 = default!, T2 value2 = default!)
	{
		_index = index;
		_value0 = value0;
		_value1 = value1;
		_value2 = value2;
	}

	public int Index => _index;

	public object? Value => _index switch
	{
		0 => _value0,
		1 => _value1,
		2 => _value2,
		_ => throw new InvalidOperationException($"Invalid OneOf index: {_index}"),
	};

	public bool IsT0 => _index == 0;
	public bool IsT1 => _index == 1;
	public bool IsT2 => _index == 2;

	public T0 AsT0 => _index == 0
		? _value0
		: throw new InvalidOperationException($"Cannot access T0 when index is {_index}.");

	public T1 AsT1 => _index == 1
		? _value1
		: throw new InvalidOperationException($"Cannot access T1 when index is {_index}.");

	public T2 AsT2 => _index == 2
		? _value2
		: throw new InvalidOperationException($"Cannot access T2 when index is {_index}.");

	public static implicit operator OneOf<T0, T1, T2>(T0 t) => new(0, value0: t);

	public static implicit operator OneOf<T0, T1, T2>(T1 t) => new(1, value1: t);

	public static implicit operator OneOf<T0, T1, T2>(T2 t) => new(2, value2: t);

	public static OneOf<T0, T1, T2> FromT0(T0 value) => value;
	public static OneOf<T0, T1, T2> FromT1(T1 value) => value;
	public static OneOf<T0, T1, T2> FromT2(T2 value) => value;

	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public TResult Match<TResult>(
		Func<T0, TResult> f0,
		Func<T1, TResult> f1,
		Func<T2, TResult> f2)
	{
		return _index switch
		{
			0 => f0(_value0),
			1 => f1(_value1),
			2 => f2(_value2),
			_ => throw new InvalidOperationException($"Invalid OneOf index: {_index}"),
		};
	}

	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public void Switch(
		Action<T0> a0,
		Action<T1> a1,
		Action<T2> a2)
	{
		switch (_index)
		{
			case 0: a0(_value0); break;
			case 1: a1(_value1); break;
			case 2: a2(_value2); break;
			default: throw new InvalidOperationException($"Invalid OneOf index: {_index}");
		}
	}

	public bool TryPickT0([MaybeNullWhen(false)] out T0 value)
	{
		if (_index == 0)
		{
			value = _value0;
			return true;
		}
		value = default;
		return false;
	}

	public bool TryPickT1([MaybeNullWhen(false)] out T1 value)
	{
		if (_index == 1)
		{
			value = _value1;
			return true;
		}
		value = default;
		return false;
	}

	public bool TryPickT2([MaybeNullWhen(false)] out T2 value)
	{
		if (_index == 2)
		{
			value = _value2;
			return true;
		}
		value = default;
		return false;
	}

	public bool Equals(OneOf<T0, T1, T2> other)
	{
		if (_index != other._index) return false;
		return _index switch
		{
			0 => EqualityComparer<T0>.Default.Equals(_value0, other._value0),
			1 => EqualityComparer<T1>.Default.Equals(_value1, other._value1),
			2 => EqualityComparer<T2>.Default.Equals(_value2, other._value2),
			_ => false,
		};
	}

	public override bool Equals(object? obj) => obj is OneOf<T0, T1, T2> other && Equals(other);

	public override int GetHashCode() => _index switch
	{
		0 => HashCode.Combine(_index, _value0),
		1 => HashCode.Combine(_index, _value1),
		2 => HashCode.Combine(_index, _value2),
		_ => HashCode.Combine(_index),
	};

	public static bool operator ==(OneOf<T0, T1, T2> left, OneOf<T0, T1, T2> right) => left.Equals(right);
	public static bool operator !=(OneOf<T0, T1, T2> left, OneOf<T0, T1, T2> right) => !left.Equals(right);

	public override string ToString() => _index switch
	{
		0 => $"OneOf<T0>({_value0})",
		1 => $"OneOf<T1>({_value1})",
		2 => $"OneOf<T2>({_value2})",
		_ => $"OneOf(invalid:{_index})",
	};
}
