// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

namespace OneOf;

public readonly struct OneOf<T0, T1, T2, T3, T4, T5, T6, T7> : IOneOf, IEquatable<OneOf<T0, T1, T2, T3, T4, T5, T6, T7>>
{
	private readonly T0 _value0;
	private readonly T1 _value1;
	private readonly T2 _value2;
	private readonly T3 _value3;
	private readonly T4 _value4;
	private readonly T5 _value5;
	private readonly T6 _value6;
	private readonly T7 _value7;
	private readonly int _index;

	private OneOf(int index, T0 value0 = default!, T1 value1 = default!, T2 value2 = default!, T3 value3 = default!, T4 value4 = default!, T5 value5 = default!, T6 value6 = default!, T7 value7 = default!)
	{
		_index = index;
		_value0 = value0;
		_value1 = value1;
		_value2 = value2;
		_value3 = value3;
		_value4 = value4;
		_value5 = value5;
		_value6 = value6;
		_value7 = value7;
	}

	public int Index => _index;

	public object? Value => _index switch
	{
		0 => _value0,
		1 => _value1,
		2 => _value2,
		3 => _value3,
		4 => _value4,
		5 => _value5,
		6 => _value6,
		7 => _value7,
		_ => throw new InvalidOperationException($"Invalid OneOf index: {_index}"),
	};

	public bool IsT0 => _index == 0;
	public bool IsT1 => _index == 1;
	public bool IsT2 => _index == 2;
	public bool IsT3 => _index == 3;
	public bool IsT4 => _index == 4;
	public bool IsT5 => _index == 5;
	public bool IsT6 => _index == 6;
	public bool IsT7 => _index == 7;

	public T0 AsT0 => _index == 0
		? _value0
		: throw new InvalidOperationException($"Cannot access T0 when index is {_index}.");

	public T1 AsT1 => _index == 1
		? _value1
		: throw new InvalidOperationException($"Cannot access T1 when index is {_index}.");

	public T2 AsT2 => _index == 2
		? _value2
		: throw new InvalidOperationException($"Cannot access T2 when index is {_index}.");

	public T3 AsT3 => _index == 3
		? _value3
		: throw new InvalidOperationException($"Cannot access T3 when index is {_index}.");

	public T4 AsT4 => _index == 4
		? _value4
		: throw new InvalidOperationException($"Cannot access T4 when index is {_index}.");

	public T5 AsT5 => _index == 5
		? _value5
		: throw new InvalidOperationException($"Cannot access T5 when index is {_index}.");

	public T6 AsT6 => _index == 6
		? _value6
		: throw new InvalidOperationException($"Cannot access T6 when index is {_index}.");

	public T7 AsT7 => _index == 7
		? _value7
		: throw new InvalidOperationException($"Cannot access T7 when index is {_index}.");

	public static implicit operator OneOf<T0, T1, T2, T3, T4, T5, T6, T7>(T0 t) => new(0, value0: t);

	public static implicit operator OneOf<T0, T1, T2, T3, T4, T5, T6, T7>(T1 t) => new(1, value1: t);

	public static implicit operator OneOf<T0, T1, T2, T3, T4, T5, T6, T7>(T2 t) => new(2, value2: t);

	public static implicit operator OneOf<T0, T1, T2, T3, T4, T5, T6, T7>(T3 t) => new(3, value3: t);

	public static implicit operator OneOf<T0, T1, T2, T3, T4, T5, T6, T7>(T4 t) => new(4, value4: t);

	public static implicit operator OneOf<T0, T1, T2, T3, T4, T5, T6, T7>(T5 t) => new(5, value5: t);

	public static implicit operator OneOf<T0, T1, T2, T3, T4, T5, T6, T7>(T6 t) => new(6, value6: t);

	public static implicit operator OneOf<T0, T1, T2, T3, T4, T5, T6, T7>(T7 t) => new(7, value7: t);

	public static OneOf<T0, T1, T2, T3, T4, T5, T6, T7> FromT0(T0 value) => value;
	public static OneOf<T0, T1, T2, T3, T4, T5, T6, T7> FromT1(T1 value) => value;
	public static OneOf<T0, T1, T2, T3, T4, T5, T6, T7> FromT2(T2 value) => value;
	public static OneOf<T0, T1, T2, T3, T4, T5, T6, T7> FromT3(T3 value) => value;
	public static OneOf<T0, T1, T2, T3, T4, T5, T6, T7> FromT4(T4 value) => value;
	public static OneOf<T0, T1, T2, T3, T4, T5, T6, T7> FromT5(T5 value) => value;
	public static OneOf<T0, T1, T2, T3, T4, T5, T6, T7> FromT6(T6 value) => value;
	public static OneOf<T0, T1, T2, T3, T4, T5, T6, T7> FromT7(T7 value) => value;

	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public TResult Match<TResult>(
		Func<T0, TResult> f0,
		Func<T1, TResult> f1,
		Func<T2, TResult> f2,
		Func<T3, TResult> f3,
		Func<T4, TResult> f4,
		Func<T5, TResult> f5,
		Func<T6, TResult> f6,
		Func<T7, TResult> f7)
	{
		return _index switch
		{
			0 => f0(_value0),
			1 => f1(_value1),
			2 => f2(_value2),
			3 => f3(_value3),
			4 => f4(_value4),
			5 => f5(_value5),
			6 => f6(_value6),
			7 => f7(_value7),
			_ => throw new InvalidOperationException($"Invalid OneOf index: {_index}"),
		};
	}

	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public void Switch(
		Action<T0> a0,
		Action<T1> a1,
		Action<T2> a2,
		Action<T3> a3,
		Action<T4> a4,
		Action<T5> a5,
		Action<T6> a6,
		Action<T7> a7)
	{
		switch (_index)
		{
			case 0: a0(_value0); break;
			case 1: a1(_value1); break;
			case 2: a2(_value2); break;
			case 3: a3(_value3); break;
			case 4: a4(_value4); break;
			case 5: a5(_value5); break;
			case 6: a6(_value6); break;
			case 7: a7(_value7); break;
			default: throw new InvalidOperationException($"Invalid OneOf index: {_index}");
		}
	}

	public bool TryPickT0([MaybeNullWhen(false)] out T0 value)
	{
		if (_index == 0)
		{
			value = _value0;
			return true;
		}
		value = default;
		return false;
	}

	public bool TryPickT1([MaybeNullWhen(false)] out T1 value)
	{
		if (_index == 1)
		{
			value = _value1;
			return true;
		}
		value = default;
		return false;
	}

	public bool TryPickT2([MaybeNullWhen(false)] out T2 value)
	{
		if (_index == 2)
		{
			value = _value2;
			return true;
		}
		value = default;
		return false;
	}

	public bool TryPickT3([MaybeNullWhen(false)] out T3 value)
	{
		if (_index == 3)
		{
			value = _value3;
			return true;
		}
		value = default;
		return false;
	}

	public bool TryPickT4([MaybeNullWhen(false)] out T4 value)
	{
		if (_index == 4)
		{
			value = _value4;
			return true;
		}
		value = default;
		return false;
	}

	public bool TryPickT5([MaybeNullWhen(false)] out T5 value)
	{
		if (_index == 5)
		{
			value = _value5;
			return true;
		}
		value = default;
		return false;
	}

	public bool TryPickT6([MaybeNullWhen(false)] out T6 value)
	{
		if (_index == 6)
		{
			value = _value6;
			return true;
		}
		value = default;
		return false;
	}

	public bool TryPickT7([MaybeNullWhen(false)] out T7 value)
	{
		if (_index == 7)
		{
			value = _value7;
			return true;
		}
		value = default;
		return false;
	}

	public bool Equals(OneOf<T0, T1, T2, T3, T4, T5, T6, T7> other)
	{
		if (_index != other._index) return false;
		return _index switch
		{
			0 => EqualityComparer<T0>.Default.Equals(_value0, other._value0),
			1 => EqualityComparer<T1>.Default.Equals(_value1, other._value1),
			2 => EqualityComparer<T2>.Default.Equals(_value2, other._value2),
			3 => EqualityComparer<T3>.Default.Equals(_value3, other._value3),
			4 => EqualityComparer<T4>.Default.Equals(_value4, other._value4),
			5 => EqualityComparer<T5>.Default.Equals(_value5, other._value5),
			6 => EqualityComparer<T6>.Default.Equals(_value6, other._value6),
			7 => EqualityComparer<T7>.Default.Equals(_value7, other._value7),
			_ => false,
		};
	}

	public override bool Equals(object? obj) => obj is OneOf<T0, T1, T2, T3, T4, T5, T6, T7> other && Equals(other);

	public override int GetHashCode() => _index switch
	{
		0 => HashCode.Combine(_index, _value0),
		1 => HashCode.Combine(_index, _value1),
		2 => HashCode.Combine(_index, _value2),
		3 => HashCode.Combine(_index, _value3),
		4 => HashCode.Combine(_index, _value4),
		5 => HashCode.Combine(_index, _value5),
		6 => HashCode.Combine(_index, _value6),
		7 => HashCode.Combine(_index, _value7),
		_ => HashCode.Combine(_index),
	};

	public static bool operator ==(OneOf<T0, T1, T2, T3, T4, T5, T6, T7> left, OneOf<T0, T1, T2, T3, T4, T5, T6, T7> right) => left.Equals(right);
	public static bool operator !=(OneOf<T0, T1, T2, T3, T4, T5, T6, T7> left, OneOf<T0, T1, T2, T3, T4, T5, T6, T7> right) => !left.Equals(right);

	public override string ToString() => _index switch
	{
		0 => $"OneOf<T0>({_value0})",
		1 => $"OneOf<T1>({_value1})",
		2 => $"OneOf<T2>({_value2})",
		3 => $"OneOf<T3>({_value3})",
		4 => $"OneOf<T4>({_value4})",
		5 => $"OneOf<T5>({_value5})",
		6 => $"OneOf<T6>({_value6})",
		7 => $"OneOf<T7>({_value7})",
		_ => $"OneOf(invalid:{_index})",
	};
}
