// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>

namespace Protocol
{
	public enum AttributeOperands
	{
		/// <summary>OPERAND_MIN</summary>
		OPERANDMIN = 0,
		/// <summary>OPERAND_MAX</summary>
		OPERANDMAX = 1,
		/// <summary>OPERAND_CURRENT</summary>
		OPERANDCURRENT = 2,
		/// <summary>TOTAL_OPERANDS</summary>
		TOTALOPERANDS = 3,
		/// <summary>OPERAND_INVALID</summary>
		OPERANDINVALID = 3,
	}
}
