// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class AttributeData
	{
		public float MinValue { get; set; }
		public float MaxValue { get; set; }
		public float CurrentValue { get; set; }
		public float DefaultMinValue { get; set; }
		public float DefaultMaxValue { get; set; }
		public float DefaultValue { get; set; }
		public string Name { get; set; }
		public List<AttributeModifier> Modifiers { get; set; } = new List<AttributeModifier>();

		public void Read(MemoryStreamReader reader)
		{
			MinValue = reader.ReadSingle();
			MaxValue = reader.ReadSingle();
			CurrentValue = reader.ReadSingle();
			DefaultMinValue = reader.ReadSingle();
			DefaultMaxValue = reader.ReadSingle();
			DefaultValue = reader.ReadSingle();
			Name = reader.ReadLengthPrefixedString();
			Modifiers = reader.ReadSlice(() => { var _Item = new AttributeModifier(); _Item.Read(reader); return _Item; });
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteSingle(MinValue);
			writer.WriteSingle(MaxValue);
			writer.WriteSingle(CurrentValue);
			writer.WriteSingle(DefaultMinValue);
			writer.WriteSingle(DefaultMaxValue);
			writer.WriteSingle(DefaultValue);
			writer.WriteLengthPrefixedString(Name);
			writer.WriteSlice(Modifiers, v => v.Write(writer));
		}
	}
}
