// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.EAS
{
	public class AttributeLayerData
	{
		public string Name { get; set; }
		public Optional<string> NoiseName { get; set; } = new Optional<string>();
		public DimensionType Dimension { get; set; }
		public AttributeLayerSettings Settings { get; set; }
		public List<EnvironmentAttributeData> Attributes { get; set; } = new List<EnvironmentAttributeData>();

		public void Read(MemoryStreamReader reader)
		{
			Name = reader.ReadLengthPrefixedString();
			if (reader.ReadByte() != 0)
			{
				NoiseName = new Optional<string>(reader.ReadLengthPrefixedString());
			}
			Dimension = new DimensionType();
			Dimension.Read(reader);
			Settings = new AttributeLayerSettings();
			Settings.Read(reader);
			Attributes = reader.ReadSlice(() => { var _Item = new EnvironmentAttributeData(); _Item.Read(reader); return _Item; });
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(Name);
			if (NoiseName != null && NoiseName.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteLengthPrefixedString(NoiseName.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
			Dimension.Write(writer);
			Settings.Write(writer);
			writer.WriteSlice(Attributes, v => v.Write(writer));
		}
	}
}
