// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.EAS
{
	public class ColorAttributeData
	{
		public int[] Value { get; set; } = new int[4];
		public Protocol.EAS.ColorAttributeOperation Operation { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			Value = reader.ReadSliceOfLen(4, () => reader.ReadInt32());
			Operation = EnumCodec.FromString<Protocol.EAS.ColorAttributeOperation>(reader.ReadLengthPrefixedString());
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteSliceOfLen(Value, 4, v => writer.WriteInt32(v));
			writer.WriteLengthPrefixedString(EnumCodec.ToString(Operation));
		}
	}
}
