// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>

namespace Protocol.EAS
{
	public enum FloatAttributeOperation
	{
		OVERRIDE = 0,
		/// <summary>ALPHA_BLEND</summary>
		ALPHABLEND = 1,
		ADD = 2,
		SUBTRACT = 3,
		MULTIPLY = 4,
		MINIMUM = 5,
		MAXIMUM = 6,
	}
}
