// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.EAS
{
	public class FloatAttributeData
	{
		public float Value { get; set; }
		public Protocol.EAS.FloatAttributeOperation Operation { get; set; }
		public Optional<float> ConstraintMin { get; set; } = new Optional<float>();
		public Optional<float> ConstraintMax { get; set; } = new Optional<float>();

		public void Read(MemoryStreamReader reader)
		{
			Value = reader.ReadSingle();
			Operation = EnumCodec.FromString<Protocol.EAS.FloatAttributeOperation>(reader.ReadLengthPrefixedString());
			if (reader.ReadByte() != 0)
			{
				ConstraintMin = new Optional<float>(reader.ReadSingle());
			}
			if (reader.ReadByte() != 0)
			{
				ConstraintMax = new Optional<float>(reader.ReadSingle());
			}
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteSingle(Value);
			writer.WriteLengthPrefixedString(EnumCodec.ToString(Operation));
			if (ConstraintMin != null && ConstraintMin.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteSingle(ConstraintMin.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (ConstraintMax != null && ConstraintMax.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteSingle(ConstraintMax.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
		}
	}
}
