// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.EAS
{
	public class NoiseAlignment
	{
		public Protocol.NoiseAlignmentType Type { get; set; }
		public uint Value { get; set; } 

		public void Read(MemoryStreamReader reader)
		{
			Type = (Protocol.NoiseAlignmentType)reader.ReadByte();
			Value = VarInt.ReadUInt32(reader); 
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteByte((byte)Type);
			writer.WriteVarUInt32(Value); 
		}
	}
}

namespace Protocol
{
	public enum NoiseAlignmentType
	{
		/// <summary>minLocalTransitionEnd</summary>
		MinLocalTransitionEnd = 0,
	}
}
