// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.CameraInstructionOptions
{
	public class SetInstruction
	{
		public uint Preset { get; set; }
		public Optional<CameraInstructionOptions.SetInstruction.EaseOption> Ease { get; set; } = new Optional<CameraInstructionOptions.SetInstruction.EaseOption>();
		public Optional<CameraInstructionOptions.SetInstruction.PosOption> Pos { get; set; } = new Optional<CameraInstructionOptions.SetInstruction.PosOption>();
		public Optional<CameraInstructionOptions.SetInstruction.RotOption> Rot { get; set; } = new Optional<CameraInstructionOptions.SetInstruction.RotOption>();
		public Optional<CameraInstructionOptions.SetInstruction.FacingOption> Facing { get; set; } = new Optional<CameraInstructionOptions.SetInstruction.FacingOption>();
		public Optional<CameraInstructionOptions.SetInstruction.ViewOffsetOption> ViewOffset { get; set; } = new Optional<CameraInstructionOptions.SetInstruction.ViewOffsetOption>();
		public Optional<CameraInstructionOptions.SetInstruction.EntityOffsetOption> EntityOffset { get; set; } = new Optional<CameraInstructionOptions.SetInstruction.EntityOffsetOption>();
		public Optional<bool> Default { get; set; } = new Optional<bool>();
		public bool RemoveIgnoreStartingValuesComponent { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			Preset = reader.ReadUInt32();
			if (reader.ReadByte() != 0)
			{
				var _EaseValue = new CameraInstructionOptions.SetInstruction.EaseOption();
				_EaseValue.Read(reader);
				Ease = new Optional<CameraInstructionOptions.SetInstruction.EaseOption>(_EaseValue);
			}
			if (reader.ReadByte() != 0)
			{
				var _PosValue = new CameraInstructionOptions.SetInstruction.PosOption();
				_PosValue.Read(reader);
				Pos = new Optional<CameraInstructionOptions.SetInstruction.PosOption>(_PosValue);
			}
			if (reader.ReadByte() != 0)
			{
				var _RotValue = new CameraInstructionOptions.SetInstruction.RotOption();
				_RotValue.Read(reader);
				Rot = new Optional<CameraInstructionOptions.SetInstruction.RotOption>(_RotValue);
			}
			if (reader.ReadByte() != 0)
			{
				var _FacingValue = new CameraInstructionOptions.SetInstruction.FacingOption();
				_FacingValue.Read(reader);
				Facing = new Optional<CameraInstructionOptions.SetInstruction.FacingOption>(_FacingValue);
			}
			if (reader.ReadByte() != 0)
			{
				var _ViewOffsetValue = new CameraInstructionOptions.SetInstruction.ViewOffsetOption();
				_ViewOffsetValue.Read(reader);
				ViewOffset = new Optional<CameraInstructionOptions.SetInstruction.ViewOffsetOption>(_ViewOffsetValue);
			}
			if (reader.ReadByte() != 0)
			{
				var _EntityOffsetValue = new CameraInstructionOptions.SetInstruction.EntityOffsetOption();
				_EntityOffsetValue.Read(reader);
				EntityOffset = new Optional<CameraInstructionOptions.SetInstruction.EntityOffsetOption>(_EntityOffsetValue);
			}
			if (reader.ReadByte() != 0)
			{
				Default = new Optional<bool>(reader.ReadByte() != 0);
			}
			RemoveIgnoreStartingValuesComponent = reader.ReadByte() != 0;
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteUInt32(Preset);
			if (Ease != null && Ease.HasValue)
			{
				writer.WriteByte(1);
				Ease.Value.Write(writer);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (Pos != null && Pos.HasValue)
			{
				writer.WriteByte(1);
				Pos.Value.Write(writer);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (Rot != null && Rot.HasValue)
			{
				writer.WriteByte(1);
				Rot.Value.Write(writer);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (Facing != null && Facing.HasValue)
			{
				writer.WriteByte(1);
				Facing.Value.Write(writer);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (ViewOffset != null && ViewOffset.HasValue)
			{
				writer.WriteByte(1);
				ViewOffset.Value.Write(writer);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (EntityOffset != null && EntityOffset.HasValue)
			{
				writer.WriteByte(1);
				EntityOffset.Value.Write(writer);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (Default != null && Default.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteByte(Default.Value ? (byte)1 : (byte)0);
			}
			else
			{
				writer.WriteByte(0);
			}
			writer.WriteByte(RemoveIgnoreStartingValuesComponent ? (byte)1 : (byte)0);
		}

	public class EaseOption
	{
		public byte Type_ { get; set; }
		public float Time { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			Type_ = (byte)reader.ReadByte();
			Time = reader.ReadSingle();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteByte(Type_);
			writer.WriteSingle(Time);
		}
	}

	public class EntityOffsetOption
	{
		public float EntityOffsetX { get; set; }
		public float EntityOffsetY { get; set; }
		public float EntityOffsetZ { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			EntityOffsetX = reader.ReadSingle();
			EntityOffsetY = reader.ReadSingle();
			EntityOffsetZ = reader.ReadSingle();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteSingle(EntityOffsetX);
			writer.WriteSingle(EntityOffsetY);
			writer.WriteSingle(EntityOffsetZ);
		}
	}

	public class FacingOption
	{
		public Vec3 Pos { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			Pos = new Vec3();
			Pos.Read(reader);
		}

		public void Write(MemoryStreamWriter writer)
		{
			Pos.Write(writer);
		}
	}

	public class PosOption
	{
		public Vec3 Pos { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			Pos = new Vec3();
			Pos.Read(reader);
		}

		public void Write(MemoryStreamWriter writer)
		{
			Pos.Write(writer);
		}
	}

	public class RotOption
	{
		public float X { get; set; }
		public float Y { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			X = reader.ReadSingle();
			Y = reader.ReadSingle();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteSingle(X);
			writer.WriteSingle(Y);
		}
	}

	public class ViewOffsetOption
	{
		public float X { get; set; }
		public float Y { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			X = reader.ReadSingle();
			Y = reader.ReadSingle();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteSingle(X);
			writer.WriteSingle(Y);
		}
	}
	}
}
