// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.SyncWorldClocksPacketPayload
{
	public class InitializeRegistryData
	{
		public List<WorldClockData> ClockData { get; set; } = new List<WorldClockData>();

		public void Read(MemoryStreamReader reader)
		{
			ClockData = reader.ReadSlice(() => { var _Item = new WorldClockData(); _Item.Read(reader); return _Item; });
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteSlice(ClockData, v => v.Write(writer));
		}
	}
}
