// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.MapInfoRequestPacketAnon
{
	public class ClientPixelsProxy
	{
		public uint Pixel { get; set; }
		public ushort Index { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			Pixel = reader.ReadUInt32();
			Index = reader.ReadUInt16();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteUInt32(Pixel);
			writer.WriteUInt16(Index);
		}
	}
}
