// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.MapItemTrackedActor
{
	public class UniqueId
	{
		public Protocol.MapItemTrackedActor.Type Type_ { get; set; }
		public Optional<ActorUniqueID> EntityID { get; set; } = new Optional<ActorUniqueID>();
		public Optional<BlockPos> BlockPosition { get; set; } = new Optional<BlockPos>();

		public void Read(MemoryStreamReader reader)
		{
			Type_ = (Protocol.MapItemTrackedActor.Type)reader.ReadInt32();
			if (reader.ReadByte() != 0)
			{
				var _EntityIDValue = new ActorUniqueID();
				_EntityIDValue.Read(reader);
				EntityID = new Optional<ActorUniqueID>(_EntityIDValue);
			}
			if (reader.ReadByte() != 0)
			{
				var _BlockPositionValue = new BlockPos();
				_BlockPositionValue.Read(reader);
				BlockPosition = new Optional<BlockPos>(_BlockPositionValue);
			}
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteInt32((int)Type_);
			if (EntityID != null && EntityID.HasValue)
			{
				writer.WriteByte(1);
				EntityID.Value.Write(writer);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (BlockPosition != null && BlockPosition.HasValue)
			{
				writer.WriteByte(1);
				BlockPosition.Value.Write(writer);
			}
			else
			{
				writer.WriteByte(0);
			}
		}
	}
}
