// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.TextPacketPayload
{
	public class MessageAndParams
	{
		public Protocol.TextPacketType MessageType { get; set; }
		public string Message { get; set; }
		public List<string> ParameterList { get; set; } = new List<string>();

		public void Read(MemoryStreamReader reader)
		{
			MessageType = (Protocol.TextPacketType)reader.ReadByte();
			Message = reader.ReadLengthPrefixedString();
			ParameterList = reader.ReadSlice(() => reader.ReadLengthPrefixedString());
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteByte((byte)MessageType);
			writer.WriteLengthPrefixedString(Message);
			writer.WriteSlice(ParameterList, v => writer.WriteLengthPrefixedString(v));
		}
	}
}
