// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class BlockPos
	{
		public int X { get; set; } 
		public int Y { get; set; } 
		public int Z { get; set; } 

		public void Read(MemoryStreamReader reader)
		{
			X = VarInt.ReadInt32(reader); 
			Y = VarInt.ReadInt32(reader); 
			Z = VarInt.ReadInt32(reader); 
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteVarInt32(X); 
			writer.WriteVarInt32(Y); 
			writer.WriteVarInt32(Z); 
		}
	}
}
