// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.VoxelShapes
{
	public class SerializableCells
	{
		public byte XSize { get; set; }
		public byte YSize { get; set; }
		public byte ZSize { get; set; }
		public List<byte> Storage { get; set; } = new List<byte>();

		public void Read(MemoryStreamReader reader)
		{
			XSize = (byte)reader.ReadByte();
			YSize = (byte)reader.ReadByte();
			ZSize = (byte)reader.ReadByte();
			Storage = reader.ReadSlice(() => (byte)reader.ReadByte());
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteByte(XSize);
			writer.WriteByte(YSize);
			writer.WriteByte(ZSize);
			writer.WriteSlice(Storage, v => writer.WriteByte(v));
		}
	}
}
