// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.VoxelShapes
{
	public class SerializableVoxelShape
	{
		public SerializableCells Cells { get; set; }
		public List<float> XCoordinates { get; set; } = new List<float>();
		public List<float> YCoordinates { get; set; } = new List<float>();
		public List<float> ZCoordinates { get; set; } = new List<float>();

		public void Read(MemoryStreamReader reader)
		{
			Cells = new SerializableCells();
			Cells.Read(reader);
			XCoordinates = reader.ReadSlice(() => reader.ReadSingle());
			YCoordinates = reader.ReadSlice(() => reader.ReadSingle());
			ZCoordinates = reader.ReadSlice(() => reader.ReadSingle());
		}

		public void Write(MemoryStreamWriter writer)
		{
			Cells.Write(writer);
			writer.WriteSlice(XCoordinates, v => writer.WriteSingle(v));
			writer.WriteSlice(YCoordinates, v => writer.WriteSingle(v));
			writer.WriteSlice(ZCoordinates, v => writer.WriteSingle(v));
		}
	}
}
