// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class ContainerMixDataEntry
	{
		public int FromItemId { get; set; } 
		public int ReagentItemId { get; set; } 
		public int ToItemId { get; set; } 

		public void Read(MemoryStreamReader reader)
		{
			FromItemId = VarInt.ReadInt32(reader); 
			ReagentItemId = VarInt.ReadInt32(reader); 
			ToItemId = VarInt.ReadInt32(reader); 
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteVarInt32(FromItemId); 
			writer.WriteVarInt32(ReagentItemId); 
			writer.WriteVarInt32(ToItemId); 
		}
	}
}
