// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class FullContainerName
	{
		public Protocol.ContainerEnumName ContainerName { get; set; }
		public Optional<uint> DynamicID { get; set; } = new Optional<uint>();

		public void Read(MemoryStreamReader reader)
		{
			ContainerName = (Protocol.ContainerEnumName)reader.ReadByte();
			if (reader.ReadByte() != 0)
			{
				DynamicID = new Optional<uint>(reader.ReadUInt32());
			}
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteByte((byte)ContainerName);
			if (DynamicID != null && DynamicID.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteUInt32(DynamicID.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
		}
	}
}
