// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class ArmorSlotAndDamagePair
	{
		public Protocol.SharedTypes.Legacy.ArmorSlot ArmorSlot { get; set; } 
		public short Damage { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			ArmorSlot = (Protocol.SharedTypes.Legacy.ArmorSlot)VarInt.ReadInt32(reader); 
			Damage = reader.ReadInt16();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteVarInt32((int)ArmorSlot); 
			writer.WriteInt16(Damage);
		}
	}
}
