// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class CreativeItemEntryPayload
	{
		public TypedServerNetId_struct_CreativeItemNetIdTag CreativeNetId { get; set; }
		public NetworkItemInstanceDescriptor.NetworkItemInstanceDescriptor ItemInstance { get; set; }
		public uint GroupIndex { get; set; } 

		public void Read(MemoryStreamReader reader)
		{
			CreativeNetId = new TypedServerNetId_struct_CreativeItemNetIdTag();
			CreativeNetId.Read(reader);
			ItemInstance = new NetworkItemInstanceDescriptor.NetworkItemInstanceDescriptor();
			ItemInstance.Read(reader);
			GroupIndex = VarInt.ReadUInt32(reader); 
		}

		public void Write(MemoryStreamWriter writer)
		{
			CreativeNetId.Write(writer);
			ItemInstance.Write(writer);
			writer.WriteVarUInt32(GroupIndex); 
		}
	}
}
