// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class CreativeGroupInfoPayload
	{
		public Protocol.SharedTypes.CreativeItemCategory CreativeCategory { get; set; }
		public string Name { get; set; }
		public NetworkItemInstanceDescriptor.NetworkItemInstanceDescriptor GroupIconItem { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			CreativeCategory = (Protocol.SharedTypes.CreativeItemCategory)reader.ReadByte();
			Name = reader.ReadLengthPrefixedString();
			GroupIconItem = new NetworkItemInstanceDescriptor.NetworkItemInstanceDescriptor();
			GroupIconItem.Read(reader);
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteByte((byte)CreativeCategory);
			writer.WriteLengthPrefixedString(Name);
			GroupIconItem.Write(writer);
		}
	}
}
