// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class FurnaceOptions
	{
		public Protocol.FurnaceLeftTabIndex LeftFurnaceTab { get; set; } 
		public bool Filtering { get; set; }
		public Protocol.FurnaceLayout Layout { get; set; } 

		public void Read(MemoryStreamReader reader)
		{
			LeftFurnaceTab = (Protocol.FurnaceLeftTabIndex)VarInt.ReadInt32(reader); 
			Filtering = reader.ReadByte() != 0;
			Layout = (Protocol.FurnaceLayout)VarInt.ReadInt32(reader); 
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteVarInt32((int)LeftFurnaceTab); 
			writer.WriteByte(Filtering ? (byte)1 : (byte)0);
			writer.WriteVarInt32((int)Layout); 
		}
	}
}
