// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>

namespace Protocol
{
	public enum FurnaceLeftTabIndex
	{
		None = 0,
		RecipeFood = 1,
		RecipeItems = 2,
		RecipeBlocks = 3,
		RecipeSearch = 4,
		Inventory = 5,
	}
}
