// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>

namespace Protocol
{
	public enum InventoryLayout
	{
		None = 0,
		InventoryOnly = 1,
		Default = 2,
		RecipeBookOnly = 3,
	}
}
