// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class InventoryOptions
	{
		public Protocol.InventoryLeftTabIndex LeftInventoryTab { get; set; } 
		public Protocol.InventoryRightTabIndex RightInventoryTab { get; set; } 
		public bool Filtering { get; set; }
		public Protocol.InventoryLayout LayoutInv { get; set; } 
		public Protocol.InventoryLayout LayoutCraft { get; set; } 

		public void Read(MemoryStreamReader reader)
		{
			LeftInventoryTab = (Protocol.InventoryLeftTabIndex)VarInt.ReadInt32(reader); 
			RightInventoryTab = (Protocol.InventoryRightTabIndex)VarInt.ReadInt32(reader); 
			Filtering = reader.ReadByte() != 0;
			LayoutInv = (Protocol.InventoryLayout)VarInt.ReadInt32(reader); 
			LayoutCraft = (Protocol.InventoryLayout)VarInt.ReadInt32(reader); 
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteVarInt32((int)LeftInventoryTab); 
			writer.WriteVarInt32((int)RightInventoryTab); 
			writer.WriteByte(Filtering ? (byte)1 : (byte)0);
			writer.WriteVarInt32((int)LayoutInv); 
			writer.WriteVarInt32((int)LayoutCraft); 
		}
	}
}
