// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>

namespace Protocol.SharedTypes
{
	public enum CreativeItemCategory
	{
		All = 0,
		Construction = 1,
		Nature = 2,
		Equipment = 3,
		Items = 4,
		ItemCommandOnly = 5,
		Undefined = 6,
	}
}
