// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class UpdateSubChunkBlocksChangedInfo
	{
		public List<UpdateSubChunkNetworkBlockInfo> BlocksChangedStandards { get; set; } = new List<UpdateSubChunkNetworkBlockInfo>();
		public List<UpdateSubChunkNetworkBlockInfo> BlocksChangedExtras { get; set; } = new List<UpdateSubChunkNetworkBlockInfo>();

		public void Read(MemoryStreamReader reader)
		{
			BlocksChangedStandards = reader.ReadSlice(() => { var _Item = new UpdateSubChunkNetworkBlockInfo(); _Item.Read(reader); return _Item; });
			BlocksChangedExtras = reader.ReadSlice(() => { var _Item = new UpdateSubChunkNetworkBlockInfo(); _Item.Read(reader); return _Item; });
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteSlice(BlocksChangedStandards, v => v.Write(writer));
			writer.WriteSlice(BlocksChangedExtras, v => v.Write(writer));
		}
	}
}
