// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.SoundDataEvent
{
	public class SeekTo
	{
		public float Seconds { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			Seconds = reader.ReadSingle();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteSingle(Seconds);
		}
	}
}
