// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.SoundDataEvent
{
	public class Resume
	{
		public void Read(MemoryStreamReader reader)
		{
		}

		public void Write(MemoryStreamWriter writer)
		{
		}
	}
}
