// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class TypedServerNetId_struct_ItemStackNetIdTag_int32_t_0
	{
		public int ID { get; set; } 

		public void Read(MemoryStreamReader reader)
		{
			ID = VarInt.ReadInt32(reader); 
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteVarInt32(ID); 
		}
	}
}
