// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using Protocol.Utility.IO;

namespace Protocol.Packets
{
	public abstract class IPacket
	{
		public virtual int PacketId { get; }
		public ReadOnlyMemory<byte> bytes { get; set; }

		public virtual void Read(MemoryStreamReader reader)
		{

		}

		public virtual void Write(MemoryStreamWriter writer)
		{

		}
	}
}
