using System;
using System.Collections.Generic;

namespace Protocol.Packets
{
	/// <summary>包注册表: 静态注册所有 IPacket 实现, 按 PacketId 建立索引 (AOT 兼容, 无反射)。</summary>
	public static class PacketRegistry
	{
		private static readonly Dictionary<int, Type> _packetsById = new Dictionary<int, Type>
		{
			{ 1, typeof(LoginPacket) },
			{ 2, typeof(PlayStatusPacket) },
			{ 3, typeof(ServerToClientHandshakePacket) },
			{ 4, typeof(ClientToServerHandshakePacket) },
			{ 5, typeof(DisconnectPacket) },
			{ 6, typeof(ResourcePacksInfoPacket) },
			{ 7, typeof(ResourcePackStackPacket) },
			{ 8, typeof(ResourcePackClientResponsePacket) },
			{ 9, typeof(TextPacket) },
			{ 10, typeof(SetTimePacket) },
			{ 11, typeof(StartGamePacket) },
			{ 12, typeof(AddPlayerPacket) },
			{ 13, typeof(AddActorPacket) },
			{ 14, typeof(RemoveActorPacket) },
			{ 15, typeof(AddItemActorPacket) },
			{ 16, typeof(ServerPlayerPostMovePositionPacket) },
			{ 17, typeof(TakeItemActorPacket) },
			{ 18, typeof(MoveActorAbsolutePacket) },
			{ 19, typeof(MovePlayerPacket) },
			{ 21, typeof(UpdateBlockPacket) },
			{ 22, typeof(AddPaintingPacket) },
			{ 25, typeof(LevelEventPacket) },
			{ 26, typeof(BlockEventPacket) },
			{ 27, typeof(ActorEventPacket) },
			{ 28, typeof(MobEffectPacket) },
			{ 29, typeof(UpdateAttributesPacket) },
			{ 30, typeof(InventoryTransactionPacket) },
			{ 31, typeof(MobEquipmentPacket) },
			{ 32, typeof(MobArmorEquipmentPacket) },
			{ 33, typeof(InteractPacket) },
			{ 34, typeof(BlockPickRequestPacket) },
			{ 35, typeof(ActorPickRequestPacket) },
			{ 36, typeof(PlayerActionPacket) },
			{ 38, typeof(HurtArmorPacket) },
			{ 39, typeof(SetActorDataPacket) },
			{ 40, typeof(SetActorMotionPacket) },
			{ 41, typeof(SetActorLinkPacket) },
			{ 42, typeof(SetHealthPacket) },
			{ 43, typeof(SetSpawnPositionPacket) },
			{ 44, typeof(AnimatePacket) },
			{ 45, typeof(RespawnPacket) },
			{ 46, typeof(ContainerOpenPacket) },
			{ 47, typeof(ContainerClosePacket) },
			{ 48, typeof(PlayerHotbarPacket) },
			{ 49, typeof(InventoryContentPacket) },
			{ 50, typeof(InventorySlotPacket) },
			{ 51, typeof(ContainerSetDataPacket) },
			{ 52, typeof(CraftingDataPacket) },
			{ 54, typeof(GuiDataPickItemPacket) },
			{ 56, typeof(BlockActorDataPacket) },
			{ 57, typeof(PlayerInputPacket) },
			{ 58, typeof(LevelChunkPacket) },
			{ 59, typeof(SetCommandsEnabledPacket) },
			{ 60, typeof(SetDifficultyPacket) },
			{ 61, typeof(ChangeDimensionPacket) },
			{ 62, typeof(SetPlayerGameTypePacket) },
			{ 63, typeof(PlayerListPacket) },
			{ 64, typeof(SimpleEventPacket) },
			{ 65, typeof(LegacyTelemetryEventPacket) },
			{ 66, typeof(SpawnExperienceOrbPacket) },
			{ 67, typeof(ClientboundMapItemDataPacket) },
			{ 68, typeof(MapInfoRequestPacket) },
			{ 69, typeof(RequestChunkRadiusPacket) },
			{ 70, typeof(ChunkRadiusUpdatedPacket) },
			{ 72, typeof(GameRulesChangedPacket) },
			{ 73, typeof(CameraPacket) },
			{ 74, typeof(BossEventPacket) },
			{ 75, typeof(ShowCreditsPacket) },
			{ 76, typeof(AvailableCommandsPacket) },
			{ 77, typeof(CommandRequestPacket) },
			{ 78, typeof(CommandBlockUpdatePacket) },
			{ 79, typeof(CommandOutputPacket) },
			{ 80, typeof(UpdateTradePacket) },
			{ 81, typeof(UpdateEquipPacket) },
			{ 82, typeof(ResourcePackDataInfoPacket) },
			{ 83, typeof(ResourcePackChunkDataPacket) },
			{ 84, typeof(ResourcePackChunkRequestPacket) },
			{ 85, typeof(TransferPacket) },
			{ 86, typeof(PlaySoundPacket) },
			{ 87, typeof(StopSoundPacket) },
			{ 88, typeof(SetTitlePacket) },
			{ 89, typeof(AddBehaviorTreePacket) },
			{ 90, typeof(StructureBlockUpdatePacket) },
			{ 91, typeof(ShowStoreOfferPacket) },
			{ 92, typeof(PurchaseReceiptPacket) },
			{ 93, typeof(PlayerSkinPacket) },
			{ 94, typeof(SubClientLoginPacket) },
			{ 95, typeof(AutomationClientConnectPacket) },
			{ 96, typeof(SetLastHurtByPacket) },
			{ 97, typeof(BookEditPacket) },
			{ 98, typeof(NpcRequestPacket) },
			{ 99, typeof(PhotoTransferPacket) },
			{ 100, typeof(ModalFormRequestPacket) },
			{ 101, typeof(ModalFormResponsePacket) },
			{ 102, typeof(ServerSettingsRequestPacket) },
			{ 103, typeof(ServerSettingsResponsePacket) },
			{ 104, typeof(ShowProfilePacket) },
			{ 105, typeof(SetDefaultGameTypePacket) },
			{ 106, typeof(RemoveObjectivePacket) },
			{ 107, typeof(SetDisplayObjectivePacket) },
			{ 108, typeof(SetScorePacket) },
			{ 109, typeof(LabTablePacket) },
			{ 110, typeof(UpdateBlockSyncedPacket) },
			{ 111, typeof(MoveActorDeltaPacket) },
			{ 112, typeof(SetScoreboardIdentityPacket) },
			{ 113, typeof(SetLocalPlayerAsInitializedPacket) },
			{ 114, typeof(UpdateSoftEnumPacket) },
			{ 115, typeof(NetworkStackLatencyPacket) },
			{ 118, typeof(SpawnParticleEffectPacket) },
			{ 119, typeof(AvailableActorIdentifiersPacket) },
			{ 121, typeof(NetworkChunkPublisherUpdatePacket) },
			{ 122, typeof(BiomeDefinitionListPacket) },
			{ 123, typeof(LevelSoundEventPacket) },
			{ 124, typeof(LevelEventGenericPacket) },
			{ 125, typeof(LecternUpdatePacket) },
			{ 129, typeof(ClientCacheStatusPacket) },
			{ 130, typeof(OnScreenTextureAnimationPacket) },
			{ 131, typeof(MapCreateLockedCopyPacket) },
			{ 132, typeof(StructureTemplateDataRequestPacket) },
			{ 133, typeof(StructureTemplateDataResponsePacket) },
			{ 135, typeof(ClientCacheBlobStatusPacket) },
			{ 136, typeof(ClientCacheMissResponsePacket) },
			{ 137, typeof(EducationSettingsPacket) },
			{ 138, typeof(EmotePacket) },
			{ 139, typeof(MultiplayerSettingsPacket) },
			{ 140, typeof(SettingsCommandPacket) },
			{ 141, typeof(AnvilDamagePacket) },
			{ 142, typeof(CompletedUsingItemPacket) },
			{ 143, typeof(NetworkSettingsPacket) },
			{ 144, typeof(PlayerAuthInputPacket) },
			{ 145, typeof(CreativeContentPacket) },
			{ 146, typeof(PlayerEnchantOptionsPacket) },
			{ 147, typeof(ItemStackRequestPacket) },
			{ 148, typeof(ItemStackResponsePacket) },
			{ 149, typeof(PlayerArmorDamagePacket) },
			{ 150, typeof(CodeBuilderPacket) },
			{ 151, typeof(UpdatePlayerGameTypePacket) },
			{ 152, typeof(EmoteListPacket) },
			{ 153, typeof(PositionTrackingDBServerBroadcastPacket) },
			{ 154, typeof(PositionTrackingDBClientRequestPacket) },
			{ 155, typeof(DebugInfoPacket) },
			{ 156, typeof(PacketViolationWarningPacket) },
			{ 157, typeof(MotionPredictionHintsPacket) },
			{ 158, typeof(AnimateEntityPacket) },
			{ 159, typeof(CameraShakePacket) },
			{ 160, typeof(PlayerFogPacket) },
			{ 161, typeof(CorrectPlayerMovePredictionPacket) },
			{ 162, typeof(ItemRegistryPacket) },
			{ 164, typeof(ClientboundDebugRendererPacket) },
			{ 165, typeof(SyncActorPropertyPacket) },
			{ 166, typeof(AddVolumeEntityPacket) },
			{ 167, typeof(RemoveVolumeEntityPacket) },
			{ 168, typeof(SimulationTypePacket) },
			{ 169, typeof(NpcDialoguePacket) },
			{ 170, typeof(EduUriResourcePacket) },
			{ 171, typeof(CreatePhotoPacket) },
			{ 172, typeof(UpdateSubChunkBlocksPacket) },
			{ 174, typeof(SubChunkPacket) },
			{ 175, typeof(SubChunkRequestPacket) },
			{ 176, typeof(PlayerStartItemCooldownPacket) },
			{ 177, typeof(ScriptMessagePacket) },
			{ 178, typeof(CodeBuilderSourcePacket) },
			{ 179, typeof(TickingAreasLoadStatusPacket) },
			{ 180, typeof(DimensionDataPacket) },
			{ 181, typeof(AgentActionEventPacket) },
			{ 182, typeof(ChangeMobPropertyPacket) },
			{ 183, typeof(LessonProgressPacket) },
			{ 184, typeof(RequestAbilityPacket) },
			{ 185, typeof(RequestPermissionsPacket) },
			{ 186, typeof(ToastRequestPacket) },
			{ 187, typeof(UpdateAbilitiesPacket) },
			{ 188, typeof(UpdateAdventureSettingsPacket) },
			{ 189, typeof(DeathInfoPacket) },
			{ 190, typeof(EditorNetworkPacket) },
			{ 191, typeof(FeatureRegistryPacket) },
			{ 192, typeof(ServerStatsPacket) },
			{ 193, typeof(RequestNetworkSettingsPacket) },
			{ 194, typeof(GameTestRequestPacket) },
			{ 195, typeof(GameTestResultsPacket) },
			{ 196, typeof(UpdateClientInputLocksPacket) },
			{ 198, typeof(CameraPresetsPacket) },
			{ 199, typeof(UnlockedRecipesPacket) },
			{ 300, typeof(CameraInstructionPacket) },
			{ 302, typeof(TrimDataPacket) },
			{ 303, typeof(OpenSignPacket) },
			{ 304, typeof(AgentAnimationPacket) },
			{ 305, typeof(RefreshEntitlementsPacket) },
			{ 306, typeof(PlayerToggleCrafterSlotRequestPacket) },
			{ 307, typeof(SetPlayerInventoryOptionsPacket) },
			{ 308, typeof(SetHudPacket) },
			{ 309, typeof(AwardAchievementPacket) },
			{ 310, typeof(ClientboundCloseFormPacket) },
			{ 312, typeof(ServerboundLoadingScreenPacket) },
			{ 313, typeof(JigsawStructureDataPacket) },
			{ 314, typeof(CurrentStructureFeaturePacket) },
			{ 315, typeof(ServerboundDiagnosticsPacket) },
			{ 316, typeof(CameraAimAssistPacket) },
			{ 317, typeof(ContainerRegistryCleanupPacket) },
			{ 318, typeof(MovementEffectPacket) },
			{ 320, typeof(CameraAimAssistPresetsPacket) },
			{ 321, typeof(ClientCameraAimAssistPacket) },
			{ 322, typeof(ClientMovementPredictionSyncPacket) },
			{ 323, typeof(UpdateClientOptionsPacket) },
			{ 324, typeof(PlayerVideoCapturePacket) },
			{ 325, typeof(PlayerUpdateEntityOverridesPacket) },
			{ 326, typeof(PlayerLocationPacket) },
			{ 327, typeof(ClientboundControlSchemeSetPacket) },
			{ 328, typeof(PrimitiveShapesPacket) },
			{ 329, typeof(ServerboundPackSettingChangePacket) },
			{ 330, typeof(ClientboundDataStorePacket) },
			{ 331, typeof(GraphicsOverrideParameterPacket) },
			{ 332, typeof(ServerboundDataStorePacket) },
			{ 333, typeof(ClientboundDataDrivenUIShowScreenPacket) },
			{ 334, typeof(ClientboundDataDrivenUICloseScreenPacket) },
			{ 335, typeof(ClientboundDataDrivenUIReloadPacket) },
			{ 336, typeof(ClientboundTextureShiftPacket) },
			{ 337, typeof(VoxelShapesPacket) },
			{ 338, typeof(CameraSplinePacket) },
			{ 339, typeof(CameraAimAssistActorPriorityPacket) },
			{ 340, typeof(ResourcePacksReadyForValidationPacket) },
			{ 341, typeof(LocatorBarPacket) },
			{ 342, typeof(PartyChangedPacket) },
			{ 343, typeof(ServerboundDataDrivenScreenClosedPacket) },
			{ 344, typeof(SyncWorldClocksPacket) },
			{ 345, typeof(ClientboundAttributeLayerSyncPacket) },
			{ 346, typeof(ServerStoreInfoPacket) },
			{ 347, typeof(ServerPresenceInfoPacket) },
			{ 348, typeof(ClientboundUpdateSoundDataPacket) },
			{ 349, typeof(SendPartyDestinationCookiePacket) },
			{ 350, typeof(PartyDestinationCookieResponsePacket) },
		};

		private static readonly Dictionary<Type, int> _packetIdsByType = new Dictionary<Type, int>();

		static PacketRegistry()
		{
			foreach (var pair in _packetsById)
			{
				_packetIdsByType[pair.Value] = pair.Key;
			}
		}

		/// <summary>已注册的包数量。</summary>
		public static int Count => _packetsById.Count;

		/// <summary>PacketId → 包类型。</summary>
		public static IReadOnlyDictionary<int, Type> PacketsById => _packetsById;

		public static bool TryGetPacketType(int packetId, out Type type)
		{
			return _packetsById.TryGetValue(packetId, out type);
		}

		public static bool TryGetPacketType(MinecraftPacketIds packetId, out Type type)
		{
			return _packetsById.TryGetValue((int)packetId, out type);
		}

		public static Type GetPacketType(int packetId)
		{
			if (!_packetsById.TryGetValue(packetId, out var type))
			{
				throw new KeyNotFoundException($"未注册的包 ID: {packetId}");
			}

			return type;
		}

		public static Type GetPacketType(MinecraftPacketIds packetId)
		{
			return GetPacketType((int)packetId);
		}

		public static bool TryGetPacketId(Type type, out int packetId)
		{
			return _packetIdsByType.TryGetValue(type, out packetId);
		}

		public static int GetPacketId(Type type)
		{
			if (!_packetIdsByType.TryGetValue(type, out var packetId))
			{
				throw new KeyNotFoundException($"未注册的包类型: {type.FullName}");
			}

			return packetId;
		}

		public static int GetPacketId<T>() where T : IPacket
		{
			return GetPacketId(typeof(T));
		}

		public static IPacket CreatePacket(int packetId)
		{
			return packetId switch
			{
				1 => new LoginPacket(),
				2 => new PlayStatusPacket(),
				3 => new ServerToClientHandshakePacket(),
				4 => new ClientToServerHandshakePacket(),
				5 => new DisconnectPacket(),
				6 => new ResourcePacksInfoPacket(),
				7 => new ResourcePackStackPacket(),
				8 => new ResourcePackClientResponsePacket(),
				9 => new TextPacket(),
				10 => new SetTimePacket(),
				11 => new StartGamePacket(),
				12 => new AddPlayerPacket(),
				13 => new AddActorPacket(),
				14 => new RemoveActorPacket(),
				15 => new AddItemActorPacket(),
				16 => new ServerPlayerPostMovePositionPacket(),
				17 => new TakeItemActorPacket(),
				18 => new MoveActorAbsolutePacket(),
				19 => new MovePlayerPacket(),
				21 => new UpdateBlockPacket(),
				22 => new AddPaintingPacket(),
				25 => new LevelEventPacket(),
				26 => new BlockEventPacket(),
				27 => new ActorEventPacket(),
				28 => new MobEffectPacket(),
				29 => new UpdateAttributesPacket(),
				30 => new InventoryTransactionPacket(),
				31 => new MobEquipmentPacket(),
				32 => new MobArmorEquipmentPacket(),
				33 => new InteractPacket(),
				34 => new BlockPickRequestPacket(),
				35 => new ActorPickRequestPacket(),
				36 => new PlayerActionPacket(),
				38 => new HurtArmorPacket(),
				39 => new SetActorDataPacket(),
				40 => new SetActorMotionPacket(),
				41 => new SetActorLinkPacket(),
				42 => new SetHealthPacket(),
				43 => new SetSpawnPositionPacket(),
				44 => new AnimatePacket(),
				45 => new RespawnPacket(),
				46 => new ContainerOpenPacket(),
				47 => new ContainerClosePacket(),
				48 => new PlayerHotbarPacket(),
				49 => new InventoryContentPacket(),
				50 => new InventorySlotPacket(),
				51 => new ContainerSetDataPacket(),
				52 => new CraftingDataPacket(),
				54 => new GuiDataPickItemPacket(),
				56 => new BlockActorDataPacket(),
				57 => new PlayerInputPacket(),
				58 => new LevelChunkPacket(),
				59 => new SetCommandsEnabledPacket(),
				60 => new SetDifficultyPacket(),
				61 => new ChangeDimensionPacket(),
				62 => new SetPlayerGameTypePacket(),
				63 => new PlayerListPacket(),
				64 => new SimpleEventPacket(),
				65 => new LegacyTelemetryEventPacket(),
				66 => new SpawnExperienceOrbPacket(),
				67 => new ClientboundMapItemDataPacket(),
				68 => new MapInfoRequestPacket(),
				69 => new RequestChunkRadiusPacket(),
				70 => new ChunkRadiusUpdatedPacket(),
				72 => new GameRulesChangedPacket(),
				73 => new CameraPacket(),
				74 => new BossEventPacket(),
				75 => new ShowCreditsPacket(),
				76 => new AvailableCommandsPacket(),
				77 => new CommandRequestPacket(),
				78 => new CommandBlockUpdatePacket(),
				79 => new CommandOutputPacket(),
				80 => new UpdateTradePacket(),
				81 => new UpdateEquipPacket(),
				82 => new ResourcePackDataInfoPacket(),
				83 => new ResourcePackChunkDataPacket(),
				84 => new ResourcePackChunkRequestPacket(),
				85 => new TransferPacket(),
				86 => new PlaySoundPacket(),
				87 => new StopSoundPacket(),
				88 => new SetTitlePacket(),
				89 => new AddBehaviorTreePacket(),
				90 => new StructureBlockUpdatePacket(),
				91 => new ShowStoreOfferPacket(),
				92 => new PurchaseReceiptPacket(),
				93 => new PlayerSkinPacket(),
				94 => new SubClientLoginPacket(),
				95 => new AutomationClientConnectPacket(),
				96 => new SetLastHurtByPacket(),
				97 => new BookEditPacket(),
				98 => new NpcRequestPacket(),
				99 => new PhotoTransferPacket(),
				100 => new ModalFormRequestPacket(),
				101 => new ModalFormResponsePacket(),
				102 => new ServerSettingsRequestPacket(),
				103 => new ServerSettingsResponsePacket(),
				104 => new ShowProfilePacket(),
				105 => new SetDefaultGameTypePacket(),
				106 => new RemoveObjectivePacket(),
				107 => new SetDisplayObjectivePacket(),
				108 => new SetScorePacket(),
				109 => new LabTablePacket(),
				110 => new UpdateBlockSyncedPacket(),
				111 => new MoveActorDeltaPacket(),
				112 => new SetScoreboardIdentityPacket(),
				113 => new SetLocalPlayerAsInitializedPacket(),
				114 => new UpdateSoftEnumPacket(),
				115 => new NetworkStackLatencyPacket(),
				118 => new SpawnParticleEffectPacket(),
				119 => new AvailableActorIdentifiersPacket(),
				121 => new NetworkChunkPublisherUpdatePacket(),
				122 => new BiomeDefinitionListPacket(),
				123 => new LevelSoundEventPacket(),
				124 => new LevelEventGenericPacket(),
				125 => new LecternUpdatePacket(),
				129 => new ClientCacheStatusPacket(),
				130 => new OnScreenTextureAnimationPacket(),
				131 => new MapCreateLockedCopyPacket(),
				132 => new StructureTemplateDataRequestPacket(),
				133 => new StructureTemplateDataResponsePacket(),
				135 => new ClientCacheBlobStatusPacket(),
				136 => new ClientCacheMissResponsePacket(),
				137 => new EducationSettingsPacket(),
				138 => new EmotePacket(),
				139 => new MultiplayerSettingsPacket(),
				140 => new SettingsCommandPacket(),
				141 => new AnvilDamagePacket(),
				142 => new CompletedUsingItemPacket(),
				143 => new NetworkSettingsPacket(),
				144 => new PlayerAuthInputPacket(),
				145 => new CreativeContentPacket(),
				146 => new PlayerEnchantOptionsPacket(),
				147 => new ItemStackRequestPacket(),
				148 => new ItemStackResponsePacket(),
				149 => new PlayerArmorDamagePacket(),
				150 => new CodeBuilderPacket(),
				151 => new UpdatePlayerGameTypePacket(),
				152 => new EmoteListPacket(),
				153 => new PositionTrackingDBServerBroadcastPacket(),
				154 => new PositionTrackingDBClientRequestPacket(),
				155 => new DebugInfoPacket(),
				156 => new PacketViolationWarningPacket(),
				157 => new MotionPredictionHintsPacket(),
				158 => new AnimateEntityPacket(),
				159 => new CameraShakePacket(),
				160 => new PlayerFogPacket(),
				161 => new CorrectPlayerMovePredictionPacket(),
				162 => new ItemRegistryPacket(),
				164 => new ClientboundDebugRendererPacket(),
				165 => new SyncActorPropertyPacket(),
				166 => new AddVolumeEntityPacket(),
				167 => new RemoveVolumeEntityPacket(),
				168 => new SimulationTypePacket(),
				169 => new NpcDialoguePacket(),
				170 => new EduUriResourcePacket(),
				171 => new CreatePhotoPacket(),
				172 => new UpdateSubChunkBlocksPacket(),
				174 => new SubChunkPacket(),
				175 => new SubChunkRequestPacket(),
				176 => new PlayerStartItemCooldownPacket(),
				177 => new ScriptMessagePacket(),
				178 => new CodeBuilderSourcePacket(),
				179 => new TickingAreasLoadStatusPacket(),
				180 => new DimensionDataPacket(),
				181 => new AgentActionEventPacket(),
				182 => new ChangeMobPropertyPacket(),
				183 => new LessonProgressPacket(),
				184 => new RequestAbilityPacket(),
				185 => new RequestPermissionsPacket(),
				186 => new ToastRequestPacket(),
				187 => new UpdateAbilitiesPacket(),
				188 => new UpdateAdventureSettingsPacket(),
				189 => new DeathInfoPacket(),
				190 => new EditorNetworkPacket(),
				191 => new FeatureRegistryPacket(),
				192 => new ServerStatsPacket(),
				193 => new RequestNetworkSettingsPacket(),
				194 => new GameTestRequestPacket(),
				195 => new GameTestResultsPacket(),
				196 => new UpdateClientInputLocksPacket(),
				198 => new CameraPresetsPacket(),
				199 => new UnlockedRecipesPacket(),
				300 => new CameraInstructionPacket(),
				302 => new TrimDataPacket(),
				303 => new OpenSignPacket(),
				304 => new AgentAnimationPacket(),
				305 => new RefreshEntitlementsPacket(),
				306 => new PlayerToggleCrafterSlotRequestPacket(),
				307 => new SetPlayerInventoryOptionsPacket(),
				308 => new SetHudPacket(),
				309 => new AwardAchievementPacket(),
				310 => new ClientboundCloseFormPacket(),
				312 => new ServerboundLoadingScreenPacket(),
				313 => new JigsawStructureDataPacket(),
				314 => new CurrentStructureFeaturePacket(),
				315 => new ServerboundDiagnosticsPacket(),
				316 => new CameraAimAssistPacket(),
				317 => new ContainerRegistryCleanupPacket(),
				318 => new MovementEffectPacket(),
				320 => new CameraAimAssistPresetsPacket(),
				321 => new ClientCameraAimAssistPacket(),
				322 => new ClientMovementPredictionSyncPacket(),
				323 => new UpdateClientOptionsPacket(),
				324 => new PlayerVideoCapturePacket(),
				325 => new PlayerUpdateEntityOverridesPacket(),
				326 => new PlayerLocationPacket(),
				327 => new ClientboundControlSchemeSetPacket(),
				328 => new PrimitiveShapesPacket(),
				329 => new ServerboundPackSettingChangePacket(),
				330 => new ClientboundDataStorePacket(),
				331 => new GraphicsOverrideParameterPacket(),
				332 => new ServerboundDataStorePacket(),
				333 => new ClientboundDataDrivenUIShowScreenPacket(),
				334 => new ClientboundDataDrivenUICloseScreenPacket(),
				335 => new ClientboundDataDrivenUIReloadPacket(),
				336 => new ClientboundTextureShiftPacket(),
				337 => new VoxelShapesPacket(),
				338 => new CameraSplinePacket(),
				339 => new CameraAimAssistActorPriorityPacket(),
				340 => new ResourcePacksReadyForValidationPacket(),
				341 => new LocatorBarPacket(),
				342 => new PartyChangedPacket(),
				343 => new ServerboundDataDrivenScreenClosedPacket(),
				344 => new SyncWorldClocksPacket(),
				345 => new ClientboundAttributeLayerSyncPacket(),
				346 => new ServerStoreInfoPacket(),
				347 => new ServerPresenceInfoPacket(),
				348 => new ClientboundUpdateSoundDataPacket(),
				349 => new SendPartyDestinationCookiePacket(),
				350 => new PartyDestinationCookieResponsePacket(),
				_ => throw new KeyNotFoundException($"未注册的包 ID: {packetId}"),
			};
		}

		public static IPacket CreatePacket(MinecraftPacketIds packetId)
		{
			return CreatePacket((int)packetId);
		}

		public static T CreatePacket<T>() where T : IPacket, new()
		{
			return new T();
		}
	}
}
