// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class BiomeCoordinateData
	{
		public int MinValueType { get; set; } 
		public ushort MinValue { get; set; }
		public int MaxValueType { get; set; } 
		public ushort MaxValue { get; set; }
		public uint GridOffset { get; set; }
		public uint GridStepSize { get; set; }
		public Protocol.SharedTypes.v1_21_10.RandomDistributionType Distribution { get; set; } 

		public void Read(MemoryStreamReader reader)
		{
			MinValueType = VarInt.ReadInt32(reader); 
			MinValue = reader.ReadUInt16();
			MaxValueType = VarInt.ReadInt32(reader); 
			MaxValue = reader.ReadUInt16();
			GridOffset = reader.ReadUInt32();
			GridStepSize = reader.ReadUInt32();
			Distribution = (Protocol.SharedTypes.v1_21_10.RandomDistributionType)VarInt.ReadInt32(reader); 
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteVarInt32(MinValueType); 
			writer.WriteUInt16(MinValue);
			writer.WriteVarInt32(MaxValueType); 
			writer.WriteUInt16(MaxValue);
			writer.WriteUInt32(GridOffset);
			writer.WriteUInt32(GridStepSize);
			writer.WriteVarInt32((int)Distribution); 
		}
	}
}
