// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class BiomeTagsData
	{
		public List<ushort> Tags { get; set; } = new List<ushort>();

		public void Read(MemoryStreamReader reader)
		{
			Tags = reader.ReadSlice(() => reader.ReadUInt16());
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteSlice(Tags, v => writer.WriteUInt16(v));
		}
	}
}
