// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class BiomeConsolidatedFeatureData
	{
		public BiomeScatterParamData Scatter { get; set; }
		public ushort Feature { get; set; }
		public ushort Identifier { get; set; }
		public ushort Pass { get; set; }
		public bool CanUseInternalFeature { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			Scatter = new BiomeScatterParamData();
			Scatter.Read(reader);
			Feature = reader.ReadUInt16();
			Identifier = reader.ReadUInt16();
			Pass = reader.ReadUInt16();
			CanUseInternalFeature = reader.ReadByte() != 0;
		}

		public void Write(MemoryStreamWriter writer)
		{
			Scatter.Write(writer);
			writer.WriteUInt16(Feature);
			writer.WriteUInt16(Identifier);
			writer.WriteUInt16(Pass);
			writer.WriteByte(CanUseInternalFeature ? (byte)1 : (byte)0);
		}
	}
}
