// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class BiomeSurfaceMaterialData
	{
		public uint TopBlock { get; set; }
		public uint MidBlock { get; set; }
		public uint SeaFloorBlock { get; set; }
		public uint FoundationBlock { get; set; }
		public uint SeaBlock { get; set; }
		public int SeaFloorDepth { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			TopBlock = reader.ReadUInt32();
			MidBlock = reader.ReadUInt32();
			SeaFloorBlock = reader.ReadUInt32();
			FoundationBlock = reader.ReadUInt32();
			SeaBlock = reader.ReadUInt32();
			SeaFloorDepth = reader.ReadInt32();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteUInt32(TopBlock);
			writer.WriteUInt32(MidBlock);
			writer.WriteUInt32(SeaFloorBlock);
			writer.WriteUInt32(FoundationBlock);
			writer.WriteUInt32(SeaBlock);
			writer.WriteInt32(SeaFloorDepth);
		}
	}
}
