// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class BiomeCappedSurfaceData
	{
		public List<uint> FloorBlocks { get; set; } = new List<uint>();
		public List<uint> CeilingBlocks { get; set; } = new List<uint>();
		public Optional<uint> SeaBlock { get; set; } = new Optional<uint>();
		public Optional<uint> FoundationBlock { get; set; } = new Optional<uint>();
		public Optional<uint> BeachBlock { get; set; } = new Optional<uint>();

		public void Read(MemoryStreamReader reader)
		{
			FloorBlocks = reader.ReadSlice(() => reader.ReadUInt32());
			CeilingBlocks = reader.ReadSlice(() => reader.ReadUInt32());
			if (reader.ReadByte() != 0)
			{
				SeaBlock = new Optional<uint>(reader.ReadUInt32());
			}
			if (reader.ReadByte() != 0)
			{
				FoundationBlock = new Optional<uint>(reader.ReadUInt32());
			}
			if (reader.ReadByte() != 0)
			{
				BeachBlock = new Optional<uint>(reader.ReadUInt32());
			}
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteSlice(FloorBlocks, v => writer.WriteUInt32(v));
			writer.WriteSlice(CeilingBlocks, v => writer.WriteUInt32(v));
			if (SeaBlock != null && SeaBlock.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteUInt32(SeaBlock.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (FoundationBlock != null && FoundationBlock.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteUInt32(FoundationBlock.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (BeachBlock != null && BeachBlock.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteUInt32(BeachBlock.Value);
			}
			else
			{
				writer.WriteByte(0);
			}
		}
	}
}
