// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>

namespace Protocol
{
	public enum BiomeTemperatureCategory
	{
		Medium = 0,
		Warm = 1,
		Lukewarm = 2,
		Cold = 3,
		Frozen = 4,
	}
}
