// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class BiomeDefinitionData
	{
		public ushort Id { get; set; }
		public float Temperature { get; set; }
		public float Downfall { get; set; }
		public float FoliageSnow { get; set; }
		public float Depth { get; set; }
		public float Scale { get; set; }
		public int MapWaterColorARGB { get; set; }
		public bool Rain { get; set; }
		public Optional<BiomeTagsData> Tags { get; set; } = new Optional<BiomeTagsData>();
		public Optional<BiomeDefinitionChunkGenData> ChunkGenData { get; set; } = new Optional<BiomeDefinitionChunkGenData>();

		public void Read(MemoryStreamReader reader)
		{
			Id = reader.ReadUInt16();
			Temperature = reader.ReadSingle();
			Downfall = reader.ReadSingle();
			FoliageSnow = reader.ReadSingle();
			Depth = reader.ReadSingle();
			Scale = reader.ReadSingle();
			MapWaterColorARGB = reader.ReadInt32();
			Rain = reader.ReadByte() != 0;
			if (reader.ReadByte() != 0)
			{
				var _TagsValue = new BiomeTagsData();
				_TagsValue.Read(reader);
				Tags = new Optional<BiomeTagsData>(_TagsValue);
			}
			if (reader.ReadByte() != 0)
			{
				var _ChunkGenDataValue = new BiomeDefinitionChunkGenData();
				_ChunkGenDataValue.Read(reader);
				ChunkGenData = new Optional<BiomeDefinitionChunkGenData>(_ChunkGenDataValue);
			}
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteUInt16(Id);
			writer.WriteSingle(Temperature);
			writer.WriteSingle(Downfall);
			writer.WriteSingle(FoliageSnow);
			writer.WriteSingle(Depth);
			writer.WriteSingle(Scale);
			writer.WriteInt32(MapWaterColorARGB);
			writer.WriteByte(Rain ? (byte)1 : (byte)0);
			if (Tags != null && Tags.HasValue)
			{
				writer.WriteByte(1);
				Tags.Value.Write(writer);
			}
			else
			{
				writer.WriteByte(0);
			}
			if (ChunkGenData != null && ChunkGenData.HasValue)
			{
				writer.WriteByte(1);
				ChunkGenData.Value.Write(writer);
			}
			else
			{
				writer.WriteByte(0);
			}
		}
	}
}
