// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class BiomeElementData
	{
		public float NoiseFreqScale { get; set; }
		public float NoiseLowerBound { get; set; }
		public float NoiseUpperBound { get; set; }
		public int HeightMinType { get; set; } 
		public ushort HeightMin { get; set; }
		public int HeightMaxType { get; set; } 
		public ushort HeightMax { get; set; }
		public BiomeSurfaceMaterialData AdjustedMaterials { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			NoiseFreqScale = reader.ReadSingle();
			NoiseLowerBound = reader.ReadSingle();
			NoiseUpperBound = reader.ReadSingle();
			HeightMinType = VarInt.ReadInt32(reader); 
			HeightMin = reader.ReadUInt16();
			HeightMaxType = VarInt.ReadInt32(reader); 
			HeightMax = reader.ReadUInt16();
			AdjustedMaterials = new BiomeSurfaceMaterialData();
			AdjustedMaterials.Read(reader);
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteSingle(NoiseFreqScale);
			writer.WriteSingle(NoiseLowerBound);
			writer.WriteSingle(NoiseUpperBound);
			writer.WriteVarInt32(HeightMinType); 
			writer.WriteUInt16(HeightMin);
			writer.WriteVarInt32(HeightMaxType); 
			writer.WriteUInt16(HeightMax);
			AdjustedMaterials.Write(writer);
		}
	}
}
