// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class BiomeClimateData
	{
		public float Temperature { get; set; }
		public float Downfall { get; set; }
		public float SnowAccumulationMin { get; set; }
		public float SnowAccumulationMax { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			Temperature = reader.ReadSingle();
			Downfall = reader.ReadSingle();
			SnowAccumulationMin = reader.ReadSingle();
			SnowAccumulationMax = reader.ReadSingle();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteSingle(Temperature);
			writer.WriteSingle(Downfall);
			writer.WriteSingle(SnowAccumulationMin);
			writer.WriteSingle(SnowAccumulationMax);
		}
	}
}
