// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class BiomeReplacementData
	{
		public ushort ReplacementBiome { get; set; }
		public ushort Dimension { get; set; }
		public List<ushort> TargetBiomes { get; set; } = new List<ushort>();
		public float Amount { get; set; }
		public float NoiseFrequencyScale { get; set; }
		public uint ReplacementIndex { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			ReplacementBiome = reader.ReadUInt16();
			Dimension = reader.ReadUInt16();
			TargetBiomes = reader.ReadSlice(() => reader.ReadUInt16());
			Amount = reader.ReadSingle();
			NoiseFrequencyScale = reader.ReadSingle();
			ReplacementIndex = reader.ReadUInt32();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteUInt16(ReplacementBiome);
			writer.WriteUInt16(Dimension);
			writer.WriteSlice(TargetBiomes, v => writer.WriteUInt16(v));
			writer.WriteSingle(Amount);
			writer.WriteSingle(NoiseFrequencyScale);
			writer.WriteUInt32(ReplacementIndex);
		}
	}
}
