// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class BiomeReplacementsData
	{
		public List<BiomeReplacementData> BiomeReplacements { get; set; } = new List<BiomeReplacementData>();

		public void Read(MemoryStreamReader reader)
		{
			BiomeReplacements = reader.ReadSlice(() => { var _Item = new BiomeReplacementData(); _Item.Read(reader); return _Item; });
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteSlice(BiomeReplacements, v => v.Write(writer));
		}
	}
}
