// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class DataItemInt64Payload
	{
		public Protocol.DataItemType Type_ { get; set; }
		public long Value { get; set; } 

		public void Read(MemoryStreamReader reader)
		{
			Type_ = (Protocol.DataItemType)reader.ReadByte();
			Value = VarInt.ReadInt64(reader); 
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteByte((byte)Type_);
			writer.WriteVarInt64(Value); 
		}
	}
}
