// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class ChangePlayerScore
	{
		public Protocol.ScorePacketEntryAction Action { get; set; }
		public ScoreboardId ScoreboardId { get; set; }
		public string ObjectiveName { get; set; }
		public int ScoreValue { get; set; }
		public PlayerScoreboardId PlayerUniqueId { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			Action = EnumCodec.FromString<Protocol.ScorePacketEntryAction>(reader.ReadLengthPrefixedString());
			ScoreboardId = new ScoreboardId();
			ScoreboardId.Read(reader);
			ObjectiveName = reader.ReadLengthPrefixedString();
			ScoreValue = reader.ReadInt32();
			PlayerUniqueId = new PlayerScoreboardId();
			PlayerUniqueId.Read(reader);
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(EnumCodec.ToString(Action));
			ScoreboardId.Write(writer);
			writer.WriteLengthPrefixedString(ObjectiveName);
			writer.WriteInt32(ScoreValue);
			PlayerUniqueId.Write(writer);
		}
	}
}
