// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>

namespace Protocol
{
	public enum ScorePacketEntryAction
	{
		Remove = 0,
		ChangePlayer = 1,
		ChangeEntity = 2,
		ChangeFakePlayer = 3,
	}
}
