// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class ScoreboardIdentityPacketInfo
	{
		public ScoreboardId ScoreboardId { get; set; }
		public Optional<long> PlayerUniqueId { get; set; } = new Optional<long>(); 

		public void Read(MemoryStreamReader reader)
		{
			ScoreboardId = new ScoreboardId();
			ScoreboardId.Read(reader);
			if (reader.ReadByte() != 0)
			{
				PlayerUniqueId = new Optional<long>(VarInt.ReadInt64(reader)); 
			}
		}

		public void Write(MemoryStreamWriter writer)
		{
			ScoreboardId.Write(writer);
			if (PlayerUniqueId != null && PlayerUniqueId.HasValue)
			{
				writer.WriteByte(1);
				writer.WriteVarInt64(PlayerUniqueId.Value); 
			}
			else
			{
				writer.WriteByte(0);
			}
		}
	}
}
