// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.WaypointGroup
{
	public class WaypointHandle
	{
		public mce.UUID UUID { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			UUID = new mce.UUID();
			UUID.Read(reader);
		}

		public void Write(MemoryStreamWriter writer)
		{
			UUID.Write(writer);
		}
	}
}
