// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class EnchantmentInstance
	{
		public Protocol.Enchant.Type EnchantType { get; set; }
		public byte EnchantLevel { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			EnchantType = (Protocol.Enchant.Type)reader.ReadByte();
			EnchantLevel = (byte)reader.ReadByte();
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteByte((byte)EnchantType);
			writer.WriteByte(EnchantLevel);
		}
	}
}
