// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types
{
	public class ItemEnchantOption
	{
		public byte Cost { get; set; }
		public ItemEnchants Enchants { get; set; }
		public string EnchantName { get; set; }
		public TypedServerNetId_struct_RecipeNetIdTag EnchantNetId { get; set; }

		public void Read(MemoryStreamReader reader)
		{
			Cost = (byte)reader.ReadByte();
			Enchants = new ItemEnchants();
			Enchants.Read(reader);
			EnchantName = reader.ReadLengthPrefixedString();
			EnchantNetId = new TypedServerNetId_struct_RecipeNetIdTag();
			EnchantNetId.Read(reader);
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteByte(Cost);
			Enchants.Write(writer);
			writer.WriteLengthPrefixedString(EnchantName);
			EnchantNetId.Write(writer);
		}
	}
}
