// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.AvailableCommandsPacketPayload
{
	public class ChainedSubcommandRelationship
	{
		public uint SubCommandFirstValue { get; set; } 
		public uint SubCommandSecondValue { get; set; } 

		public void Read(MemoryStreamReader reader)
		{
			SubCommandFirstValue = VarInt.ReadUInt32(reader); 
			SubCommandSecondValue = VarInt.ReadUInt32(reader); 
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteVarUInt32(SubCommandFirstValue); 
			writer.WriteVarUInt32(SubCommandSecondValue); 
		}
	}
}
