// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.AvailableCommandsPacketPayload
{
	public class ConstrainedValueData
	{
		public uint EnumValueSymbol { get; set; }
		public uint EnumSymbol { get; set; }
		public List<byte> ConstraintIndices { get; set; } = new List<byte>();

		public void Read(MemoryStreamReader reader)
		{
			EnumValueSymbol = reader.ReadUInt32();
			EnumSymbol = reader.ReadUInt32();
			ConstraintIndices = reader.ReadSlice(() => (byte)reader.ReadByte());
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteUInt32(EnumValueSymbol);
			writer.WriteUInt32(EnumSymbol);
			writer.WriteSlice(ConstraintIndices, v => writer.WriteByte(v));
		}
	}
}
