// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.AvailableCommandsPacketPayload
{
	public class ChainedSubcommandData
	{
		public string Name { get; set; }
		public List<ChainedSubcommandRelationship> SubCommandValues { get; set; } = new List<ChainedSubcommandRelationship>();

		public void Read(MemoryStreamReader reader)
		{
			Name = reader.ReadLengthPrefixedString();
			SubCommandValues = reader.ReadSlice(() => { var _Item = new ChainedSubcommandRelationship(); _Item.Read(reader); return _Item; });
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(Name);
			writer.WriteSlice(SubCommandValues, v => v.Write(writer));
		}
	}
}
