// <auto-generated>
//     由 Protocol.Gen 自动生成, 请勿手动修改
// </auto-generated>
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using OneOf;
using Protocol.Utility;
using Protocol.Utility.IO;

namespace Protocol.Types.AvailableCommandsPacketPayload
{
	public class EnumData
	{
		public string Name { get; set; }
		public List<uint> Values { get; set; } = new List<uint>();

		public void Read(MemoryStreamReader reader)
		{
			Name = reader.ReadLengthPrefixedString();
			Values = reader.ReadSlice(() => reader.ReadUInt32());
		}

		public void Write(MemoryStreamWriter writer)
		{
			writer.WriteLengthPrefixedString(Name);
			writer.WriteSlice(Values, v => writer.WriteUInt32(v));
		}
	}
}
